### ISSUE TITLE
DSL for ExpectedConditions.elementToBeClickable

### ISSUE THREAD

**Issue by manuelbernhardt** [FluentLenium/FluentLenium#105]
It'd be great to be able to write:

    browser.await().atMost(5, TimeUnit.SECONDS).until("#someId").isClickable

Which under the covers would use `ExpectedConditions.elementToBeClickable`, i.e.

    val wait = new WebDriverWait(browser.webDriver, 10)
    wait.until(ExpectedConditions.elementToBeClickable(By.id("someId")))

**Comment by logineimer** [comment]
Fixed!
