### ISSUE TITLE
Alert presence validation is incorrect/misleading

### ISSUE THREAD

**Issue by picimako** [FluentLenium/FluentLenium#1054]
I've been checking the implementation of `AlertImpl` and `AlertAssert` and noticed something.

An `AlertImpl` object can be instantiated successfully only when there is an actual alert present on the page, otherwise both consctuctors throw a `NoAlertPresentException`.
I guess that is why its `present()` method always returns true, because once the object is created it is for sure that the alert is present.

However `AlertAssert#isPresent()` implemented in the following way:

```java
@Override
public AlertStateAssert isPresent() {
    if (!actual.present()) {
        failWithMessage("There is no alert box");
    }
    return this;
}
```

in which, considering the construction of an `AlertImpl` instance, the `!actual.present()` check doesn't make sense because it won't be false ever.

If my presumption is correct, I see two approaches to handle this:
- either remove the `!actual.present()` check, and with that the whole `AlertAssert#isPresent()` method,
- or update the implementation of `AlertImpl` to be create the instance even when there is no alert present.

Which one would be preferable, or do you see any other possible approach?

**Comment by slawekradzyminski** [comment]
Hi @picimako 

I guess you should write E2E test first that integrates with alerts and then decide which approach is better. I don't have any preference regarding solutions. Make it work:)

**Comment by abendt** [comment]
i also noticed that while implementing (and testing) kotest custom assertions for alert: 

https://github.com/FluentLenium/FluentLenium/blob/develop/fluentlenium-kotest-assertions/src/test/kotlin/org/fluentlenium/kotest/matchers/alert/AlertMatchersSpec.kt#L18

currently its not possible to use the assertion to test for absence of the matcher without wrapping it in a try/catch
