### ISSUE TITLE
Running multiple browsers and switching between browsers in single test 

### ISSUE THREAD

**Issue by satnair** [FluentLenium/FluentLenium#110]
Given I setup a meeting on different browsers as:
      | Browser |
      | chrome  |
      | firefox |
And I have logged in as admin user in "chrome" browser
And I login as participant user in "firefox browser"
When I add a chat message from admin page
Then I should see the chat message in the participant page

Please let me know how to switch between browsers and do certain action after switching.

**Comment by MathildeLemee** [comment]
Hello,

You have to code your own driver provider ! Use the getDefaultDriver methods to provide the one you want.
