### ISSUE TITLE
Compile error when using FluentTestNgSpringTest

### ISSUE THREAD

**Issue by whitejeffreyl** [FluentLenium/FluentLenium#1156]
I am getting the following error when compiling.  The error is on this line:
public abstract class TestBaseLocalTestngSpring extends FluentTestNgSpringTest

ERROR:
java: cannot access org.fluentlenium.adapter.TestRunnerAdapter
  class file for org.fluentlenium.adapter.TestRunnerAdapter not found

Shouldn't it be looking for:
org.fluentlenium.adapter.FluentTestRunnerAdapter?

CODE EXCERPT:

@Slf4j
@SuppressWarnings("checkstyle:magicnumber")
@ContextConfiguration(locations = {"classpath:spring-test-config.xml"})
public abstract class TestBaseLocalTestngSpring extends FluentTestNgSpringTest {

    @Autowired
    private Config config;
    @Autowired
    private FluentConfig testConfig;

    protected SoftAssertions softAssertions;

    private Faker faker = new Faker();

**Comment by slawekradzyminski** [comment]
That's disappointing. Can you share your pom/gradle dependencies?

There is working example available here: https://github.com/FluentLenium/FluentLenium/tree/develop/examples/spring

Can you compare it with your project? I wonder what may be the reason. Maybe some kind of hotfix is required.

**Comment by whitejeffreyl** [comment]
This seems to not be an issue anymore.
