### ISSUE TITLE
Test checkAwaitEndsWithRegex KO on Chrome

### ISSUE THREAD

**Issue by lhuet** [FluentLenium/FluentLenium#116]
org.fluentlenium.integration.FluentLeniumWaitTest.checkAwaitEndsWithRegex() test Failed with chromedriver.

Starting ChromeDriver (v2.9.248304) on port 15212
[0,093][WARNING]: PAC support disabled because there is no system implementation

org.openqa.selenium.TimeoutException: Timed out after 0 seconds: Selector .small has not the size 1.[id$="null"] Filters : 
Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'

**Comment by filipcynarski** [comment]
Seems like your code issue. Unable to reproduce. Are you able to provide working example?
