### ISSUE TITLE
Wrong example on page https://fluentlenium.com/docs/key_features/#page-object-pattern-support

### ISSUE THREAD

**Issue by CamilleDesmots** [FluentLenium/FluentLenium#1198]
On page URL : https://fluentlenium.com/docs/key_features/#page-object-pattern-support

We've got this : 
 
    public SelectComponent(WebElement webElement, WebDriver driver, ComponentInstantiator instantiator) {
        super(webElement, driver, instantiator);
    }

but it should be : 

    public SelectComponent(WebElement webElement, FluentControl control, ComponentInstantiator instantiator) {
        super(webElement, control, instantiator);
    }

**Comment by filipcynarski** [comment]
Thank you for reporting the issue, we'll review documentation and fix the documentation errors.
