### ISSUE TITLE
Appium and Fluentlenium

### ISSUE THREAD

**Issue by puresk** [FluentLenium/FluentLenium#1210]
I am trying to setup Appium driver in Fluentlenium. I see there is _getAppiumDriver_. Does it do something? Like when i setup chromeDriver in Fluentlenium i am able to access it by _getDriver()_. I would really appreciate an code example for this one. Thanks!

**Comment by slawekradzyminski** [comment]
Hi @puresk :) Have you tried the steps described in docs?

https://fluentlenium.com/docs/appium-support/

**Comment by puresk** [comment]
Hi, thx for answer. I did not find the answer there. For WebAutomation i am doing something like the this: 

```
@FactoryName("exampleFactoryName")
public class ExampleFactory implements **WebDriverFactory** {
    @Override
    public WebDriver newWebDriver(Capabilities desiredCapabilities, ConfigurationProperties configuration) {
        //creating driver
    }
```

Then i am able to access it by `getDriver();`


I can create new Factory, but i am not sure this is the way here. Method `getAppiumDriver()` in `FluentControl` confuses me.

**Comment by puresk** [comment]
Ok, i found a way how to create AppiumDriver and using _getAppiumDriver()_ in my code! :-) Didn't see it at first.

**Comment by slawekradzyminski** [comment]
Cool :) Any suggestions for feature improvements?

**Comment by puresk** [comment]
No right now. Will raise a case if i will have :-)
