### ISSUE TITLE
@FindBy for Mac apps

### ISSUE THREAD

**Issue by puresk** [FluentLenium/FluentLenium#1211]
Hi, 

i was trying to find how to create pageObject for mac application. So far i see there is windows, android and ios for this purpose: [native_support](https://fluentlenium.com/docs/appium-support/#native-support). 

is there a way to use pageObject for mac or will this be supported in future? I am using appium-mac2-driver.

Thanks!

**Comment by slawekradzyminski** [comment]
@puresk isn't Xpath dedicated for such purposes?

**Comment by puresk** [comment]
@slawekradzyminski Thanks for answer! I've tried xpath and id and looks like it work pretty nice. Thanks!
