### ISSUE TITLE
Maintaining two drivers - appiumDriver, chromeDriver

### ISSUE THREAD

**Issue by puresk** [FluentLenium/FluentLenium#1212]
Hi, it's me again :) I have one last problem. How do you deal with a problem where you have to use two drivers. For example - you setup something on webSite (chromeDriver) and then you work with it in mac agent app (appiumDriver). I spend whole day trying to maintain two modules, each with driver it uses, but looks like this is not the way. I didn't succeed to initialize second driver. Thanks!

**Comment by slawekradzyminski** [comment]
@puresk I don't think it's a good idea to handle two different drivers simultaneously (even for Web-only automation). In my work I had similar setup but I run everything sequentially. I had package separation for web & mobile.

```
./gradlew test WebTest
./gradlew test MobileTest
```

**Comment by puresk** [comment]
@slawekradzyminski Thanks for answer! Yeah i see the issue here, but what about e2e tests then - where i need to access web and app in one test? So far i think i will have to create this instance of chromeDriver and maintain it by myself, which is not the best idea. Even pageObjects won't work. 

if anyone dealt with this issue, give me a hint! :-)
