### ISSUE TITLE
Stop using org.openqa.selenium.internal.WrapsElement

### ISSUE THREAD

**Issue by agavrilov76** [FluentLenium/FluentLenium#1222]
`FluentWebElement` implements `org.openqa.selenium.internal.WrapsElement` which is internal and has been removed in Selenium v4 causing `java.lang.NoClassDefFoundError: org/openqa/selenium/internal/WrapsElement` exception

**Comment by slawekradzyminski** [comment]
Hi @agavrilov76 - We don't support Selenium 4 yet
