### ISSUE TITLE
FluentLenium with Spock 2.0-groovy-3.0

### ISSUE THREAD

**Issue by b-palaniappan** [FluentLenium/FluentLenium#1272]
I recently upgraded Spock to `2.0-groovy-3.0` version. After upgrading to Spock 2.0 and Groovy 3.0 all my FluentLenium test cases are failing.

I use springboot (version `2.5.1`) project with with Gradle as build tool. Gradle config,
```groovy
    // Springboot test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Spock
    testImplementation 'org.spockframework:spock-spring:2.0-groovy-3.0'

    // fluentlenium integration testing with html unit
    testImplementation 'org.fluentlenium:fluentlenium-spock:4.6.2'
    testImplementation 'org.seleniumhq.selenium:htmlunit-driver:2.50.0'
    testImplementation 'net.sourceforge.htmlunit:htmlunit:2.50.0'
```

Sample testcase,

```groovy
import org.fluentlenium.adapter.spock.FluentSpecification

class DemoSpec extends FluentSpecification {
    def "hello world fluent spec"() {
        when:
        goTo("https://duckduckgo.com")
        $("#search_form_input_homepage").fill().with("FluentLenium")
        $("#search_button_homepage").submit()

        then:
        window().title().contains("FluentLenium")
    }
}
```

Stack trace,
```
java.lang.NullPointerException: Cannot invoke "org.fluentlenium.core.FluentControl.goTo(String)" because the return value of "org.fluentlenium.core.FluentControl.getFluentControl()" is null

	at org.fluentlenium.core.FluentControl.goTo(FluentControl.java:342)
	at io.c12.bala.web.leaf.DemoSpec.hello world fluent spec(DemoSpec.groovy:8)
```

**Comment by slawekradzyminski** [comment]
Hi @b-palaniappan :)

Good to know someone is using Spock module.

Spock 2 is not compatible with previous version (they have ditched junit4 in favour of junit5).  You can read about it here:
https://spockframework.org/spock/docs/2.0/migration_guide.html#_migration_guide_2_0

I have bumped our implementation in this PR, please note the addition of `spock-junit4` module:
https://github.com/FluentLenium/FluentLenium/pull/1259/files

You have 2 options:

- Wait for next FL release where Spock 2 is supported (it's going to happen soon)

- Try experimenting with `spock-junit4` but I can't guarantee you success

**Comment by b-palaniappan** [comment]
Hi @slawekradzyminski,

Thanks for the quick reply. I am a great fan of Spock framework, I use it for all our Springboot projects for Unit and Integration testing.

I will try with `spock-junit4`. I was expecting this may be the issue :-)

**Comment by b-palaniappan** [comment]
Thanks @slawekradzyminski it works great. Thanks again for fix it so quickly.
