### ISSUE TITLE
Add kotlin DSL module

### ISSUE THREAD

**Issue by christian-draeger** [FluentLenium/FluentLenium#1280]
As discussed in https://github.com/FluentLenium/FluentLenium/issues/1250#issuecomment-856184200 fluentlenium could provide a kotlin dsl module and thereby increase kotlin support by using language capabilities to write highly readable tests

**Comment by filipcynarski** [comment]
@christian-draeger please rise PR if you need - we are open source and happy to include the module and you can help us to be better
