### ISSUE TITLE
Make isEnabled() check 'disabled' attribute on any element

### ISSUE THREAD

**Issue by alias1** [FluentLenium/FluentLenium#130]
In [FluentWebElement.isEnabled()](https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/core/domain/FluentWebElement.java#L147)

Add something like:
```
boolean isDisabledByAttribute = element.getAttribute("disabled") != null;
```

Eg.
```
public boolean isEnabled() {
 boolean isDisabledByAttribute = element.getAttribute("disabled") != null;
  return webElement.isEnabled() && !isDisabledByAttribute;
}
```

Ref: [WebElement.getAttribute()](http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/WebElement.html#getAttribute(java.lang.String))

**Comment by j-walker23** [comment]
Thanks for this! Quick question if someone sees this. If i have just a `WebElement` can i create a `FluentWebElement` from it?

**Comment by MathildeLemee** [comment]
Yes, you can use the constructor 
    public FluentWebElement(WebElement webElement)
