### ISSUE TITLE
Error occurred for appium FluentDriver - You should use getAppiumDriver() method for mobile automation

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [FluentLenium/FluentLenium#1337]
I have overridden the newWebDriver with the following implementation

```
  @Override
    public AppiumDriver<?> newWebDriver()
    {
        final AppiumDriver<?> appiumDriver = new AppiumDriver<MobileElement>(driverLocalService, getCapabilities());

        return appiumDriver;
    }

```
The driver is successfully created and erroring out when finding the elements

```
el(MobileBy.AndroidUIAutomator(locator)).displayed();
el(MobileBy.AndroidUIAutomator(locator)).click();

```

Also, I have overridden and tried with getAppiumDriver as follows

```
@Override
    public AppiumDriver<?> getAppiumDriver()
    {
        final AppiumDriver<?> appiumDriver = new AppiumDriver<MobileElement>(driverLocalService, getCapabilities());

        return appiumDriver;
    }
```

Getting another error.

`Caused by: java.util.concurrent.ExecutionException: org.fluentlenium.configuration.ConfigurationException: Can't create new WebDriver instance
`

**Comment by filipcynarski** [comment]
Please take a look on Appium Examples in examples directory and let us know if you need more assistance @ramkumar-yoganathan
