### ISSUE TITLE
Shadow DOM is not working

### ISSUE THREAD

**Issue by ramkumar-yoganathan** [FluentLenium/FluentLenium#1346]
I used the annotation @Unshadow with CSS selectors. But the error message says id or name is not found which is not relevant to the object. Here is my code

```
   @Unshadow(css = {"zwe-marketplace-product-listing", "span:nth-child(2)"})
    private FluentWebElement lnkInventoryManagement;

    @Unshadow(css = {"zwe-marketplace-product-listing", "div:nth-child(3)", "div:nth-child(1)", "a"})
    private FluentWebElement lnkVoucherCodes;
```
Output

`org.openqa.selenium.NoSuchElementException: Element by id or name "lnkInventoryManagement" (first) (Lazy Element) is not present`

Assuming that, it was finding using id or name instead of CSS

**Comment by filipcynarski** [comment]
Hello @ramkumar-yoganathan could you please try with 5.0.2 version you need to use Selenium 4 - I have fixed it and released today.
