### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by EECOLOR** [FluentLenium/FluentLenium#135]
The documentation states:

> This will click on all the visible fields returned by the search.

This however is not the case. This is probably cause by the `$(...)` selector being used. It will also return non-visible elements. There should probably be a filter that should be introduced.

If you want to keep it compatible with jquery, support the `:visible` selector: http://api.jquery.com/visible-selector/

**Comment by MathildeLemee** [comment]
Fix with https://github.com/FluentLenium/FluentLenium/commit/379f8f67e2fae47023a1c628bb217e6d799563bd
