### ISSUE TITLE
Upgrade to Selenium 4.1

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#1372]

**Comment by abendt** [comment]
hey @filipcynarski 

have a look at https://github.com/FluentLenium/FluentLenium/pull/1380
it took existing PR from https://github.com/FluentLenium/FluentLenium/pull/1084
and made all necessary further changes. its using Selenium 4.1 now

Tests all green

**Comment by slawekradzyminski** [comment]
Done :)
