### ISSUE TITLE
Drop support for Java 8

### ISSUE THREAD

**Issue by slawekradzyminski** [FluentLenium/FluentLenium#1414]
Maintaining Java-8 compatibility is a burden for us which we would love to drop. Additionally, latest features and releases are Java 11 only.

I'm creating this ticket to gather initial feedback about it. Java 8 end of life is on 31 Mar 2022 but perhaps we should cut the cord earlier.

**Comment by abendt** [comment]
testng 7.6.0 now has JDK11 as minimum requirement: https://github.com/cbeust/testng/blob/master/CHANGES.txt
In consequence we are stuck with testng 7.5 https://github.com/FluentLenium/FluentLenium/pull/1568

**Comment by filipcynarski** [comment]
We can override versions in profiles I'm doing so now @abendt

**Comment by abendt** [comment]
apparently the released version is not usable with jdk8. think its compiled with target version 11.

**Comment by abendt** [comment]
spring 6 now has JDK17 as minimum requirement

**Comment by filipcynarski** [comment]
I think we should drop the Java 8 support officially in next release

**Comment by filipcynarski** [comment]
@abendt it is done and merged to develop
