### ISSUE TITLE
Test execution reports.

### ISSUE THREAD

**Issue by LucaLis** [FluentLenium/FluentLenium#1472]
Hello Guys!

Do you have any advice regarding reporting? You have supplied quite a lot of test examples but I haven't found much about reporting. It would be great if you could comment on that and share how you address this aspect.

To be more specific - this is what I'm aiming for:
- generate html report 
- attach screenshots (one or is possible more per test)
- attach text (e.g. add some text per test execution e.g. error logged in browser console)

I can probably do it all using features for specific test runner but I've decided to ask before I'll start reinventing the wheel... 

PS:
You are doing awesome job!

Thanks,
Luke

**Comment by abendt** [comment]
hey Luke,

afaik there is no out of the box solution provided by fluentlenium. What i have used in the past:
* Usually it was enough to just have the screenshot of a failing test. Fluentlenium allows you to do that. Then we Used to have some listener code that would print out the screenshot name as part of the test output. This would allow then to navigate from a junit report to the respective screenshot.
* https://docs.qameta.io/allure/ This allows you to create nice reports. It also offers an API to e.g. add artifacts/texts/etc to the report. If you are willing to write some glue code this should be really flexible.
