### ISSUE TITLE
Setting capabilities while in test / change the name of the test

### ISSUE THREAD

**Issue by ttwhy** [FluentLenium/FluentLenium#1506]
I try to write a test and submit the name as a capability to the remoteDriver. The only way this takes affect (change the name of the test within selenium grid) is if i set the capabilities within the "beforeTest". Therefor i can not use getTestMethodName as i am currently not in the Test Context (cause i am before the test context). 
Setting the capabilities within the test doesn't have any effect as the webdriver is already loaded. 
Is there anything i can do to come around this issue? Is there a best Practice to set the name of a test?

**Comment by filipcynarski** [comment]
Please share your project/code within example what is not working for you - I cannot provide an answer basing on this description @ttwhy
