### ISSUE TITLE
Unable to retrieve a WebElement in a shadow DOM

### ISSUE THREAD

**Issue by phileti** [FluentLenium/FluentLenium#1508]
Hello,
I'm having trouble retrieve WebElements in a shadow DOM.
My project is using Fluentlenium 5.0.3 and Selenium 4.1.2 under Chrome webdriver.
I declare
```
@Unshadow(css = {"#shadow_host", "#shadow_content"})
private FluentWebElement span;
```
and when executing I get the error
```
org.openqa.selenium.NoSuchElementException: Element by id or name "span" (first) (Lazy Element) is not present
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'xxxxxxxxxx', ip: 'xxxxxxxxxxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17'
	at org.fluentlenium.core.domain.ElementUtils.noSuchElementException(ElementUtils.java:27)
	at org.fluentlenium.core.proxy.LocatorHandler.noSuchElement(LocatorHandler.java:86)
	at org.fluentlenium.core.proxy.ComponentHandler.getLocatorResultImpl(ComponentHandler.java:73)
	at org.fluentlenium.core.proxy.ComponentHandler.getLocatorResultImpl(ComponentHandler.java:18)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.getLocatorResult(AbstractLocatorHandler.java:69)
	at org.fluentlenium.core.proxy.AbstractLocatorAndInvocationHandler.invoke(AbstractLocatorAndInvocationHandler.java:52)
	at org.fluentlenium.core.proxy.ComponentHandler.invoke(ComponentHandler.java:98)
	at jdk.proxy2/jdk.proxy2.$Proxy63.getText(Unknown Source)
	at org.fluentlenium.core.domain.FluentWebElement.text(FluentWebElement.java:635)
	at fr.phe.ju5.pages.WatirPage.getShadowRootSpanText(WatirPage.java:29)
	at fr.phe.ju5.tests.ShadowJUnit5.checkShadowItem(ShadowJUnit5.java:33)
```
It looks like Selenium is looking for the WebElement by the variable name and not by the selector provided.
When I inspect the span variable in the debugger, I get
![2022-03-11_17h00_27](https://user-images.githubusercontent.com/101417582/158072986-1101ef4a-19f8-441d-abfc-a935cfb3e1ac.png)
ShadowRootTest in FluentLenium Integration Tests (https://github.com/FluentLenium/FluentLenium/tree/develop/fluentlenium-integration-tests/src/test/java/org/fluentlenium/test/shadowroot) works fine. 
![2022-03-11_17h04_51](https://user-images.githubusercontent.com/101417582/158073025-40b1bedc-cc8c-43f1-b8bc-ee6494a6ce68.png)
Is it because it uses a file URL instead of a web URL? Or is there an error in my project that I can't see?
Here is the link of the example project that I created for the occasion: [https://github.com/phileti/shadow-fluentlenium-JU5](https://github.com/phileti/shadow-fluentlenium-JU5)
Thank you in advance for your feedback.

**Comment by filipcynarski** [comment]
Hello @phileti 

Thank you for reporting the issues. Since the ShadowRoot support is quite fresh feature in FluentLenium it might be possible we need to improve some functionality.

Currently your example is missing html file which you are trying to open, could you please add this page to the resources directory and push your changes to exemplary project you created for us to investigate?

Static file shouldn't be a problem because our integration tests are using html files from FS and it is working fine. Your code looks also good, so please share this page with us so I can investigate further.

Cheers

**Comment by phileti** [comment]
Hello @filipcynarski 
Thank you for considering my request.
URL is http://watir.com/examples/shadow_dom.html and is declared in project file shadow-fluentlenium-JU5/src/main/java/fr/phe/ju5/pages/WatirPage.java 
`@PageUrl("http://watir.com/examples/shadow_dom.html")`

**Comment by filipcynarski** [comment]
@phileti Please check with newest Selenium and newest FluentLenium from io.fluentlenium if it is not working reopen and we can take a closer look.
