### ISSUE TITLE
Proposal of "find" method with only filters argument

### ISSUE THREAD

**Issue by NozomiIto** [FluentLenium/FluentLenium#151]
I think the test codes to find an element by name attribute by FluentLenium are below 3 patterns:

#### 1

```Java
fill("[name=abc]").with("test");
 ```
I don't feel the code is elegant...

#### 2
```Java
fill("input", withName("abc")).with("test");
```
I think this code is recommended in FluentLenium README now.
But I think this selector is brittle.
This selector requires modification 
if element type is changed from "input" to "textarea" in the future.

#### 3
```Java
fill("*", withName("abc")).with("test");
```
This selector is not brittle, but I feel this is redundant..

---------------------------------
So, I want to write as below:
```Java
fill(withName("abc")).with("test");
```
I think this is good idea since $ method in Geb already has similar API:
```Groovy
$(name:"abc")
```

Has FluentLenium already provided such API?
If not, do you think this is good idea?
If you think this is good idea, I want to try implementing this idea 
to all methods with cssSelector and filters arguments, and send pull requrest!!

**Comment by MathildeLemee** [comment]
That looks like a good idea, you can submit a PR :)

**Comment by NozomiIto** [comment]
Thank you for your quick reply.
I will try!

**Comment by NozomiIto** [comment]
Merged. Thank you!
