### ISSUE TITLE
Prevent start of Firefox

### ISSUE THREAD

**Issue by logineimer** [FluentLenium/FluentLenium#154]
Hello,

is it possible to prevent Firefox from starting automatically? I use the IEDriverServer.exe as my WebDriver. However, everytime a test starts Firefox will show up showing nothing.

Thanks in advance!

**Comment by NozomiIto** [comment]
Do you override getDefaultDriver method?
If this method is not overridden, FirefoxDriver is used for your test.
The following page may help you:
http://stackoverflow.com/questions/17070725/how-can-i-setup-fluentlenium-to-run-in-different-browser-drivers

**Comment by logineimer** [comment]
Thank you for the fast reply! I formerly overrid getDriver() method instead of getDefaultDriver() which I figured out recently. It's working now. :)

**Comment by NozomiIto** [comment]
I think getDriver() should not be overridden.
Overriding getDefaultDriver() is the recommended approach.
