### ISSUE TITLE
Enhance fillSelect() of #80

### ISSUE THREAD

**Issue by logineimer** [FluentLenium/FluentLenium#155]
Hello!

I'd be glad if I can do something like element.fillSelect().with("Test"); just like in element.fill().with("Test");

That would be a great feature. :)

**Comment by j-walker23** [comment]
Also this one fillSelect(element).withIndex(value)?

@logineimer is there anyway currently to fill a select list using a FluentWebElement?

ps. To the author(s), seriously thank you for this tool. This shit is awesome!!! I am trying to change the whole company to these patterns, so much cleaner then the ugly native driver.findElement everywhere with lame PageObject patterns.

**Comment by logineimer** [comment]
Is b1451c5 stable to merge? It's seems not to be present in master yet.
