### ISSUE TITLE
No Tests Found - Fluentlenium Spring Testng ver. 5.0.3

### ISSUE THREAD

**Issue by whitejeffreyl** [FluentLenium/FluentLenium#1554]
If I run with the uncommented versions I can run my tests. If I comment it out and use the latest version, I get "No Tests Found". 

All others things being equal, why would this be?   This happens when I try to run via the testng.xml or by using Intellij's TestNG plugin to run each test manually (both run and debug mode). 
    
    
<img width="444" alt="Screen Shot 2022-04-25 at 11 08 42 AM" src="https://user-images.githubusercontent.com/4417751/165117959-758e4272-e6da-4a2a-a1d4-a189eb3c5ea7.png">

MOST OF THE POM (minus the secure stuff):

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.nextgearcapital</groupId>
    <artifactId>salesforce-ui-automation</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>salesforce-ui-automation</name>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
        <relativePath/>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <lombok.version>1.18.12</lombok.version>
        <failsafe.version>3.0.0-M4</failsafe.version>
        <assertj-core.version>3.11.1</assertj-core.version>
        <jackson-datatype-joda.version>2.9.7</jackson-datatype-joda.version>
        <maven-checkstyle-plugin.version>2.17</maven-checkstyle-plugin.version>
        <excluded.tests>**/validation/**</excluded.tests>
        <webdrivermanager.version>5.1.0</webdrivermanager.version>
        <mockito.core.version>2.23.0</mockito.core.version>
        <spring-profile>sit</spring-profile>
        <joda-time.version>2.10.6</joda-time.version>
        <versions-maven-plugin.version>2.7</versions-maven-plugin.version>
        <java.faker.version>1.0.2</java.faker.version>
        <force-rest-api.version>0.0.40</force-rest-api.version>
        <slf4j-simple.version>1.7.25</slf4j-simple.version>
        <salesforce-service.version>2.0.6</salesforce-service.version>
        
        <encrypt.key>${env.SELENIUM_CRM_SIT_ENCRYPT_KEY}</encrypt.key>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <exclusions>
                
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.assertj</groupId>
                    <artifactId>assertj-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.twilio.sdk</groupId>
            <artifactId>twilio</artifactId>
            <version>8.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>xalan</groupId>
            <artifactId>xalan</artifactId>
            <version>2.7.2</version>
        </dependency>
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <version>1.0.b2</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
            <version>2.0.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-joda</artifactId>
            <version>${jackson-datatype-joda.version}</version>
        </dependency>
        <dependency>
            <groupId>com.frejo</groupId>
            <artifactId>force-rest-api</artifactId>
            <version>${force-rest-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>${java.faker.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-rsa</artifactId>
            <version>1.0.9.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>${joda-time.version}</version>
        </dependency>
                <dependency>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>selenium-java</artifactId>
                    <version>3.141.59</version>
                </dependency>
                <dependency>
                    <groupId>org.fluentlenium</groupId>
                    <artifactId>fluentlenium-spring-testng</artifactId>
                    <version>4.5.1</version>
                    <scope>test</scope>
                </dependency>
                <dependency>
                    <groupId>org.fluentlenium</groupId>
                    <artifactId>fluentlenium-assertj</artifactId>
                    <version>4.5.1</version>
                    <scope>test</scope>
                </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>com.nextgearcapital.crm</groupId>
            <artifactId>salesforce-service</artifactId>
            <version>${salesforce-service.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>2.0.24</version>
        </dependency>
        <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>8.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
            <version>3.1.8</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skipTests>false</skipTests>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/resources/testng-SmokeTests2.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    <systemPropertyVariables>
                        <testng.dtd.http>true</testng.dtd.http>
                    </systemPropertyVariables>
                    <trimStackTrace>false</trimStackTrace>
                    <properties>
                        <property>
                            <name>surefire.testng.verbose</name>
                            <value>10</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${versions-maven-plugin.version}</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <configuration>
                            <encoding>UTF-8</encoding>
                            <consoleOutput>true</consoleOutput>
                            <failsOnError>true</failsOnError>
                            <configLocation>checkstyle.xml</configLocation>
                            <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by whitejeffreyl** [comment]
Inside one of the tests

<img width="718" alt="Screen Shot 2022-04-25 at 10 36 11 AM" src="https://user-images.githubusercontent.com/4417751/165111554-18a83efc-c1b8-4fe8-9d52-eb45050c4943.png">

**Comment by whitejeffreyl** [comment]
The thing is, using fluentlenium-spring-testng 4.X works. 5.X doesn't.  It runs perfectly fine using the current names in 4.x. Given that my 4.x using Surefire, and successfully runs them, that not seem to be the problem. If you use Intellij, each test has "run" and "debug" options are there in both 4.x and 5.x. To run via the Intellij IDE the testng xml is not even a factor. I can run 4.x without a testng.xml. I will however change the names and test it.

**Comment by whitejeffreyl** [comment]
Changed the name to the convention you suggested and switched to 5.x and it failed to run. 

<img width="1260" alt="Screen Shot 2022-04-26 at 10 54 34 AM" src="https://user-images.githubusercontent.com/4417751/165329138-3db9fe62-8556-41ee-977e-d1e0b5654eb4.png">

![Uploading Screen Shot 2022-04-26 at 10.56.21 AM.png…]()

**Comment by whitejeffreyl** [comment]
Bottom line, all other things being equal, Changing versions on the three things should not cause the test NOT to run if they work under the earlier version. 

<img width="628" alt="Screen Shot 2022-04-26 at 10 59 15 AM" src="https://user-images.githubusercontent.com/4417751/165330227-dfe8e53e-29ea-49bd-9776-ca4c2718e6f2.png">

**Comment by whitejeffreyl** [comment]
This for instance, does not work:

<suite name="Smoke Test Suite" parallel="tests" skipfailedinvocationcounts="true" verbose="10" thread-count="9">
    <listeners>
        <listener class-name="com.nextgearcapital.TestController"/>
    </listeners>
    <test name="Queue Tests">
        <classes>
            <class name="com.nextgearcapital.tests.smoke.SFTestQueuesTests"/>
        </classes>
    </test>
</suite>

**Comment by abendt** [comment]
Using your pom:

```
$ mvn dependency:tree

[INFO] +- org.seleniumhq.selenium:selenium-java:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.141.59:compile
[INFO] |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.14.8:compile
[INFO] |  |  \- com.squareup.okio:okio:jar:1.14.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.1.3:compile
[INFO] |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:compile
[INFO] |  |  +- com.google.auto.service:auto-service:jar:1.0.1:compile
[INFO] |  |  |  \- com.google.auto:auto-common:jar:1.2:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-json:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v97:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v98:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v99:jar:4.1.3:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.141.59:compile
[INFO] |  \- org.seleniumhq.selenium:selenium-support:jar:3.141.59:compile
```

Note the mixed selenium artifact versions _3.141.59_ and _4.1.3_. This might lead to issues.

Apparently the spring boot parent pom contains a dependency management section to manage these versions.
Try to explicitely set the _selenium.version_ property in your properties block to align the version numbers.

**Comment by whitejeffreyl** [comment]
You are brilliant. I took out the Spring Boot Parent POM and the other Spring dependencies (as your framework already provides what I needed). It works now. Thanks very much for your help.
