### ISSUE TITLE
Provide examples for options, again

### ISSUE THREAD

**Issue by nickik** [FluentLenium/FluentLenium#157]
I have a problem with select. I have seen this old issue [1] but it does no longer work and I am unable to find a example that works for me. 

Function like 'withId' dont seem to exist anymore.

`<select id="borrower-rate-category" name="rateCategory" class="form-control">
      `<option value="0">`Standard`<option>
      `<option value="1">`Change`<option>
`<select>

How could I select a diffrent option?

Thanks for your help.

https://github.com/FluentLenium/FluentLenium/issues/1

Edit: Cant get html to format correctly

**Comment by nickik** [comment]
I have found a solution with CSS 

click("select[id='borrower-rate-category'] option[value='4']");

but I would still be intrested in the 'normal' way.

**Comment by NozomiIto** [comment]
I think `fillSelect("#borrower-rate-category").withValue("4")` is normal way.
You can see it at
https://github.com/FluentLenium/FluentLenium#fill
