### ISSUE TITLE
@SharedDriver doesn't work in play WithApplication

### ISSUE THREAD

**Issue by zbeckman** [FluentLenium/FluentLenium#160]
Apparently we can't use @SharedDriver to change the driver (to share an instance across tests) while writing tests in Play WithApplication. Very frustrating... there should be a way to do this, since the alternative (no state between tests) makes for some very limited testing.

**Comment by NozomiIto** [comment]
This code (not using Play Framewrk) works on my enviroment.

```Java
import org.fluentlenium.adapter.FluentTest;
import org.fluentlenium.adapter.util.SharedDriver;
import org.junit.Test;

@SharedDriver(type = SharedDriver.SharedType.PER_CLASS)
public class SampleTest extends FluentTest {
    
    @Test
    public void test1() {
        goTo("http://google.com");
    }
    
    @Test
    public void test2() {
        goTo("http://google.com");
    }   
}
```

I think:

- @SharedDriver annotation must be added to class
- @SharedDriver only works with JUnit or TestNG now. You use any other test framework?

**Comment by zbeckman** [comment]
Hm. Well, We're writing in Scala but the tests should be using the JUnit driver. I'm guessing something in the bridge between ScalaTest and JUnit isn't working.

This is my code:

```
@RunWith(classOf[JUnitRunner])
@SharedDriver(deleteCookies = false)
@SharedDriver(`type` = SharedDriver.SharedType.PER_CLASS)
class TestWebsiteAuthentication extends Specification {
	val loginURL = routes.Application.login().url
	val administrativePortalURL = routes.Application.index().url

	"Application" should {
		"login as an administrative user on the web site" in new WithBrowser with GPAuthenticationTestUtility {
			browser.goTo(loginURL)

			// WebDriver won't interact with hidden elements; use a litlte js to enable the hidden fields so we can instrument them:
			browser.executeScript("document.getElementsByName('ipAddress')[0].setAttribute('type', 'text');")
			browser.executeScript("document.getElementsByName('operatingSystem')[0].setAttribute('type', 'text');")
			browser.executeScript("document.getElementsByName('deviceType')[0].setAttribute('type', 'text');")

			browser.fill("#email").`with`(prerequisiteAccounts.head.userIdentity)
			browser.fill("#password").`with`(prerequisiteAccounts.head.password)
			browser.fill("#ipAddress").`with`(ipAddress)
			browser.fill("#operatingSystem").`with`(operatingSystem)
			browser.fill("#deviceType").`with`(deviceType)
			browser.submit("#submit")
			browser.await().atMost(5, TimeUnit.SECONDS).untilPage().isLoaded

			assert(browser.title().contains("Upload"))
		}
	}
}
```

The behavior I'm seeing is that the authentication appears to fail (it works in a real web browser), and the upload page (the one that I should be on after authentication) never loads. If I check the browser.title() just before the assert, it's still reporting the login page.

Prior to adding authentication support this worked fine. That is, we would login, there was no authentication logic so it would just go directly to the upload page (no real authentication). But as soon as we added authentication... no good. So I'm guessing that the browser state is not being preserved, so authentication fails...

**Comment by zbeckman** [comment]
I've done a handful more testing. Seems that the browser is unable to maintain state even across two subsequent calls (in the same test). For example:

```
	browser.fill("#email").`with`(prerequisiteAccounts.head.userIdentity)
	browser.fill("#password").`with`(prerequisiteAccounts.head.password)
	browser.submit("#submit")

	browser.await().atMost(5, TimeUnit.SECONDS).untilPage().isLoaded
	browser.getDriver.get(browser.getBaseUrl + administrativePortalURL)
	browser.await().atMost(5, TimeUnit.SECONDS).untilPage().isLoaded

	Logger.debug(browser.title())
	assert(browser.title().contains("Upload"))
```

This outputs the login page title (not the administrative page title), and the assert fails -- indicating that the browser was unable to authenticate.

**Comment by NozomiIto** [comment]
Sorry, I'm not familiar with ScalaTest..

According to [this code](https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/adapter/FluentTest.java), SharedDriver feature for JUnit is implemented with @Rule annotation, and according to [this page](http://stackoverflow.com/questions/27468846/how-to-use-junits-rule-annotation-with-scala-specs2-tests), @Rule annoation does not work with ScalaTest spec style.

**Comment by MathildeLemee** [comment]
It will not work because you use Play wrapper.

Just have a look at https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/adapter/FluentTest.java

You will see the code you need to make it work.

**Comment by zbeckman** [comment]
Thanks Mathilde. What I'm still struggling with is getting a FluentLenium test that successfully logs in on an authenticated web site (in Scala). I'm able to do most things successfully... but any attempt to write  test that authenticates fails. It seems to be state related, that is, the login attempt appears to fail (for instance, tried to write one that logs in on Google Mail... never succeeds). Any pointers would be wonderful – been scouring the net for a Scala FluentLenium example of logging in... :-/

**Comment by filipcynarski** [comment]
SharedDriver will work for PER_METHOD as well since 0.10.9 version. Please keep in mind that the value should correspond w/ surefire settings. If you are using multiple execution methods please use PER_METHOD
