### ISSUE TITLE
FluentWait with max retry Attempts 

### ISSUE THREAD

**Issue by apsharma** [FluentLenium/FluentLenium#1628]
Looking for suggestions, inputs or pointers on how to build an additional method or configuration for FluentWait that allows specifying `maxAttempts(int attempts)` ? I realize that I could put this inside a while loop and get the same result but just looking if there was better or alternate way.

I am interested to build something like 

```
 await().atMost(poll_duration.duration, TimeUnit.SECONDS)
                .pollingEvery(poll_interval.interval, TimeUnit.MILLISECONDS)
                .maxAttempts(5)
                .withMessage(" still displayed").
                until(webElement).not().displayed();
```

Is there value in adding such a capability to FluentWait ?

**Comment by filipcynarski** [comment]
I think it is the same like a poolingEvery, but with less controlled cycles. It combines the atMost value divided by polling factor. I think we don't need maxAttempts because it is indirectly implemented as I explained.
