### ISSUE TITLE
Mvn latest snapshot 0.10.4

### ISSUE THREAD

**Issue by j-walker23** [FluentLenium/FluentLenium#165]
Sorry, i am still a Java new kid, there is no bug or anything i just can't figure out how to get the latest code. I really want the coolness it looks like you have added, especially the @FindBys and the add fillSelect on FluentWebElement (issue #155).

I have been spinning my wheels learning how to install snapshots, in your pom i see `0.10.4-SNAPSHOT`. Should i be able to get that snapshot from Sonatype? If not is there any good way?

Thanks for any help, and huge thanks for putting in the time for this. Everyone loves it who i have introduced it too!

**Comment by johanrydstrom** [comment]
If you want a SNAPSHOT to depend on you (probably) have to build it yourself. And furthermore, If you want a build server to be able to use that SNAPSHOT it either has to build it and have it available in it's local Maven repository OR build it and upload it to your own artifact repository (like Artifactory/Nexus/...)

**Comment by j-walker23** [comment]
Awesome, thanks man. I appreciate the info! I just need more time, there is a never never never never ending amount of coolness to learn.
