### ISSUE TITLE
How to implement Fluentlenium into an already existing Java Selenium Project

### ISSUE THREAD

**Issue by MauGarL** [FluentLenium/FluentLenium#1687]
Due to Fluentlenium is an extension to Selenium rather than an alternative, how can an already existing Java Selenium Project that uses TestNg with Page Factory and BasePage class implement Fluentlenium?

**Comment by filipcynarski** [comment]
Hello @MauGarL please use related example from examples directory: https://github.com/FluentLenium/FluentLenium/tree/develop/examples it should work if you face any issues please let us know

Cheers
