### ISSUE TITLE
Looking for a new maintener

### ISSUE THREAD

**Issue by MathildeLemee** [FluentLenium/FluentLenium#172]
I'm too busy, is someone interested by joining the team and be able to do the release and merging the pull requests ?

**Comment by fat-troll** [comment]
Hey, I was using your framework back in 2014, until developed my own one. I just hope the project will move on in future and you will find a person, as even for that time it was pretty cool :)

**Comment by logineimer** [comment]
I'm interested.

**Comment by filipcynarski** [comment]
I'm interested as well. In my current company we relay on fluentlenium and have huge solution (~460 test cases) we've also extended FluentLenium for nice features (like concurrent execution on method level - it is not implemented in FluentLenium) and I'm also interested to be involved in this project personally.

**Comment by fat-troll** [comment]
If so, I'm also interested. Currently I'm working on another framework (based on Selenide), but I would be glad to help you here, as I know this framework's architecture already from my past.

**Comment by logineimer** [comment]
It's the same here as filipcynarski said.

**Comment by filipcynarski** [comment]
So what are we going to do?

**Comment by logineimer** [comment]
Well, at first @MathildeLemee has to answer. :)

**Comment by Toilal** [comment]
@MathildeLemee I'm interested too. I often work with FluentLenium to test webapps and can't find anything better to test webapp from using a JAVA API.

**Comment by MathildeLemee** [comment]
Great ! Just join the mailing list https://groups.google.com/forum/#!forum/fluentlenium and let's talk about that :)

**Comment by filipcynarski** [comment]
We've managed that already.
