### ISSUE TITLE
Events are not available for RemoteWebDriver (v4.8.0)

### ISSUE THREAD

**Issue by apsharma** [FluentLenium/FluentLenium#1724]
Events are triggered only when using a local webdriver. Events are not triggered when using the RemoteWebDriver.

This does not happen even after overriding the getEventsEnabled() to return True, always. As I said earlier, this is not a problem when running the tests against a local Chrome or Edge or Firefox driver.

In fact, the declared event throws an error saying "An EventFiringWebDriver instance is required to use events. You should set 'eventsEnabled' configuration property to 'true' or override newWebDriver() to build an EventFiringWebDriver."
e.g. - 
```
events().afterNavigateRefresh(webDriver -> {
            log.warn("Waiting for {} seconds after a page refresh", waitAfterRefresh);
            await().explicitlyFor(10, TimeUnit.SECONDS);
        });
```

**Comment by filipcynarski** [comment]
We will take a look at this issue after Selenium upgrade to the most recent version

**Comment by filipcynarski** [comment]
@apsharma please check now, with the newest version of Selenium we are also compatible. Closing this issue for now, feel free to reopen.
