### ISSUE TITLE
Unable to upload document, facing exceptions 

### ISSUE THREAD

**Issue by kamathvrinda18** [FluentLenium/FluentLenium#1742]
org.openqa.selenium.InvalidElementStateException: invalid element state 

The element is clickable, yet `element.click().fill().with(imagePath); ` it is not working

**Comment by apsharma** [comment]
I do something very similar in my tests i.e upload documents and it seems to work just fine, both with a local and remote driver/browser.
There aren't many details, in your question, to know exactly what might be going on. FWIW, this does not seem to be a Fluentlenium issue, for now. 

Have you tried adding an explicit check with an if block and checking the results ? For e.g.
```
if (element.clickable()) {
	element.click().fill().with(imagePath);
} 
```

It is not a solution to your problem but might help you uncover where the issue. 

From the snippet, it _seems_ that clicking on the `element` opens up another text or input field. It might be worth checking whether that input field itself is clickable/editable before `fill().with(imagePath)`.

**Comment by filipcynarski** [comment]
Sorry that's not what FL is doing differently than Selenium please find examples in the internet and reuse.
