### ISSUE TITLE
Fluentlenium cannot identify elements on page after a DOM change

### ISSUE THREAD

**Issue by apsharma** [FluentLenium/FluentLenium#1750]
I have a situation where a <span> node appears in the DOM after clicking a button. The node is not available unless the button is clicked. 

I am unable to discover the element using 
`el(By.cssSelector(".identifierClass"))`
but the element is instantiated using the selenium driver like this:
`getDriver().findElement(By.cssSelector(".identifierClass"))`

Any pointers or suggestions ?

**Comment by apsharma** [comment]
Also, is there a way to convert a `WebElement` to a `FluentWebElement` ? I know the reverse is possible.

**Comment by apsharma** [comment]
Leaving this comment here for further discussion/input from @filipcynarski  and others. (Also, in case, someone else runs into this situation)

I ended up doing something like this:
```
WebElement element = getDriver().findElement(By.cssSelector(".select2-dropdown"));
MyWebComponent fwe = new MyWebComponent(element, control, instantiator) // wanted to make this a separate component
fwe.keyboard.sendKeys(blah)
fwe.keyboard.sendKeys(Keys.Enter)
```

However, I did notice that `@ FindBy` would not work for elements defined within MyWebComponent. I have to explicitly instantiate them such
`FluentWebElement someElement = this.el(".identifierClass");`

Two questions:
- Any ideas why `@FindBy` won't/doesn't work inside MyWebComponent class ?
- Fluentlenium has a `getElement()` that returns the WebElement for a FluentWebElement. Should there be something that does the opposite i.e. `getFluentWebElement(WebElement element)` ?

**Comment by filipcynarski** [comment]
That's expected and known limitation when you are using FindBy the instantiation of FluentWebElement happens when you tries to use this reference for the first time. For dynamic pages you need to refer to the selector by using el, or $ within CSS selector. @apsharma
