### ISSUE TITLE
Create pure main branch from develop just after releasing 6.0.0

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#1755]
Merging back master to develop breaks current logic and fixes looks like it is outdated and is not reflecting the current state of the project.

We need to create a fresh main branch from develop after releasing 6.0.0

**Comment by apsharma** [comment]
@filipcynarski - do you feel that it will be pre-mature to pull in the develop branch and see how it works ? (it _seems_ that it might have fixes to issues around Selenium Grid v4)

**Comment by filipcynarski** [comment]
@apsharma we are always releasing from develop branch so no worries

**Comment by mkurz** [comment]
Any ETA for 6.0? Thanks!

**Comment by filipcynarski** [comment]
I’m planning to release the recent changes in the first week of May (possibly tomorrow)

**Comment by filipcynarski** [comment]
@mkurz Because of repackaging I needed to ask for a dedicated staging profile for FL, once this ticket is sorted I'll upload JARs to maven: https://issues.sonatype.org/browse/OSSRH-91252

Sorry for the delay

**Comment by mkurz** [comment]
@filipcynarski Thanks! Curious, did you add the txt record to the domain? I can't see anything currently using `dig -t txt fluentlenium.io`

**Comment by filipcynarski** [comment]
FL 6.0.0 released today morning @mkurz

**Comment by mkurz** [comment]
Thanks! I told scala-steward to help migration in the scala world: https://github.com/scala-steward-org/scala-steward/pull/3044
