### ISSUE TITLE
Drag and drop using FluentLenium

### ISSUE THREAD

**Issue by johdah** [FluentLenium/FluentLenium#176]
Is it possible to drag and drop using FluentLenium? Me and our Test Engineer hasn't been able to find any way to do that. We are looking for support for this:

http://docs.seleniumhq.org/docs/03_webdriver.jsp#drag-and-drop

**Comment by logineimer** [comment]
Currently, it's not supported.

**Comment by Toilal** [comment]
It may help : http://stackoverflow.com/questions/14210051/how-to-automate-drag-drop-functionality-using-selenium-web-driver

**Comment by filipcynarski** [comment]
We have to keep in mind that some features especially like moveToElement actions are not fully supported on mobile devices, but AFAIK FluentLenium is not written to support such sort of browsers. We can work on that and think how to deal w/ that soon.

**Comment by johdah** [comment]
@filipcynarski isn't drag and drop currently supported in the underlying Selenium API? Or is FluentLenium a new implementation of Selenium? We really pretty heavily on drag and drop for some features so it's kind of a big problem for us.
