### ISSUE TITLE
0.10.4.

### ISSUE THREAD

**Issue by totovelo10** [FluentLenium/FluentLenium#178]
hello @sebglon @MathildeLemee 

have you got a date for the  0.10.4  release ?

**Comment by filipcynarski** [comment]
I've created 0.10.4 there is no due date, I'll work on new features and bug fixes, I think the realistic date is next month or two, we need to work to gather all people in place, as you can see new contributors where added to the team, and it is going to be first release led by new people. Please give us time to work on processes and new features. I can promise you that the FluentLenium project will start live again ;)

**Comment by totovelo10** [comment]
thank you @filipcynarski
