### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#179]
As you know, java 8 brings great features like lambdas and streams API. I'm currently working with FluentLenium in a Java 8 project.

I have two ideas to make FluentLenium more java 8 compliant ...

1) **The easy one**: Avoid all ambiguities in functionnal interface parameters.

``` java
FluentWebElement myElement = ...;
await().until((until) -> myElement.isEnabled());
// Great ! Java 8, lambdas ! It's really readable ! :)
```

Cool stuff ! But actually it doesn't compile :(.

Because await() object has ambiguous methods for using lambdas.
- **<T> T until(Function<? super F, T> isTrue)**
- **until(Predicate<Fluent> isTrue)** {

So currently, it requires a cast to clarify the ambiguity.

``` java
FluentWebElement myElement = ...;
await().until((com.google.common.base.Predicate<Fluent>)(until) -> myElement.isEnabled());
// So sad ... :(
```

=> _Solution_: rename until(Predicate) by untilTrue(Predicate) or something like that ...

2) **The hard one**: Most of Guava APIs are useless when working with java 8.

Because it duplicates what's inside JDK java `java.util.function` package.

=> _Solution_: extract guava related features in a distinct `fluentlenium-guava` module ...
- `fluentlenium-core`, containing everything common ...
- `fluentlenium-guava` for JDK<8 users.
- `fluentlenium-java8` for JDK>=8 users.

It's probably a lot of work, with many factories to introduce, but it would be great to achieve this ...

**Comment by Toilal** [comment]
What about switching the whole project to java8, and use [RetroLambda](https://github.com/orfjackal/retrolambda) to support previous JVM versions ?

**Comment by Toilal** [comment]
There will be not support for java < 8 for FluentLenium >= 2

**Comment by filipcynarski** [comment]
@Toilal I think we do not need to support Java 7. Neither create fluentlenium-guava module all classes compiled w/ Java 8 won't work on earlier versions. So it will simplify 2nd task. It is a result of dropping Java 7 by Selenium 3.

**Comment by filipcynarski** [comment]
* Guava removed from FluentLenium code

**Comment by filipcynarski** [comment]
* Until predicate is not required to be renamed I've just added a test for lambdas in await within until.

Please take a look on review, it can be merged.

**Comment by Toilal** [comment]
It's already been renamed, there's an untilPredicate() method.

**Comment by filipcynarski** [comment]
ok, that's what I've found. I'll push test to git soon.

**Comment by filipcynarski** [comment]
Good, I see test is not required for it. So only guava replacement left to close this task in my opinion. What do you think?

**Comment by Toilal** [comment]
Yes, I think so. But it's a mass refactoring, we could wait 3.1.0 ?

**Comment by Toilal** [comment]
And maybe close this one and create another one ?

**Comment by filipcynarski** [comment]
I think it is not massive refactoring just removing guava optional and use java util one. We agreed that we don't need a module for java 7 so it is pretty small. Are you expecting to change anything more?

**Comment by Toilal** [comment]
There's not only Optional, but also features like Collections2 that can be replaced with stream API, and Predicate, Function ... It's used widely in the codebase.

**Comment by filipcynarski** [comment]
* com.google.common.base.Predicate should be also replaced
* we should remove all functional classes, like Supplier, Function, Predicate, by the Java8 equivalent

**Comment by Toilal** [comment]
Thanks @filipcynarski for working on this !
