### ISSUE TITLE
Wait parameters for FluentWebElement/FluentList actions

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#180]
I'm working with AngularJS, and it naturaly cause some headaches with Selenium because of the quite instable DOM when the view/model is loading.

In this environment, actions available on FluentWebElement objects (like click()) often fails because the element is still not enabled ...

Currently i need do things like this ...
```
FluentWebElement element = ...;
await().atMost(2000L).until((until) -> element.isEnabled());
element.click();
```

It's not really natural, and not easy to read ...

It would be great to be able to wait automatically for element to become clickable.

**use case 1**: For a specific action.
```
FluentWebElement element = ...;
element.click(2000L); // until element.isEnabled() is automatic by default because it make sense for a click ...
element.click(2000L, (until) -> element.getText().contains("Click here"));
```

**use case 2**: For a specific element.
```
FluentWebElement element = ...;
element.actionWait(2000L).click();
//FluentWebElement is now configured for this wait time ...
element.click((until) -> element.getText().contains("Click here")); // custom wait until condition can be given for each call ...
```

**use case 3**: For all elements.
```
setDefaultActionWait(2000L); // Configure default action wait time globaly.
...
FluentWebElement element = ...;
element.click(); // automatically wait for at most 2000L for the element to become "clickable".
element.click((until) -> element.getText().contains("Click here")); // With a custom condition ...
```

Same principles could be applied to FluentList, to ensure that all elements are enabled before trying to click on them. Today, elements are skipped and it can be even worse than just raising an exception.

**Comment by MathildeLemee** [comment]
That's something I handle with  :

public class LoginPage extends FluentPage {
   @AjaxElement
   FluentWebElement myAjaxElement;
}
You can set the timeout in seconds for the page to throw an error if not found with @AjaxElement(timeountOnSeconds=3) if you want to wait 3 seconds. By default, the timeout is set to one second.
And for all elements, you have : 
withDefaultSearchWait(long l, TimeUnit timeUnit);
withDefaultPageWait(long l, TimeUnit timeUnit);

**Comment by Toilal** [comment]
It doesn't work in many use case with those included waits. Those waits wait for the element to be visible, but the click will fail if element is not enabled. 

In fact, it's not possible to customize the exit predicate in those wait ... I my case, I need a custom wait implementation with a predicate that checks the button is enabled so it can be clicked.

 Currently, it requires to use await().until(...) but it's quite verbose and it requires an additional statement.

**Comment by Toilal** [comment]
Or maybe we could create an annotation @WaitClickable ?

```
@AjaxElement
@WaitClickable
FluentWebElement myAjaxElement;
```

**Comment by Toilal** [comment]
In fact, withDefaultSearchWait configure implicit wait on WebDriver, but @AjaxElement use an explicit wait.

**Comment by Toilal** [comment]
It's now here with hooks (and a default @Wait hook)
