### ISSUE TITLE
helper methods to work with tab

### ISSUE THREAD

**Issue by YannMoisan** [FluentLenium/FluentLenium#181]
There are no method to ease testing with multiple tabs. 

What do you think about adding them ?

Here is a sample to illustrate the idea :

    def goToInNewTab(f: Fluent, url: String): Fluent = {
        f.executeScript(s"window.open('${url}', '_blank');")
        val tabs = f.getDriver.getWindowHandles()
        f.getDriver.switchTo().window(tabs.toList(1))
        return f
    }

**Comment by filipcynarski** [comment]
Your pull request has been commented if you will be able to sort this stuff out we are manage to add this new feature.
