### ISSUE TITLE
Update Selenium 2.48.2

### ISSUE THREAD

**Issue by logineimer** [FluentLenium/FluentLenium#188]
Currently, FluentLenium uses Selenium 2.45.0. Latest version is 2.48.2 so we should update it.
As filip said, updating includes a testing session.

**Comment by filipcynarski** [comment]
It is not doable now because there is a bug since 2.46.0 which I've reported

https://github.com/SeleniumHQ/selenium/issues/1189

As a result our selenium tests are not passing. I'd suggest to wait for Selenium guys to fix that issue.

**Comment by filipcynarski** [comment]
It is done :)
