### ISSUE TITLE
SharedDriver with SharedType.ONCE is not destroyed on shutdown

### ISSUE THREAD

**Issue by kutzi** [FluentLenium/FluentLenium#196]
When I create a .@SharedDriver with SharedType.ONCE - i.e. the default - it is not destroyed on shutdown.
This is because of a bug in the shutdown hook. The shutdown hook tries to find a thread local driver, which is obviously empty since the hook  runs in a different thread than the tests.
It should instead close the driver stored in the sharedDriver field.

**Comment by Toilal** [comment]
In fact, we never call close() method on WebDriver. Maybe we should ?

**Comment by Woodham** [comment]
I'm pretty sure this bug still exists because the class `SharedDriverOnceShutdownHook` calls `FluentTestRunnerAdapter.releaseSharedDriver();` which only closes the driver if `isSharedDriverPerClass` is true.

(See https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/adapter/FluentTestRunnerAdapter.java#L185 )

**Comment by kutzi** [comment]
I just retried this with FluentLenium 0.13.11 and can confirm that this is **not** fixed, yet.
When I run my testsuite with SharedType.ONCE, the browser is not closed afterwards - potentially leading to builds on CI (Jenkins) to *hang* forever

**Comment by filipcynarski** [comment]
@kutzi we can take a look on that, or maybe would you like to provide us an example or try to fix the issue on separate branch?

**Comment by kutzi** [comment]
I can try either of these, but cannot give any promise until when I might be able to work on that.

**Comment by kutzi** [comment]
What about @Woodham's comment? Did you look at that?

**Comment by filipcynarski** [comment]
@Woodham  Looks reasonable however we need to write unit tests to examine this piece of logic. To avoid such issues next time. So the part of this task is more about writing unit tests which can identify the issue -> fix the issue -> expect the tests are green :)

**Comment by kutzi** [comment]
FYI: I've fixed this on my fork https://github.com/eSailors/FluentLenium/tree/SharedType_ONCE_not_closed
but haven't added any tests, because I don't know how to write such one.

One interesting thing to mention is, that you need to cleanup the sharedDriver, too, if you change the shafred policy in the middle of a test suite. Cf.
https://github.com/eSailors/FluentLenium/commit/619f64d821f17b8ccbaf9996b035d9af9c7bb261

**Comment by kutzi** [comment]
You might want to fix it differently, I just fixed it in a minimal way - just to 'scratch my own itch'

Specifically, I would try to refactor it and find e.g. a different solution for the isSharedDriverPerClass flag

**Comment by kutzi** [comment]
BTW: could you please reopen this issue to make it visible, that it's not fixed, yet?

**Comment by filipcynarski** [comment]
Before merging it to the master I'd like to have unit tests to be able to reproduce this issue. After the issue is reproduced in the code we can try to fix it.
