### ISSUE TITLE
Simultaneous run w/o thread locals

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#206]
Try to simplify the logic to rid the most of thread locals out and make code easier to maintain.

**Comment by Toilal** [comment]
I've also created this issue https://github.com/FluentLenium/FluentLenium/issues/204, but finally closed it because i'm not sure it's possible ... But If you have any idea to make it cleaner, let's go for it :)

**Comment by Toilal** [comment]
I think it's not really do-able while keeping parralel test runs.
