### ISSUE TITLE
Use a dependency injection framework (Guice)

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#213]
It would be better to use a dependency injection framework for @Page and WebElement injection, like [Guice](https://github.com/google/guice).

**Comment by Toilal** [comment]
[governator](https://github.com/Netflix/governator) seems great.

**Comment by filipcynarski** [comment]
@Toilal could you please elaborate why do we need this change? It is a little bit cloudy to me.

**Comment by Toilal** [comment]
Code related to [@Page injection](https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/core/page/PageInitializer.java) is a bit complex, and could be replaced with some dependency injection framework.

**Comment by Toilal** [comment]
Finally, I don't think we need this.
