### ISSUE TITLE
Timeline of next release?

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [FluentLenium/FluentLenium#217]
Hi, we were about to open a duplicate issue (#155), but saw that it has been completed and merged in. Do we know when the next minor release will be so that we can upgrade and use this functionality?

Is there anything we can do to help you out with the release process?

Thanks!
Mark & Mike

**Comment by MichaelKunze** [comment]
IMHO it was stated that the next release is 1.0

Things to be implemented:
https://github.com/FluentLenium/FluentLenium/milestones

Michael

**Comment by filipcynarski** [comment]
I think we can manage that this week. Let me clarify what else we need to
perform minor release.

2016-03-21 15:08 GMT+01:00 Mark McDonald <notifications@github.com>:

**Comment by Toilal** [comment]
I think we need to release 0.11.0 for now, because there's still things to be done before 1.0.

**Comment by filipcynarski** [comment]
@MarkyMarkMcDonald release for 0.11.0 is completed
