### ISSUE TITLE
is moveToElement supported?

### ISSUE THREAD

**Issue by henray** [FluentLenium/FluentLenium#218]
Does FluentLenium currently support the Selenium "`Action#moveToElement(WebElement)`" functionality? From what I've gathered this is not currently supported. Apologies if I am wrong.

Is it possible to include this into the next release? Or can I submit a PR for this feature?

Currently I am working around the problem by simply doing:

` public void hoverMouseOver(FluentWebElement fwe) {`
`WebElement toElement = getDriver().findElement(By.id(fwe.getId()));`
`Actions a = new Actions(getDriver());`
`a.moveToElement(toElement).build().perform();`
`} `

However this seems like a good feature to have in FluentLenium

**Comment by Toilal** [comment]
No problem for pull request, but please return `this` for fluent api not to be broken. and function  name could be `mouseover(...)` only.

**Comment by henray** [comment]
The implementation shown above won't work in all cases. Not sure how to implement it because not every element has an id. :(

**Comment by Toilal** [comment]
@henray fwe.getElement() instead of the whoule By.id thing should work, even if no id is defined on the element.

**Comment by henray** [comment]
@Toilal Initially I tried to use 

`public void hoverMouseOver(FluentWebElement fwe) {`
`Actions a = new Actions(getDriver());`
`a.moveToElement(fwe.getElement()).build().perform();`
`}`

however I kept getting an exception: "ClassCastException: Cannot be cast into a (Locatable) element".
I was locating my FluentWebElements in my page by doing

`@FindBy(id = "hello")`
`FluentWebElement helloElement`

and calling the createPage function.

**Comment by Toilal** [comment]
I close this issue in favor of https://github.com/FluentLenium/FluentLenium/issues/211 which is more broad and related to Selenium Actions API integration.

**Comment by filipcynarski** [comment]
@henray your issue was resolved today. Changes are present in the master branch.

**Comment by henray** [comment]
Amazing, thank you guys @filipcynarski  @Toilal  ! Hope I can replace my own hacky implementation with yours soon :)

**Comment by Toilal** [comment]
There'll be a release very soon. There's still this issue open #211, so stay tuned for other actions implementations :)
