### ISSUE TITLE
Add PageComponent object into code base

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#219]
Add PageComponent object into code base which makes building the Page Class from reusable components.

**Comment by filipcynarski** [comment]
I'm still thinking is it make sense, now we are able to nest pages in page I'm not sure is it good what about new annotation called PageComponent to build Page using Components.

For example: I have main page and it can consist of: menu component, login component, products list component and so forth.

**Comment by Toilal** [comment]
or even better and really easy to implement :
```
Select component = find("#some-select").as(Select.class);
```

That beeing said, it should also work with @FindBy annotations, but I don't use them that much.

Does it work today to perform this ?

```
@FindBy(...)
Select select;
```

**Comment by Toilal** [comment]
I've just discovered something from the docs :+1: 

> Not only FluentWebElement fields are populated. Every type with a constructor taking a WebElement is a candidate. This makes it possible for the page to expose fields with functional methods and not (only) the 'technical' methods that FluentWebElement exposes.

So pattern is almost already there. It should just work with FindBy annotations, and we need to add as(Component.class) method in FluentWebElement class to easy convert any element to a component class.

**Comment by Toilal** [comment]
There's still a problem, because a FluentWebElement can't easily the WebDriver and some features like await(), but I think it could be discussed and fixed in another issue.

**Comment by Toilal** [comment]
Open another issue if actual code is not good enough.
