### ISSUE TITLE
Configuration Features

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#220]
There is a lack of generic configuration class it would be great to deliver something like that in the code base.

**Comment by MichaelKunze** [comment]
Could you elaborate what you have in mind?

**Comment by Toilal** [comment]
:+1: Example of what you dream of :)

**Comment by filipcynarski** [comment]
The idea is to expose common solution to configure stuff like:

browser, driver paths, proxy and so forth using properties file and a config class.

**Comment by Toilal** [comment]
Here how I currently handle parameters in my project : https://gist.github.com/Toilal/7bc23b9e53fd4365975b5a8426504be6

Then I use this class in my own test. getDefaultDriver() is overriden to use driver defined by this class. Configuration is made using environment variable or JVM properties.
