### ISSUE TITLE
Introduce @PageComponent annotation for Component

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#229]
Introduce @PageComponent annotation for Component feature

[Related code change](https://github.com/FluentLenium/FluentLenium/pull/228)

**Comment by Toilal** [comment]
I'm not sure we should implement this one before #213.

**Comment by Toilal** [comment]
As a component requires a parent WebElement to be constructed, i'm not sure it's possible to make this feature available through an annotation.

**Comment by Toilal** [comment]
Instead of a new annotation, we could use existing @FindBy.

```java
@FindBy(css = ".some-component")
private SomeComponent component;
```

And it should just work if SomeComponent class has a single argument WebElement.class constructor

```java
public class SomeComponent extends FluentWebElement {

    public SomeComponent(WebElement element) {
        super(element);
    }
    ....
}
```

**Comment by filipcynarski** [comment]
It is a great idea :)
