### ISSUE TITLE
Component issue

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#230]
I've just discovered something from the docs :+1:

> Not only FluentWebElement fields are populated. Every type with a constructor taking a WebElement is a candidate. This makes it possible for the page to expose fields with functional methods and not (only) the 'technical' methods that FluentWebElement exposes.

So pattern is almost already there. It should just work with FindBy annotations, and we need to add as(Component.class) method in FluentWebElement class to easy convert any element to a component class.

> There's still a problem, because a FluentWebElement can't easily access the WebDriver and some features like await(), but I think it could be discussed and fixed in another issue.

**Comment by Toilal** [comment]
Feature doesn't work ?

**Comment by filipcynarski** [comment]
No, I've created this issue from your comments @Toilal

**Comment by Toilal** [comment]
I've make more tests to ensure FindBy works properly with components.

For the last point, it's possible to retrieve the FluentTest instance with FluentThread.get(), so I close this one.

When #205 will be implemented, maybe we would avoid the usage of FluentThread ...
