### ISSUE TITLE
Get an Optional from FluentWebElement and FluentList

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#247]
We are going to introduce new find selector called `findOptionalElement` it will return Google's guava `Optional<FluentWebElement>` object.

**Comment by Toilal** [comment]
Good idea. I would vote for `optional()` and `optionalFirst` though. (Replacing `find` with `optional` from existing method names.

**Comment by Toilal** [comment]
With current state of project, with everything beeing lazy wrappers on WebElement, I'm not sure it still make sense.

**Comment by filipcynarski** [comment]
I think it still does. Imagine that you want to create a code which checks is item present or not and do not want to wrap everything in try catch. Is there any option to achieve that in new state of project?

**Comment by Toilal** [comment]
Now, when you call `$(".selector")`, it creates a lazy element (WebElement is proxyfied), and `findElements` is not invoked right now.

There's new functions on the FluentWebElement and FluentList (see [FluentProxyState](https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/core/proxy/FluentProxyState.java)), and one of those is `isPresent()` which returns a boolean.

So you only have to write `find(".selector").isPresent()`, and that's it, no try/catch is required anymore.

`now()` function is there to initialize the lazy element and perform the underlying search, it would then throw the `NoSuchElementException`.

**Comment by Toilal** [comment]
But, maybe FluentWebElement could implement the Optional interface, it's just an idea :)

**Comment by Toilal** [comment]
I have a better idea. We can add a optional() function in FluentWebElement and FluentList.

```java
find(".selected").optional().orElseThrow(() -> new SomeException(...));
```

When calling optional(), we should create an only if ```FluentWebElement#isPresent()``` returns true. 

```java
class FluentWebElement<T> {
...
public Optional<FluentWebElement> optional() {
    if (this.isPresent()) {
        return Optional.of(this);
    } else {
        return Optional.ofNullable(null);
    }
}
...
```

**Comment by filipcynarski** [comment]
Good, so I can use optional methods as well, not only check if exists or throw an exception?

**Comment by Toilal** [comment]
Yes of course, it will be a normal Optional object, build from the FluentWebElement if it's present in the DOM, and from null if FluentWebElement is not present.
