### ISSUE TITLE
waitAndClick method for fluent web element

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#249]
I think it makes sense to implement solution which makes things simpler to everyone, so I'm suggesting to extend FluentWebElement actions to waitAndClick method.

**Comment by Toilal** [comment]
With latest changes, it's possible to do something like this
```java
FluentWebElement element;

await().until(element).isClickable();
element.click();
```

If would be great to have an API in FluentWebElement class to access this in a more fluent style. I think of something like this :

```java
FluentWebElement element;

// Same api as existing await(), but until() is called with
// no parameter because we already have the element in context.
element.await().until().isClickable().click();

// And some shortcuts handling most actions.
element.awaitFor().click();
```

But maybe this could simply be included in `element.click()`, and a new method `element.clickNow()` to avoid the automated waiting ?

**Comment by henray** [comment]
@Toilal  I think what you just suggested is a really good idea. As a user I would really like that feature.

**Comment by Toilal** [comment]
@henray > The clickNow() or the awaitFor().click() ?

**Comment by Toilal** [comment]
Actually, in my project I have this code

```java
this.events().beforeClickOn((element, driver_) -> this.await().until(element).isClickable());
```

This wait before each click for the clicked element to be clickable.

**Comment by henray** [comment]
The last suggestion

> But maybe this could simply be included in element.click(), and a new method element.clickNow() to avoid the automated waiting ?

**Comment by Toilal** [comment]
If you work on angularJS, I also have ported a waitForAngular() function waiting for the angular digest to be stable (it's ported from Protractor).

It works really well. For the story, I don't want to use protractor to keep the testing framework agnostic from underlying javascript framework.

**Comment by henray** [comment]
@Toilal Possibility of creating an irc for the FluentLenium project? I would like to get more involved

**Comment by slawekradzyminski** [comment]
We have it implemented this way in our internal framework:

```
void waitAndClick(By locator) {
await().until(locator).isClickable();
FluentWebElement element = findElement(locator);
page().scrollToElement(element);
element.click();}
```

That's probably what Filip meant here :)

**Comment by Toilal** [comment]
I also added the scrollToElement as a event beforeClick :)

I think those tips should really be included as default behavior in FluentLenium. It's really the main things that makes using raw Selenium a nightmare, and FluentLenium should take care of this without the user to even know it.

Calling `click()` should really make everything possible to perform the click.

Currently it's hacky, but i've implemented this behaviour globaly using events().

```
        this.events().beforeClickOn((element, driver_) -> fluent
                .executeScript("arguments[0].scrollIntoView();", element.getElement()));
        // S'assure que l'élément soit affiché et actif avant de cliquer.
        this.events().beforeClickOn((element, driver_) -> this.await()
                .until(element).isClickable());
```

If we introduce this behavior as default, we should still have a way to call "raw" click of Selenium. With events, even when calling the raw click, it will call events.

**Comment by marcincharezinski** [comment]
+1 for click() idea here

**Comment by Toilal** [comment]
Use @Wait hook for this issue.
