### ISSUE TITLE
Refactor abstract class constructors to protected

### ISSUE THREAD

**Issue by henray** [FluentLenium/FluentLenium#251]
I know this isn't important for functionality, but from a design perspective, would it be better to make the constructor for Fluent and FluentPage **protected** instead of **public**?
Since you can't instantiate abstract classes anyways, then there's no real reason why they should be public?
I apologize if I'm out of line, I'm really just trying to learn (I hope I don't upset anyone with my post)

**Comment by Toilal** [comment]
http://stackoverflow.com/questions/2742408/relevance-of-public-constructor-in-abstract-class/2742446#2742446

But that's the first time I realize this point in Java :)
