### ISSUE TITLE
Add await().until(ajaxIsCompleted)

### ISSUE THREAD

**Issue by slawekradzyminski** [FluentLenium/FluentLenium#253]
Waiting for completed ajaxCall is extremely useful in writing E2E tests. I propose to add it in FluentLenium. I see three ways:

- await().untilPredicate(ajaxCallIsCompleted)

```java
private Predicate<Fluent> ajaxCallIsCompleted = new Predicate<Fluent>() {
        @Override
        public boolean apply(Fluent fluent) {
            return (Boolean) ((JavascriptExecutor) getDriver()).executeScript("return (window.jQuery != null) && (jQuery.active === 0);");
        }
    };
```

- await().untilExpectedCondition(ajaxCallIsCompleted) - assuming Issue #216 will be done before

```java
private Boolean apply(Fluent fluent) {
        JavascriptExecutor js = (JavascriptExecutor) fluent.getDriver();
        return (Boolean) js.executeScript("return (window.jQuery != null) && (jQuery.active === 0);");
    }
```

- await().untilJavaScriptDone(String script)

**Comment by Toilal** [comment]
2 first point is JQuery specific, but last point could be implemented.

It's a good idea, and I actually have this kind of stuff in my own project, but using angular.

**Comment by Toilal** [comment]
```FluentTest#executeScript()``` or ```FluentTest#executeAsyncScript()``` are blocking functions. So finally, we don't need to wait for anything here ...

Please reopen and clarify if you still need something.
