### ISSUE TITLE
assertions using hasText subject to UnknownFormatConversionException

### ISSUE THREAD

**Issue by Pivotal-Beacon** [FluentLenium/FluentLenium#254]
We wrote a test using FluentLenium and the AssertJ helpers with something like the following:

```java
assertThat(findFirst("body")).hasText("There is a 5% increase")
```

And get the following error:

```
java.util.UnknownFormatConversionException: Conversion = 'M'

	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:112)
	at org.fluentlenium.assertj.custom.FluentWebElementAssert.hasText(FluentWebElementAssert.java:113)
```

This is because `org.assertj.core.api.AbstractAssert.failWithMessage` uses `String.format` and FluentLenium is passing strings with `%` into AssertJ. The bug seems to have been introduced in #20

**Comment by filipcynarski** [comment]
Thank you for reporting this issue. We will try to address it next release.

**Comment by filipcynarski** [comment]
It is working well on 0.13.1 release. Could you please re-check? I've added Unit test for this issue.

**Comment by filipcynarski** [comment]
It is passing on 0.13.1 release, could you please recheck on newest version?

Here is a commit where I've added unit test for this issue: https://github.com/FluentLenium/FluentLenium/commit/55d29f86f7a090005b58ca7568f43ede3d5cff85

Please let me know about your findings

**Comment by filipcynarski** [comment]
@Pivotal-Beacon could you please take a look and check is it still a case for you?

**Comment by Pivotal-Beacon** [comment]
It looks like the Exception is only thrown when the Assertion fails.
(Here's a branch)[https://github.com/Pivotal-Beacon/FluentLenium/tree/string-formatting-failure-examples] changing your unit tests to failures in one commit, then fixing them in the next.

It looks like the root issue is concatenating  the error message given to the parent class inside our code (see (here)[https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-assertj/src/main/java/org/fluentlenium/assertj/custom/FluentWebElementAssert.java#L113] and (here)[https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractAssert.java#L116]), instead of calling super in a String.format style.

**Comment by Pivotal-Beacon** [comment]
I can take a shot at a pull request when I have more bandwidth later tonight if you'd like.

Do you think I should include unit tests similar to the ones I've created on the branch, or say we're not following the contract AssertJ's abstract class expect and make the changes without those tests?

**Comment by filipcynarski** [comment]
@Pivotal-Beacon thank you for examples, please include tests as well and create pull request, so I'd be able to merge it ASAP.
