### ISSUE TITLE
Add methods to operate on Windows

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#261]
It would be great to have such methods implemented to help users to operate on Windows:

* clickAndOpenNew
* openNewAndSwitch
* clickAndCloseCurrent
* close
* switchToParentFrame
* switchToLast
* switchTo
* waitForNewWindowToOpen

During this task implementation it is also important to work on unit tests for new functionalities and awaits on Window matchers.

**Comment by Toilal** [comment]
please introduce windows() as a container for all those methods.

```this.windows().clickAndOpenNew()``` ...

**Comment by filipcynarski** [comment]
Code changes merged to master branch.
