### ISSUE TITLE
Nondeterministic behaviour of isClickable method

### ISSUE THREAD

**Issue by GitHub098123** [FluentLenium/FluentLenium#263]
isClickable method from AbstractWaitElementMatcher class behaves randomly for selectors. 

Await like: `await().until(locator).isClickable();` may pass but it's (sometimes) impossible to click in element under the locator after that wait. 

Solution for that is passing FluentWebElement (which wasn't possible in earlier versions of FluentLenium). 

Situation take place mainly on mobile emulator in webdriver.

This await is used in method waitAndClick. We can pass only locators there, so it's also behaves randomly.

**Comment by filipcynarski** [comment]
I cannot do anything w/ that.

```
    public void isClickable() {
        Predicate<Fluent> isClickable = new com.google.common.base.Predicate<Fluent>() {

            @Override
            public boolean apply(Fluent input) {
                for (FluentWebElement element : find()) {
                    if (ExpectedConditions.elementToBeClickable(element.getElement()).apply(input.getDriver())
                            == null) {
                        return false;
                    }
                }
                return true;
            }
        };

        until(wait, isClickable, isClickableMessage(selectionName));
    }
```
It is just wrapping the Selenium isClickable condition please use isEnabled instead.

We can consider to add isEnabled in conjunction with isClickable however the code of Selenium is checking that but it is not working well.

**Comment by Toilal** [comment]
I'll prefer to stick with selenium natural behavior and keep as much consistency of FluentLenium with Selenium. Users can find many information about Selenium behavior, so FluentLenium should stick to Selenium behavior.

From my point of view, there's no issue in FluentLenium here.

**Comment by filipcynarski** [comment]
I think we should leave this one as it is. So it is not an issue.

**Comment by Toilal** [comment]
@GitHub098123 Maybe you could report your issue at Selenium issue tracker.
