### ISSUE TITLE
AssertJ - add new assertions for Optionals

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#264]
I'd like to be able to make an assertion on Optionals using assertThat.

**Comment by Toilal** [comment]
Maybe you could contribute on assertJ project ?

**Comment by Toilal** [comment]
In fact, there's a assert-guava that match this need. => https://github.com/joel-costigliola/assertj-guava/blob/master/src/main/java/org/assertj/guava/api/Assertions.java

Reopen if you need something else.
