### ISSUE TITLE
Testng run groups

### ISSUE THREAD

**Issue by AlmogH** [FluentLenium/FluentLenium#267]
Hi,
I have a project with testng and fluentlenium at version 0.13.0

I'm trying to run my tests by groups, I looked at the class FluentTestNg,  I think that you need to add to the annotations alwaysRun=true.

I also want to thank you of all the work you are doing, fluentlenium helps us a lot and its amazing!

**Comment by Toilal** [comment]
Hi ! thanks for your support.

Could you explain what this annotations does, and why you  need it as default in FluentLenium for testNG ? (I'm not a testNG user, sorry)

**Comment by Toilal** [comment]
Could you open a pull request ? this attribute should be added on ```@BeforeTest/@AfterTest/@BeforeMethod/@AfterMethod/@AfterClass``` of FluentTestNg ?

**Comment by AlmogH** [comment]
sorry for responding late, its my first time trying doing a pull request i hope i did it right :sweat_smile:
