### ISSUE TITLE
Create fluentlenium-junit module

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#274]
fluentlenium-core should not include JUnit dependency, because it pulls this dependency for testNG users.

**Comment by Toilal** [comment]
Was reverted by cb8065f7443bc911da6896f50e57d8041505d790 because of code coverage issues.

**Comment by Toilal** [comment]
Should be possible to have right code coverage by keeping integration tests in the junit module, while having unit tests in fluentlenium-core.

**Comment by filipcynarski** [comment]
I think all modules have to be reorganized. To be able to run each of one in separation now it is not a case for *fluentlenium-it* for example.

**Comment by Toilal** [comment]
True, I'll commit those changes to drop this fluentlenium-it module and move those test inside respective modules (junit / testng)
