### ISSUE TITLE
JUnit 5 adapter

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#276]
Would be great to have a JUnit 5 adapter, using `@ExtendWith(FluentJUnit5.class)`.

See http://www.codeaffine.com/2016/02/18/junit-5-first-look/

**Comment by tmurakam** [comment]
I'm working on this. I'll send PR later.

**Comment by tmurakam** [comment]
I send PR #555.

**Comment by filipcynarski** [comment]
@tmurakam I was reviewing your PR but my concern is you are using junit vintage module so this change is basing on backward compatibility for JUnit4 I would like to provide users fully integrated module w/o any hack, now it looks like a hack for me and what I'm trying to do is to design separate fluentlenium module for JUnit5 based on JUnit5 architecture. So I cannot fully merge your PR.

**Comment by bobtiernay-okta** [comment]
Looking forward to this!

**Comment by filipcynarski** [comment]
It is junit5 module not adapter! Merged to develop, ready for testing!

**Comment by KingBuzzer** [comment]
Maybe you should change the name to fluentlenium-junit-jupiter instead, as per [this](https://github.com/mockito/mockito/issues/445#issuecomment-269083308) advice from a junit lead on the mockito sub module for JUnit5 support.
