### ISSUE TITLE
How can I replace 'linkText' or 'partialLinkText' in SE 2.0 using Fluentlenium?

### ISSUE THREAD

**Issue by rguimaraesr** [FluentLenium/FluentLenium#280]
Hi, How can I replace 'linkText' or 'partialLinkText' in SE 2.0 using Fluentlenium?

**Comment by Toilal** [comment]
What do you mean about replacing ?

Le 28 juil. 2016 10:00 PM, "rguimaraesr" <notifications@github.com> a
écrit :

**Comment by rguimaraesr** [comment]
I mean, how to use By.linkText or By.partialLinkText in FluentLenium (I know that by.id and by.classname uses (# and .) . Sorry about the bad word.

**Comment by Toilal** [comment]
From README file, 

> you can use By locator Selenium object instead of CSS selector argument: find(By.cssSelector(".header"))

It should work with any other  default selenium By condition, including ```partialLinkText``` and ```linkText```.

**Comment by rguimaraesr** [comment]
Amazing. Thank you @Toilal
