### ISSUE TITLE
How to assert if an element contains some text?

### ISSUE THREAD

**Issue by rguimaraesr** [FluentLenium/FluentLenium#286]
I'm trying to check if an element **contains** some text. 

Using some like that (assertThat(find("form-group>label")).hasText("Blabla");)  don't check if it **contains** some text.

**Comment by Toilal** [comment]
Use can use String matcher from AssertJ using findFirst.

```java
assertThat(findFirst("form-group>label").getText()).contains("Blabla")
```

**Comment by rguimaraesr** [comment]
@Toilal thanks once again.
