### ISSUE TITLE
How assert text using a "find(By.xpath)" sentence?

### ISSUE THREAD

**Issue by rguimaraesr** [FluentLenium/FluentLenium#287]
I'm trying to check text using something like that: "assertThat(find(By.xpath("//*[@id='account-form']/div[11]/div[1]/div/label")).hasText("blabla");" But Eclipse returns that 'hasText' is undefined for the type FluentList...

**Comment by Toilal** [comment]
Currently, Selenium By selectors are not supported by AssertJ Assertions module.

**Comment by rguimaraesr** [comment]
@Toilal any workaround?

**Comment by Toilal** [comment]
```assertThat(find(By.xpath("//*[@id='account-form']/div[11]/div[1]/div/label").hasText("blabla")).isTrue();```

Of course failure message won't be as explicit as expected.

**Comment by Toilal** [comment]
Closing in favor of #320
