### ISSUE TITLE
Cannot separate Hooks class

### ISSUE THREAD

**Issue by rakesh0404** [FluentLenium/FluentLenium#291]
me using this apis, It is going really good 

My concern is to separate  hooks and steps definition, When i tried that it throwing null pointer exception

**Comment by Toilal** [comment]
Can you explain what you call a "hook" and a "step" ? I can't understand. If you have a NPE, please paste the whole stracktrace here.

**Comment by rakesh0404** [comment]
This is one of the cucumber step definition in our framework 
 
public class CommonStepDef extends FluentAdapter {
@Given("^I navigate to \"([^\"]*)\" in \"([^\"]*)\"$")
    public void iEnterURL(String url, String page) {
         goTo(url);
    }


My Cucumber hooks
public class Hooks extends FluentAdapter{
 @Before
    public void setUp() {
        this.initFluent(new FirefoxDriver());
    }


When i Run my cucumber test it opens firfox browser and then it throws below error 
 java.lang.NullPointerException
      	at org.fluentlenium.core.Fluent.goTo(Fluent.java:325)

If i move @Before method to CommonStepDef it works straight way

**Comment by Toilal** [comment]
You should extend ```FluentCucumberTest``` instead of ```FluentAdapter``` and override ```getDefaultDriver()``` method to return the WebDriver you need.

It requires ```fluentlenium-cucumber``` dependency (pom.xml).

```
<dependency>
    <groupId>org.fluentlenium</groupId>
    <artifactId>fluentlenium-cucumber</artifactId>
    <version>...</version>
</dependency>
```

**Comment by Toilal** [comment]
Ho I see, you want to separate Step in another class, so step should not initialize a webdriver ... I think it's a new use case that is not implemented in current FluentLenium version.

**Comment by rakesh0404** [comment]
Yeah you got my point

**Comment by filipcynarski** [comment]
I've updated cucumber and examples in examples section your goal can be achieved w/o any additional changes in the code. Please let us know if you need any further assistance.
