### ISSUE TITLE
There's some way to configure a Firefox profile in fluentLenium?

### ISSUE THREAD

**Issue by rguimaraesr** [FluentLenium/FluentLenium#292]
I want to load FireFox with a profile that has Portuguese as main Language. There's some example or a way to do this?

**Comment by filipcynarski** [comment]
Hello @rguimaraesr, you need to follow instructions like this: http://stackoverflow.com/questions/12031253/what-profile-does-selenium-webdriver-use-by-default

So create a profile file, save, and load to your tests suite.

**Comment by filipcynarski** [comment]
@rguimaraesr here is something better (step-by-step) example: http://www.software-testing-tutorials-automation.com/2014/05/how-to-create-and-use-custom-firefox.html

**Comment by filipcynarski** [comment]
However it is not FluentLenium specific feature so we cannot advise anything more :)

**Comment by rguimaraesr** [comment]
@filipcynarski  Yes, I Know how to do this in Selenium Webdriver. My doubt is in FluentLenium. How can I do something like my code. Can I pass this in 'goto' ?

```Java
protected void start(DriverLanguage locale) throws IOException {
		FirefoxProfile firefoxProfile = null;

		if(locale == DriverLanguage.EN) {
			File profileDir = new File("profiles/en-us");
			firefoxProfile = new FirefoxProfile(profileDir);
		}
		else if(locale == DriverLanguage.PT){
			File profileDir = new File("profiles/pt-br");
			firefoxProfile = new FirefoxProfile(profileDir);
		}
		else if(locale == DriverLanguage.ES){
			File profileDir = new File("profiles/es");
			firefoxProfile = new FirefoxProfile(profileDir);
		}

		this.setDriver(new FirefoxDriver(firefoxProfile));
		this.getDriver().manage().window().maximize();
```

**Comment by filipcynarski** [comment]
I think you are doing it wrong. You should inherit in your test class from FluentTest and override the getDefaultDriver method

```
@Override
    public WebDriver getDefaultDriver() {
        File profileDir = new File("profiles/pt-br");
        firefoxProfile = new FirefoxProfile(profileDir);
        return new FirefoxDriver(firefoxProfile);
    }
```

and let the FluentLenium to manage drivers your implementation doesn't instrument FluentLenium but creating new drivers outside of library.

**Comment by filipcynarski** [comment]
Common approach in using FleuntLenium is to build a master class for configuration which all tests inherits from. This master class should inherit from FluentTest and you can build entire instrumentation there (browsers, profiles, dimensions, and so on and so forth). Please let us know if something remains cloudy to you or attach example archive if you need more help.

**Comment by rguimaraesr** [comment]
Good @filipcynarski Now I visualize the big picture. Thank you so much.
