### ISSUE TITLE
With TestNG groups, @Page and driver are null

### ISSUE THREAD

**Issue by johncam1** [FluentLenium/FluentLenium#302]
Hi. 
When test method are annotated with groups, it seems that driver and page (@Page) are not initialize because they are always null. This is not the case if groups are not used.

Below is test code that repeat my problem.

public class Test1 extends FluentTestNg {
        
        private WebDriver driver;

        @Page
        private LoginPage loginPage;

         @Override
	 public WebDriver getDefaultDriver() {
		 return new FirefoxDriver();
	 }

        @BeforeMethod
        public void setUp() throws Exception {
                 driver = getDriver();
		 driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        }

        @Test(groups = "mygroup1")
        public void someTest() throws Exception {
                goTo(loginPage);
                loginPage.nameForm.text(id);
                loginPage.passwordForm.text(password);
                loginPage.submit.click();
        }
}

Output is:
- getDefaultDriver() is not call
- in someTest() method, loginPage is null and I have this exception

java.lang.IllegalArgumentException: Page is mandatory
	at org.fluentlenium.core.Fluent.goTo(Fluent.java:303)

If I remove group on test method (ie. replace @Test(groups = "mygroup1") by @Test), everything are OK

Otherwise, if I used createPage to initialise loginPage in test method or in @BeforeMethod, 
Output is:

java.lang.NullPointerException
	at org.fluentlenium.core.Fluent.goTo(Fluent.java:325)
	at org.fluentlenium.core.FluentPage.go(FluentPage.java:48)
	at org.fluentlenium.core.Fluent.goTo(Fluent.java:305)

In Fluent.java exception in goTo method declaration on line "this.getDriver().get(url);". This mean that getDriver() result with null value.

This is my problem. Some idea on how to avoid it ?

**Comment by Toilal** [comment]
This issue has been fixed with this commit : https://github.com/FluentLenium/FluentLenium/commit/92a381193a630057a072648d514319d4f3183f96

Unfortunatelly it's not released, it will be released with 1.0.0 which bring lots a new features and cool stuff, but also some breaking changes that could require some work to migrate.

Stay tuned, it will be out in few weeks.

**Comment by Toilal** [comment]
Maybe we could release a bug fix release for current version though...

**Comment by Toilal** [comment]
I've cherry-picked the bug fix on https://github.com/FluentLenium/FluentLenium/tree/0.x branch. You can try to compile the project by yourself, or wait for the bugfix release (will be 0.13.2).

**Comment by Toilal** [comment]
@johncam1 It's now available as 0.13.2 on maven central.

**Comment by jfoping** [comment]
Thx a lot. I will set and test it. Hope it fix my problem.

**Comment by jfoping** [comment]
Hi, after test, i confirm that the new version fix my problem. Thx for help.

**Comment by johncam1** [comment]
Hello,
You are right @jfoping. The bugfix release 0.13.2  fix the pb of NTE while using testng groups. 
@Toilal what are others features and "cool stuff" in this new version ?
Best regards

**Comment by Toilal** [comment]
You can get the list of issues related to 1.0 here => https://github.com/FluentLenium/FluentLenium/issues?q=is%3Aissue+milestone%3A1.0

Almost every part of the code has been refactoring or rewriten, and there'll be a migration path.

README from master branch contains everything ,but I still have to develop the "automated waits" feature : it will be possible to add hooks on WebElement, and one default hook will be automated wait on click, find, etc ...
