### ISSUE TITLE
Introduce @Text, @TextContent, @Html, @Value ... injection annotations

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#319]
Would be great to create new injection annotations to automatically inject text, text content, value and html.

instead of writing 

```java
class Test extends FluentTest {
    @FindBy(css = ".text-element")
    FluentWebElement someElement;

    String someElementText;

    @Test
    public void test() {
        someElementText = someElement.getText();
    }
}
```

We could write this
```java
class Test extends FluentTest {
    @FindBy(css = ".text-element")
    @Text
    String someElementText;

    @Test
    public void test() {
    }
}
```

Same for textContent(), value(), html() ...

**Comment by Toilal** [comment]
String are not interface, so it won't be possible to build proxies for them with JDK. Maybe it's possible with CGLIB, but feasability must be investigated.

**Comment by filipcynarski** [comment]
For me it will make the code hard to read and debug. I don't feel like this feature is something what I would like to use.

**Comment by Toilal** [comment]
Ok, I close then. it's not hard to call text() or value on the element itself, true :)
