### ISSUE TITLE
AssertJ matchers

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#320]
Make AssertJ matchers as consistent as possible with FluentList and FluentWebElement capabilities. Currently some methods are missing, like isPresent() and isLoaded().

**Comment by btiernay** [comment]
Also, would be nice to have isNotAt for pages

**Comment by Toilal** [comment]
I also think the `isAt()` method from `FluentPage` should be removed, in favor of the assertJ matcher. 

Or maybe `isAt()` method from `FluentPage` could return a boolean, instead of performing an hidden assertion.

This method has always confused me since I use FluentLenium.

**Comment by filipcynarski** [comment]
I've added AssertJ native methods, but will take a look on this issue to consider ideas from this task.

**Comment by filipcynarski** [comment]
I think we should return `boolean` type for isAt it is better than removing this method which may be used by many of us. Adding boolean is a not big deal and may improve tests readability - removal hidden assertion.

**Comment by filipcynarski** [comment]
#492 reported.
