### ISSUE TITLE
@VisualDebug Hook

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#322]
With a hook (@VisualDebug), we could add some colorful overlay in the DOM through javascript to visually understand what the script is performing.

**Comment by btiernay** [comment]
Interesting. How would this be viewed, with screenshots?

**Comment by Toilal** [comment]
This could be viewed "live" and on screenshots. This will be done with CSS injection.

**Comment by filipcynarski** [comment]
In my opinion, it is too much, DOM manipulation is something that we do not want to do, is anyone against closing the issue please shout.
