### ISSUE TITLE
Remove all is- and are- prefixed for better readability

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#338]
```
await().until(notification).not().isDisplayed();
```

Change it to something like that:

```
await().until(notification).displayed()
await().until(notification).not().displayed();
```

You also have some functions like "hasText", "containsText"

text().contains() would be better 
and text().equalsTo()

**Comment by Toilal** [comment]
Should we rename them from FluentWebElement too ? also, I think there's an inconsistency because there are some methods on FluentWebElement, like ``isDisplayed`, `isEnabled`, ... which are not available on FluentList.

**Comment by filipcynarski** [comment]
Yes, I think so. We should review all naming because my feeling is it is inconsistent in FluentLenium, so as a piggy back of releasing breaking changes we can make it clear.

**Comment by Toilal** [comment]
I also remove some get, like `getText`, `getAttribute`, etc ... And `text(String ...)` which is a "setter" will be renamed to `write(String ...)` to avoid collision with `text()` getter.

**Comment by Toilal** [comment]
Done
