### ISSUE TITLE
Add ability to capture javascript errors

### ISSUE THREAD

**Issue by btiernay** [FluentLenium/FluentLenium#340]
It would be really useful to have first class support for capturing, accessing and asserting on javascript errors during tests. There are a couple of approaches I've seen here:
- http://www.3pillarglobal.com/insights/how-to-capture-javascript-errors-from-your-web-application
- http://stackoverflow.com/questions/4189312/capturing-javascript-error-in-selenium

Something that could abstract the Driver would be ideal (last link)

**Comment by Toilal** [comment]
Really a good idea :). We will do something, thanks.

**Comment by Toilal** [comment]
This project seems interesting : https://github.com/mguillem/JSErrorCollector

But is it maintained ?

**Comment by Toilal** [comment]
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/148

Seems to be difficult to implement, if doable ...

**Comment by filipcynarski** [comment]
It seems like it may differentiate depending on drivers/browsers, so may be difficult to provide generic solution for that, but it is my first impression, maybe won't be so hard.

What about adding it as a spike task for 1.1 release?

**Comment by btiernay** [comment]
For SPAs, there might be some value in having the ability to inject a script that collects the errors. It  would have limitations for the initial page load, but would probably work in 90% of the use cases

**Comment by btiernay** [comment]
I may try creating a hook that uses approach 3 to check errors after click, etc:

http://www.3pillarglobal.com/insights/how-to-capture-javascript-errors-from-your-web-application

Only works for Chrome though. Maybe this approach, the FF extension and a fallback for other browsers based on script injection might be a fairly good solution?

**Comment by slawekradzyminski** [comment]
Closing this because it seems to be browser specific. If https://github.com/w3c/webdriver/issues/406 is done this feature request can be reopened.

As a workaround, you can capture console errors in Chrome:

`@After
    public void verifyConsoleErrors() {
        Logs logs = getDriver().manage().logs();
        LogEntries logEntries = logs.get(LogType.BROWSER);
        List<LogEntry> errorLogs = logEntries.filter(Level.SEVERE);

        if (errorLogs.size() != 0) {
            for (LogEntry logEntry: logEntries) {
                System.out.println("Found error in logs: " + logEntry.getMessage() );
            }
            fail("Console error found");
        }
    }`
