### ISSUE TITLE
Parameters for @PageUrl and goTo()/isAt()

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#342]
Add support for this use case :

``` java
@PageUrl("/page/{0}/{1}")
public class ParamPage extends FluentPage {
    ....
}
```

``` java
public class ParamTest extends FluentTest {
    @Page
    private ParamPage page;

    @Test
    public void test() {
        // Navigate to "/page/param1/param2"
        page.goTo("param1", "param2");
        ....
    }
}
```

**Comment by btiernay** [comment]
Or perhaps with page fields as well?

```java
@PageUrl("/page/{id}")
public class ParamPage extends FluentPage {
    String id;

    public ParamPage(FluentControl control, String id) {
        super(control);
        this.id = id;
    }
   
}
```

```java
public class ParamTest extends FluentTest {
    @Test
    public void test() {
        // Navigate to "/page/1"
        val page = getPage(ParamPage.class, "1");
        page.go();
        ...
    }
}
```

**Comment by Toilal** [comment]
@btiernay I won't implement your option, because Page instance will be the same for all possible parameter values.

Instead, there will be a `String parameter(String paramName)` method to retrieve value of a parameter.

**Comment by Toilal** [comment]
I also want to support better syntax for optional parameters.

Something like `@PageUrl("/document/{document}{?/page/page}")`.

Calling `go("123")` will generate `/document/123` URL, and calling `go("123", "456")` will generate `/document/123/page/456`
