### ISSUE TITLE
LocalDriver (Chrome, Firefox) required on local machine but RemoteDriver is used

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#343]
For project which is running tests remotely using SeleniumGrid, I have configured ChromeDriver as an optional server and even I'm not using it FluentLenium is trying to create an instance of the driver and throwing errors (not running tests on Selenium Grid)

```
10:37:55.269 Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
10:37:55.269 	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
10:37:55.269 	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
``` 

So it requires to have ChromeDriver or Firefox installed but doesn't really need it on the machine where the Selenium tests are running because these tests would be run remotely.

**Comment by filipcynarski** [comment]
The behaviour of getting first available driver is a little bit confusing that's why it seems broken but the unit test was failing where getWebDriver method was overridden instead of newWebDriver method.

So not a bug it is a feature :)

One more thing so why should getWebDriver be public? Let's make it protected or private if newWebDriver is suggested way

**Comment by Toilal** [comment]
getWebDriver should be public but final :).

It can be used to perform native Selenium WebDriver calls inside FluentTest.

**Comment by Toilal** [comment]
It has to be public because it's defined in FluentControl interface. Thanks to lombok @Delegate, it's also available in Page and Components.
