### ISSUE TITLE
Better assertions for FluentPage

### ISSUE THREAD

**Issue by btiernay** [FluentLenium/FluentLenium#345]
It would be useful to know the following when a `FluentPage#isAt` call fails:
- `@FindBy` selector
- Page title
- Current url

This lack of context is something I find in general when working with selenium tests and single page applications. Failure diagnosis is certainly something where FluentLenium could help a lot.

**Comment by Toilal** [comment]
You are right about this need to Context on failures. We could provide a better error message on isAt, but #316 goes also in the direction of better error messages. It's a point we could improve soon.

**Comment by btiernay** [comment]
Yes that would be very useful too. Having a look at all the assertj assertions, it also looks like they have zero or very little context as well. For example isDisplayed just says "Object is not displayed" on failure

**Comment by slawekradzyminski** [comment]
Let's add simple page assertions here:

hasElement(FluentWebElement);
hasTitle(String);
hasUrl();

**Comment by slawekradzyminski** [comment]
```java
@Test
    public void verifyPageAssertions() {
        assertThat(reactDemoPage).hasTitle("MobX React Form");
        assertThat(reactDemoPage).hasPageSourceContaining("light-red");
        assertThat(reactDemoPage).hasElements($("button"));
        assertThat(reactDemoPage).hasElement(el("[name=email]"));
        assertThat(reactDemoPage).hasElementDisplayed(el("[name=email]"));
        assertThat(reactDemoPage).hasExpectedElements();
        assertThat(reactDemoPage).hasExpectedUrl();
        assertThat(reactDemoPage).hasUrl("https://foxhound87.github.io/mobx-react-form-demo/demo");
    }
```

**Comment by slawekradzyminski** [comment]
done
