### ISSUE TITLE
Lack of browser information when test case is failed

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#377]
Currently FluentLenium looses information about used webdriver we need to figure out how to pass this information to Selenium.

**Comment by Toilal** [comment]
Do you mean that ...

```
org.openqa.selenium.TimeoutException: Timed out after 30 seconds waiting for ihm.test.base.LsunFluentTest$$Lambda$10/2048227213@10a42b25
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'devnat-forge.in.ac-grenoble.fr', ip: '192.168.58.193', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-642.1.1.el6.x86_64', java.version: '1.8.0_45'
Driver info: driver.version: unknown
```

The last line should display more information about WebDriver ?

**Comment by Toilal** [comment]
I think it's because FluentLenium wraps the WebDriver into EventFiringWebDriver to support events. So it's a Selenium Issue, I think.

**Comment by filipcynarski** [comment]
Indeed I would like to see browser version instead of `driver.version: unknown`

**Comment by Toilal** [comment]
I've read the source code of Selenium WebDriverException, and it displays the Driver class name without the Driver part... For example, it displayed HtmlUnit when HtmlUnitDriver is detected in the stacktrace.

**Comment by Toilal** [comment]
@filipcynarski I think it should be reported on Selenium bug tracker, because we can't handle how this message is generated.

**Comment by Toilal** [comment]
PS: The issue occurs because we are using EventFiringWebDriver.
