### ISSUE TITLE
Integration tests sometime fails

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#397]
Integration tests sometime fails with this error.

```
org.fluentlenium.integration.FluentLeniumFunctionalWaitTest
checkPolling(org.fluentlenium.integration.FluentLeniumFunctionalWaitTest)  Time elapsed: 1.837 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: org.openqa.selenium.TimeoutException
```

It most of time works, but sometimes travisCI fails with this error. Maybe it's due to parralel run of tests.

**Comment by filipcynarski** [comment]
So if the test is not Thread safe are we able to make it thread safe?

**Comment by Toilal** [comment]
I don't know why it sometime crash to be honest. This commit is more like a test, wait and see :)
