### ISSUE TITLE
Method names from WindowAction should match underlying Selenium method names

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#399]
rename maximizeWindow() to maximize() and fullScreen() to fullscreen(). Make the old method names as deprecated to avoid a breaking change.

**Comment by filipcynarski** [comment]
I think we can just rename these methods 3.0 is pre-release and not many users are using this one. So 3.0.1 can contain this braking change as far as it is documented.

**Comment by Toilal** [comment]
Also, we should make all methods from Selenium switchTo() available here.
