### ISSUE TITLE
scrollIntoView and click on firefox

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#414]
I use `@BeforeClick` and scrollIntoView to automatically scroll the clicked element into view before perfoming the click.

I hit an issue when running with firefox that locks the browser during the test.

As a workaround, here's my code :

``` java
@BeforeClickOn(64)
public void scrollIntoView(FluentWebElement element) {
    element.scrollIntoView();
    if (getWebDriver().equalsIgnoreCase("firefox")) {
        await().explicitlyFor(50);
    }
}
```

Maybe it should be integrated ? not sure though ...

**Comment by Toilal** [comment]
It is refresh the element yes. I don't think it's a side effect from our side, I really think it's a firefox or geckodriver bug. I can't reproduce this issue with chrome.

**Comment by filipcynarski** [comment]
Ok, do we have any idea how to avoid browser name if?

Maybe we should handle this issue and if issue occur refresh element reference w/o checking browser name

**Comment by Toilal** [comment]
Yes browser name and maybe version. Do you know how to retrieve those information from Selenium ?

**Comment by Toilal** [comment]
I think the problem occurs when running a JS Script and clicking the element the right after. Reloading the element doesn't really help in fact, but waiting 50ms fix. I've updated the snippet.

**Comment by filipcynarski** [comment]
Strange... I hate explicit waits. Isn't it better to wait for success? Instead of hardcoding any value for sleeps?

I can imagine `element.scrollIntoView();` can expose await for scrollable or JS ready and the invoke these method.

What do you think to add JSready-like await method?

**Comment by Toilal** [comment]
In  theory, we should need to do nothing ... 

scrollIntoView invokes a Javascript function which is synchronous, underlying element should be scrolled after the call. But invoking scrollIntoView and click just after makes the browser freeze for some reason.

This code is really a workaround for a possible bug in firefox or geckodriver, but I don't think it should come in FluentLenium, it should first be reproduced in a test environnement and reported to firefox or geckodriver issue trackers.

**Comment by Toilal** [comment]
Maybe it's related to this issue : https://bugzilla.mozilla.org/show_bug.cgi?id=1052109
