### ISSUE TITLE
Rephrase FluentLenium marketing description

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#416]
Rephrase FluentLenium marketing description on webpage, to help people understand benefits of using FluentLenium.

**Comment by filipcynarski** [comment]
Currently it is:

```
FluentLenium helps you writing readable, reusable, reliable and resilient UI functional tests for the browser.
```

I'm changing it to:

```
FluentLenium is a website automation framework which extends Selenium to write reliable and resilient UI functional tests. This framework is React ready. Written and maintained by people who are automating web browser tests on a daily basis.
```

**Comment by mamachanko** [comment]
@filipcynarski can you help me understand what "_React ready_" means?

**Comment by filipcynarski** [comment]
It means it works well w/ React JS framework :) We based our automation on FluentLenium and rewritten entire application (very complex one) to ReactJS so it is proven by example.
