### ISSUE TITLE
Not Implemented title method in FluentPage at V1.0.0.

### ISSUE THREAD

**Issue by dokechin** [FluentLenium/FluentLenium#433]
I want to use title method in FluentPage, but It does not seem to be implemented in version 1.0.0.
Is there any alternative means?

  public class ResultPage extends FluentPage{
  	public String getTitle(){
  		return title();
  	}
  }

**Comment by filipcynarski** [comment]
Hello @dokechin please use:

`
window().title()
`

**Comment by Toilal** [comment]
Docs are wrong here. I'll update them

**Comment by dokechin** [comment]
Thank you very much!!
 I can use window().title().
