### ISSUE TITLE
Is it possible to link with appium?

### ISSUE THREAD

**Issue by tiboun** [FluentLenium/FluentLenium#438]
Hi,

The current webDrivers list doesn't have any mention of "appium".
It would be great to have a web mobile testing from fluentLenium.
Do you think that is possible to include it ?

**Comment by Toilal** [comment]
It should work as Appium is an implementation of WebDriver.

To include it properly, you should try to create an Appium implementation of `org.fluentlenium.configuration.WebDriverFactory` returning the Appium WebDriver.

I see no reason why it would go wrong into FluentLenium.

**Comment by filipcynarski** [comment]
It works w/ Appium I automated some scenarios using Appium and FluentLenium too.

**Comment by tiboun** [comment]
Thanks for the answer. I'm gonna try that out :)
