### ISSUE TITLE
Race condition in FluentWebElementAssert.hasText

### ISSUE THREAD

**Issue by kutzi** [FluentLenium/FluentLenium#440]
I think we've encountered a race condition in FluentWebElementAssert.hasText
We got an assertion error like:
_"The element does not contain the text: xyz . Actual text found :  abc xyz"_

I think this could have been caused by a race condition because the text content is fetched twice for the remote webelement. Once for the assertion and again for the errorMessage:

> if(!actual.getText().contains(textToFind)) {
>             super.failWithMessage("The element does not contain the text: " + textToFind + " . Actual text found : " + actual.getText(), new Object[0]);
>         }

Fix: fetch the text only once and store in local variable.

Many other asserts in that class are probably vulnerable to the same race condition as well

**Comment by kutzi** [comment]
See https://github.com/FluentLenium/FluentLenium/pull/441

**Comment by filipcynarski** [comment]
@kutzi thank you for reporting the issue. Let me review impact of this issue and prepare fix for all affected areas.

**Comment by filipcynarski** [comment]
@kutzi I've created one commit from all of our changes on develop branch. Please take a look if you have a while.

**Comment by kutzi** [comment]
Looks good to me
