### ISSUE TITLE
Migration guide from 0.13.2 incomplete

### ISSUE THREAD

**Issue by kutzi** [FluentLenium/FluentLenium#445]
For example:

- .@SharedDriver seems to be gone (I find the replacement quite unintuitive)
- TriggerMode.ON_FAIL was renamed to AUTOMATIC_ON_FAIL
- package names have been renamed to org.fluentlenium.adapter.junit
- Fluent is gone (replaced by FluentAdapter?)
- createPage() seems to be gone from FluentTest - what is the replacement?
- FluentConditions.isNotPresent() is gone (replacement not().present()?)
- unclear what happened to FluentConditions containsText() and withText()
  - -text(...) seems to be the replacement, but then it's not clear if that checks for contains or equals-
  - Ah, see it now: text().contains() and so
- title() in Fluent seems to be gone without replacement? I.e. have to use 'native' getDriver().getTitle()
- click(selector) in Fluent seems to be gone without replacement? -> $(selector).click()
  - Also click(Element) -> Element.click()

**Comment by kutzi** [comment]
Also, I have to say that I find the removal of the is/has prefix not optimal in all occassions.
i.e. for assertions wait().until(...).hasSize(...) read IMHO more natural than
wait().until(...).size(...)

**Comment by kutzi** [comment]
Also don't understand why await().until(String selector) is gone.
That was a good convenience method IMO and migrating this is a lot of pain as it's not easy to do this with find-replace.

**Comment by kutzi** [comment]
The constructor of FluentWebElement has 2 additional parameters. While it was possible in 0.13 to wrap a FluentWebElement by calling super(delegate.getElement()) this doesn't seem to be possible at all now?
At least I cannot figure out, how to get a FluentControl and a ComponentInstantiator

**Comment by kutzi** [comment]
Wow, this is really huge.
We've got around 250 tests with FluentLenium 0.13 and migrating them all is really painful

**Comment by Toilal** [comment]
First of all, thanks for feedback. I'll try to update the migration guide after this discussion.

I'll try to answer all your questions ...

- `Fluent` class is gone yes. `0.13.2` was based on inheritance with a Fluent abstract class. It was blocking some feature implementations, caused some issues and complexity when dealing with the @SharedDriver annotation. Now FluentLenium use composition and delegation instead of inheritance. Fluent abstract class has been replaced with an interface named `FluentControl`. `FluentTest`, `FluentPage`, `FluentAdapter` implements it ...

- `createPage()` is replaced by `newInstance()`. You can pass a `FluentPage` subclass as before, but also a FluentWebElement subclass in order to instantiate it. (this answer question about the FluentWebElement constructor too).

- `isNotPresent()` is gone, in favor of `not()` method that negates the condition builder. Objective was to provide a simple API to negate any condition, without having to double the conditions internal codebase to support this.

- `@SharedDriver` has been removed and included in configuration features as driverLifecycle property. I'm sorry if this term doesn't make sense for you, but i'm pretty sure it makes more sense for newcomers.

- `await().until(".selector")` is removed to lighten the internal codebase. Maintaining this API would have cause many much more code for us to maintain. User have to replace with await().until(el(".selector")). This notation is a bit more verbose, but it allow to build wait condition with any feature provided by FluentLenium selectors, like filters and first()/last()/index(). We tried to make the API of await() API rely as much as possible on FluentLenium `$` selector function.

- `hasSize` condition (and others) has been renamed to make it consistent with advanced conditions builder like `size().equalTo()`. So you can write `size(3)` or `size().equalTo(3)`, it's just the same, and it will appear together in auto complete dialog of the IDE. But I agree it doesn't sounds like fluent english :(. Maybe we could enhance this in a later MAJOR version (FluentLenium 4 ? ;p)

I'm sorry if the migration is a pain for you ... It was painful for my own project which add more that 500 tests on 0.13.2, so I wrote this migration guide, but it can be enhanced with some of those answer points.

**Comment by Toilal** [comment]
Maybe regex replacement can help to migrate await().until(".selector"). (Example not tested ...)

```
search: await\(\).until\(\"(.*?)\"\)
replace: await\(\).until\(el(\"$1\"\))
```

**Comment by Toilal** [comment]
Also, if you rely on catching `NoSuchElementException` when searching element with `$`/`find`/`findFirst`, you have to add `now()` after the `find`/`el`/`$` function call, or replace with `present()`. (Because elements are lazy loaded now ...)

**Comment by Toilal** [comment]
So if you want to create a FluentWebElement from an existing WebElement, it's possible but unsupported with the API ... Do you have such a need ?

Maybe we could add `el(WebElement element)` to wrap a raw selenium `WebElement` into a `FluentWebElement` instance.

**Comment by filipcynarski** [comment]
@kutzi we have > 500 test scenarios which are really complex (execution time of all of those takes > 8h). We've spent one month to upgrade our suites with 2 persons. It is a massive work but I can say it improves stability of our tests. New FluentLenium is faster and more reliable so it is worth of all effort which you need to put on it.

@Toilal it would be great if you can extend migration guide basing on @kutzi comments. So we can leave this issue as a task for it.

**Comment by filipcynarski** [comment]
@Toilal `el(WebElement element)` seems like a good idea for me.

**Comment by kutzi** [comment]
Thanks a lot for the prompt and helpful answers!
I'll continue on Monday with migrating our tests.

The most pressing issues are still:
- subclassing of `FluentWebElement`: I've not understood yet how `newInstance()` can help with that. I'll have to see it in code
- shared driver config: what do I have to do now - the docu is not very clear about that?
  - call `setDriverLifecyle `- when?
  - override `getDriverLifecycle`?
  - the docu only talks about a `driverLifecycle `method which I cannot find

**Comment by Toilal** [comment]
`driverLifecycle` is one of the available configuration properties. They can all be defined with various ways : [see Configuration Ways in the docs](http://fluentlenium.org/docs/#configuration-ways).

For your case, to replace `@SharedDriver` annotation, you can either override `getDriverLifecycle`, call `setDriverLifecycle`, or use `@FluentConfiguration(driverLifecycle=DriverLifecycle.JVM)`. It's just a matter of style, choose the one you like.

You can also use `@FluentConfiguration(configurationDefaults=MyConf.class)` with the following implementation.

```java
public class MyConf extends ConfigurationDefaults {
    @Override
    public void getDriverLifecycle() {
        return DriverLifecycle.JVM;
    }
}
```

What do you really want to achieve by subclassing FluentWebElement ?

**Comment by Toilal** [comment]
About await().until(".selector") removed, I think the nicer new syntax is $(".selector").await().until(). ...

From the migration guide : 

- Replace `await().until("some-selector")...` with `await().until($(some-selector))...` or
`$(some-selector).await().until()...`.

**Comment by Toilal** [comment]
@kutzi, you can use new release 3.1.0 (or 1.1.0 if your are running Java < 8). There's a new `el(WebElement)`/`$(List<WebElement>)` method that can be used to wrap existing raw selenium element into fluentlenium element (`FluentWebElement`/`FluentList`).

**Comment by kutzi** [comment]
@Toilal thanks for your effort and your quick answers.
However, I fear that the el(WebElement) doesn't help me.
Let me explain my use case - sorry for not doing that until now:

We're overriding the `find() `method in our base test class to return a wrapped `FluentList` (called `SafeFluentList`). In that we're adding a `safeClick()` method which makes sure that a button is visible and clickable before doing the click - because a lot of devs did that wrong in their tests.
Now the `SafeFluentList` should return a analogue `SafeFluentWebElement` on `first()`, `last()` etc

For the FluentList this is easy, because it's an interface and I can just implement the interface independently and just delegate all calls to the original list.
FluentWebElement on the other hand is a class, which I can only subclass.
In 0.13 I could just call super(delegate.getElement()) in the constructor of SafeFluentWebElement.
In 3.x I cannot write a working constructor anymore, since I don't have access to the control and the instantiator.

**Comment by Toilal** [comment]
I now better understand :)

Two new features should match your need.

You should have a look to the [Hooks](http://fluentlenium.org/docs/#hooks) feature. It allows to execute code before/after interacting with WebElement, or before/after finding them. Take a particular look to the provided `@Wait` annotation hook, it should solve your initial problem without having to implement any custom method in test. If `@Wait` hook doesn't fit your extact need, you may implement your own custom hook annotation. Everything is described in the docs.

I have also introduced a feature called [Components](http://fluentlenium.org/docs/#components). It's useful to add custom methods on found elements. You can see it as an intelligent cast of FluentWebElement instances. It's a kind of Page Object, but attached to a particular DOM element, so you can have multiple instance of the same component type in the test. I personnaly use it to model custom component in the application under test (rows in an interactive table that contains buttons attached to each rows, custom HTML5/JavaScript selector, Date Picker, ...). I now use the Components feature much more that Page Object.

Hope it helps !

**Comment by Toilal** [comment]
Sources of a simple example hook : https://github.com/FluentLenium/FluentLenium/tree/develop/examples/quickstart/src/test/java/org/fluentlenium/examples/hooks

**Comment by kutzi** [comment]
Sounds awesome. I'llcheck out both options

**Comment by kutzi** [comment]
Also maybe worth mentioning that now Selenium 3 is required. This has some implications for Firefox using - i.e. requiring the geckodriver (per default)

**Comment by kutzi** [comment]
I also had an issue where we were doing something like
`js.executeScript("arguments[0].click()", find(SELECTOR_POPUP_CLOSE_BUTTON).first().getElement());`

That seemed to have stopped because of Lazy Locators (BTW: it was hanging forever! Is there some way to make it fail (fast)?)
I've changed this now to
`js.executeScript("arguments[0].click()", find(SELECTOR_POPUP_CLOSE_BUTTON).first().now().getElement());`
and it seems to work

**Comment by filipcynarski** [comment]
@kutzi indeed :) Selenium 3.0 is required and it is step forward if someone needs previous version can use previous version of FluentLenium.

Regarding to JS code which you wrote.

Why haven't you wait for element and assign existing one to the local variable like this:

```java
FluentWebElement myElement = el(SELECTOR_POPUP_CLOSE_BUTTON);
await().until(myElement).present();
js.executeScript("arguments[0].click()", myElement.getElement());
```
My question is why do you need invoke click using JS or is it a just example?

**Comment by kutzi** [comment]
Would be also possible to wait, yes. My point was a) that this doesn't work as before. b) it's breaking in a really bad way: hanging forever

On the point why we're clicking this way: I really don't remember. We tried it with normal clicks and that didn't work in that case. Maybe time to re-evaluate if it works now

**Comment by filipcynarski** [comment]
Thank you for clarification. It shouldn't hang forever, there should be some sort of timeout I agree.

Let's try to use click method it should work for you.

**Comment by filipcynarski** [comment]
@kutzi I've logged separate issue for timeouts: #458

**Comment by kutzi** [comment]
Another thing:
@FluentConfiguration(driverLifecycle = ConfigurationProperties.DriverLifecycle.CLASS)
seems to default to not delete any cookies, while in 0.13
@SharedDriver(type = SharedDriver.SharedType.PER_CLASS)
defaulted to delete cookies AFAIR

IMO deleteCookies=true is a mucher safer default

**Comment by Toilal** [comment]
Default should do nothing, it makes more sense to me.

**Comment by kutzi** [comment]
IMO the default behaviour should provide an as stable behaviour as possible.
And since we're reusing the driver for multiple tests, it's the most sane thing to delete the cookies between tests.
