### ISSUE TITLE
Delombok sources before putting into src.zip?

### ISSUE THREAD

**Issue by kutzi** [FluentLenium/FluentLenium#454]
Another thing I mentioned during migration from 0.13 to 3.x:

Fluentlenium now seems to use Lombok internally.
Unfortunately this seems to have the effect that the sources in the src.zip don't match the binaries. E.g. IntelliJ is complaining 'Library source does not match the bytecode for class FluentAdapter.

Is it possible to delombok the sources before putting it into the src.zip?

**Comment by filipcynarski** [comment]
I haven't faced such issue, I'm using IJ too. We have huge test suite and using one of the part as a module for different suites and preparing jar for some modules. I've never noticed that is a problem. Could you please prepare an example and isolate the issue? I'd be more than happy to resolve the problem on our end or suggest solution (basing on that we can extend our documentation) so it would be very useful for us too @kutzi.

**Comment by kutzi** [comment]
I guess you have installed the Lombok plugin for IJ, haven't you? I haven't.
I guess that's why we see different results.

**Comment by Toilal** [comment]
Yes, I think installing the plugin will solve the issue.

Le 21 déc. 2016 8:03 AM, "Christoph Kutzinski" <notifications@github.com> a
écrit :

**Comment by kutzi** [comment]
No, I've installed the Lombok plugin now and still see the same error

**Comment by filipcynarski** [comment]
Could you please paste it here or capture your screen?

**Comment by kutzi** [comment]
![screenshot from 2016-12-21 17-40-56](https://cloud.githubusercontent.com/assets/175061/21397579/45d17d42-c79c-11e6-833a-2841eeb4b8c7.png)

**Comment by filipcynarski** [comment]
It is nice explanation why you see the error like yours: https://github.com/rzwitserloot/lombok/issues/1062

We can delombok sources before packaging phase but I'm not sure it is an issue.

Are you facing any inconvenience because of that?

**Comment by filipcynarski** [comment]
Not an issue.

**Comment by LuckySpb** [comment]
For me this is an issue as well.
> We can delombok sources before packaging phase but I'm not sure it is an issue
This would be a solution.

May be maven plugin could be created where you can specify default behaviour for source code.

**Comment by filipcynarski** [comment]
More users voted it is an real issue, so we should add it to backlog then.

**Comment by filipcynarski** [comment]
Delombok sources may cause another issues, I'd suggest you to install Lombok support in IntelliJ I'm not facing the issue in newest IJ w/ Lombok plugin installed. Please shout if it is still an issue.

**Comment by filipcynarski** [comment]
Lombok has been removed in FluentLenium @kutzi starting from 4.1 version (release should be soon) you won't face this issue anymore. Cheers!
