### ISSUE TITLE
.and method to join await with action

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#456]
As a user I would like to be able to write:

`
fluentWebElement.await().until().present().and().click()
`

or

`
await().until(fluentWebElement).present().and().click()
`

or

`
fluentWebElement.waitAndClick()
`

What do you think about such feature?

**Comment by Toilal** [comment]
It would be nice, but hard to implement with this exact API because present actual returns a boolean.

**Comment by slawekradzyminski** [comment]
Let's add waitAndClick()

**Comment by slawekradzyminski** [comment]
done
