### ISSUE TITLE
Add Spock support in FluentLenium

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#467]
Add Spock support in FluentLenium

**Comment by filipcynarski** [comment]
it is addressed in feature/spock-support branch

**Comment by jarlehansen** [comment]
@filipcynarski let me know when you have had the chance to test the spock support

**Comment by filipcynarski** [comment]
@jarlehansen works good for me we can include this as a official module, thank you for your work. I'm planning to proceed w/ release soon.

**Comment by jarlehansen** [comment]
@filipcynarski thank you, looking forward to using spock with fluentlenium in my own projects :)
