### ISSUE TITLE
Delombok JARs for releases or remove Lombok

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#469]
Lombok cause issues with the sources on IDE side as well as SonarCube analysis

```
[08:01:15][Step 2/2] 08:01:15.939 WARN  - Class not found: lombok.NonNull
...
[08:01:17][Step 2/2] 08:01:17.775 WARN  - Class not found: lombok.NonNull
```

It is producing tons of WARNs so the safer is to introduce DeLombok feature in the code or remove Lombok at all

**Comment by Toilal** [comment]
I don't think removing Lombok is an option. We are relying too much on @Delegate.

False positive in code analysis tools should not guide our design choice. It's not possible to remove those false positive with SonarCube configuration ?

**Comment by filipcynarski** [comment]
@Toilal let's leave it as it is.

**Comment by filipcynarski** [comment]
Lombok has been removed from FluentLenium
