### ISSUE TITLE
[Question] Default path for ScreenShots/HTMLDumps?

### ISSUE THREAD

**Issue by diemol** [FluentLenium/FluentLenium#480]
Hi,

Is there a way to specify a default path for screenshots and HTML dumps? I see that if no parameter is specified, they are created on the project root folder.

Additionally, is it possible to get the file as a variable when the screenshot is taken? I am just trying to connect this feature with the "Attachments" feature from Allure1 - https://github.com/allure-framework/allure1/wiki/Attachments. I can get the file and convert it to bytes but maybe it could be done directly.

Thanks for this cool framework! It is really helpful.

**Comment by Toilal** [comment]
You can define default path for screenshots and HTML dumps using `screenshotPath` and `htmlDumpPath` configuration properties. (See configuration properties section in the docs).

With actual codebase, it's not possible to retrieve the filename of the generated screenshot. But i'll add a ScreenshotListener in a future listener to be able to get notified when a screenshot is taken.

**Comment by diemol** [comment]
Oh, I see, sorry, I didn't check the documentation properly, my bad.

If you want to, maybe point me to where you would add it, so perhaps I can figure it out and send a PR.

**Comment by gkiszczak** [comment]
Hi @diemol, sorry for late answer. Are you still looking for a solution? The easiest solution would be to create a JUnit rule to take a screenshot when a test fails and add allure @Attachment annotation.

**Comment by diemol** [comment]
Hi @gkiszczak,

I think I figured it out in a different way but I don't remember that anymore. Thanks for replying though. 

I'll close this issue since it is not relevant anymore.
