### ISSUE TITLE
[Question] Usage of fluentlenium.properties file

### ISSUE THREAD

**Issue by brunometzker** [FluentLenium/FluentLenium#481]
Hi,

I've been trying to define configurations through .properties file with no success. I was wondering if anyone could provide examples of usage of such file with IDE's and Maven, maybe add it to the documentation. Kinda confusing how to load it properly. 

Great framework by the way, I'm really liking the design choices and customization features.

**Comment by filipcynarski** [comment]
@brunometzker have you configured your framework successfully? Do you think it is still worth to add more information to the docs?

**Comment by brunometzker** [comment]
@filipcynarski yes I successfully configured with .properties file. It took me some time to figure out how the tools handled the classpath, so I think it would be very useful to add it to the docs.

Thanks for the response.

**Comment by filipcynarski** [comment]
@brunometzker could you please share your findings here. It would be better to use your case as a guidline for me to focus on problematic aspects for you.

**Comment by Toilal** [comment]
There's nothing custom in how FluentLenium handle the classpath, it's just java standard. I'm not sure it's worthing adding anything in the docs.

**Comment by filipcynarski** [comment]
ok, there is no response from @brunometzker from 23 days, so I think it can be closed.
