### ISSUE TITLE
Example from Docs not works with jetty.websocket 

### ISSUE THREAD

**Issue by arnzel** [FluentLenium/FluentLenium#482]
Hi, the example from the docs dont works with jetty '9.3.5.v20151012', but it does with '9.4.2.v20170220'.

Can the dependency being updated ?

**Comment by Toilal** [comment]
I can run with 9.3.5 here without any issue. however, we could upgrade FluentLenium to use latest Selenium 3 release, and upgrade to htmlunit driver 2.25 to avoid adding this dependency manually.
