### ISSUE TITLE
Example from docs uses removed until(String selector) method

### ISSUE THREAD

**Issue by smackfu** [FluentLenium/FluentLenium#484]
At http://fluentlenium.org/docs/, the first example in the **Wait for an Ajax Element to be available** section is using the `until(String selector)` method which doesn't seem to exist anymore in v1.x.

```
await().atMost(5, TimeUnit.SECONDS).until(".fluent").size(3);
```

I think the other examples in that section are correct since they use the `until($(selector))` method.

**Comment by filipcynarski** [comment]
@smackfu are you using v1.x?

Documentation describes the recent version only. Have you tried to upgrade to FL3.x?

**Comment by smackfu** [comment]
@filipcynarski oh interesting, was that method added back to v3?

**Comment by Toilal** [comment]
Thanks for reporting this @smackfu. It will be fixed on the website on next release.
