### ISSUE TITLE
[Question] XCUITest Appium

### ISSUE THREAD

**Issue by lndamaral** [FluentLenium/FluentLenium#485]
I'm using FluentLenium with a factory appium driver to automate some test cases for an iOS app. Whenever i try to locate some elements in an specific screen using lazy locators it fails with NoSuchElementException even though the element is present and visible. I can succesfully locate the element calling findElement directly from the driver instance. Unfortunately I can't provide the code examples. Anyone faced a similar problem?

Thanks in advance.

**Comment by filipcynarski** [comment]
are you using awaits before you call actions on elements?

**Comment by lndamaral** [comment]
I have tried both with and without with no luck.

**Comment by filipcynarski** [comment]
Are you able to provide your test code?

If not it is hard to say... :) Is it native iOS app or something based on Electron?

**Comment by lndamaral** [comment]
I can't provide the code but it is basically a fluent page instance with @FindBy FluentWebElements.

It is a native iOS app.

**Comment by filipcynarski** [comment]
well if you use el("elementLocator").click() instead of @FindBy does it work?

**Comment by lndamaral** [comment]
@filipcynarski Yes it does. What is the difference?

**Comment by filipcynarski** [comment]
FindBys are native Selenium interfaces we are creating a proxy objects to elements so it should also work if the first usage will point to existing element. Before you use object annotated by FindBy you need to check it does exist.

`$` `el` are lazy locators building a Locator doesn’t perform the search immediately. It will be searched later, just before it’s really needed to interact with the located elements.

**Comment by lndamaral** [comment]
Oh I see. Thanks for the support!
