### ISSUE TITLE
[Queston] Configuration Properties

### ISSUE THREAD

**Issue by brunometzker** [FluentLenium/FluentLenium#487]
Is there a way to retrieve the properties defined for a test run programatically?

Thanks in advance

**Comment by Toilal** [comment]
Yes, have a look to [Configuration](https://github.com/FluentLenium/FluentLenium/blob/develop/fluentlenium-core/src/main/java/org/fluentlenium/configuration/Configuration.java) interface. It's implemented by FluentTest.
