### ISSUE TITLE
isAt() method for AssertJ

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#492]
@Toilal said:
```
I also think the isAt() method from FluentPage should be removed, in favor of the assertJ matcher.

Or maybe isAt() method from FluentPage could return a boolean, instead of performing an hidden assertion.

This method has always confused me since I use FluentLenium.
```

@btiernay suggested:

```
Also, would be nice to have isNotAt for pages
```

Can be achieved if isAt return boolean value.

**Comment by lourish** [comment]
I see a few problems with this suggestion:

- It ties checking if the page is current to assertj, which is a separate module for good reason.
- Without an isAt() method it would not be possible to easily check if the page is current- instead one could only _assert_ it and users would need to handle exceptions.
- More complex checks created by overriding isAt() can currently be picked up by both the FluentLeniumAssertions and by any auto-generated custom assertions classes created on FuentPages e.g.  by the AssertJ assertion generations plugin.

**Comment by filipcynarski** [comment]
So let's skip this feature, I cannot see more advantages except cleaner architecture.
