### ISSUE TITLE
isAt() does not accept parameters (version 3.1.1)

### ISSUE THREAD

**Issue by thirstydeveloper** [FluentLenium/FluentLenium#494]
I'm trying to test is a redirect to a parameterized page e.g.,

```
    @Test
    public void successfulDirectLoginRedirectsToAccount() {
        goTo(loginPage);

        loginSuccessfully();

        assertThat(accountPage).isAt("someuser");
    }
```

where:

```
    @PageUrl("/account/{username}")
    public class AccountPage extends FluentPage
```

The [documentation](http://fluentlenium.org/docs/) shows this example:

```
    @Page
    private DocumentPage page;

    @Test
    public void test() {
        ...
        page.isAt(174, 3) // Assert that current url is "/document/174/page/3"
    }
```

Yet I see no isAt() method on Page objects taking in arguments.

Am I missing something here? If this isn't available, is there another recommended approach for my use case?

Thank you!

**Comment by Toilal** [comment]
I forgot to implement it, sorry about that ... I'll include this asap.

**Comment by filipcynarski** [comment]
Code merged will be released w/ 3.2

**Comment by thirstydeveloper** [comment]
Thanks! Looking forward to 3.2

**Comment by filipcynarski** [comment]
@thirstydeveloper I'm going to release 3.2 today
