### ISSUE TITLE
get "Can't create new WebDriver instance" when running the quick start example

### ISSUE THREAD

**Issue by idannik** [FluentLenium/FluentLenium#502]
```
import org.fluentlenium.adapter.junit.FluentTest;
import org.fluentlenium.core.hook.wait.Wait;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

@Wait
public class DuckDuckGoTest extends FluentTest {
    @Test
    public void title_of_duck_duck_go_should_contain_search_query_name() {
        goTo("https://duckduckgo.com");
        $("#search_form_input_homepage").fill().with("FluentLenium");
        $("#search_button_homepage").submit();
        assertThat(window().title()).contains("FluentLenium");
    }
}
```

**Comment by filipcynarski** [comment]
@idannik could you please paste stack trace and add more details?

**Comment by filipcynarski** [comment]
@idannik have you configured your webdriver properly (if not FluentLenium will expect to have chromedriver or geckodriver present in the system) we need stacktrace to help you? Because there was no update from 10 days, I have to close your issue if you won't reply on this comment.

**Comment by filipcynarski** [comment]
no response from the reporter @idannik issue, marked as closed, please feel free to reopen if it is still a case.
