### ISSUE TITLE
setCapability

### ISSUE THREAD

**Issue by gaponte1985** [FluentLenium/FluentLenium#505]
<img width="893" alt="screen shot 2017-06-12 at 1 52 55 pm" src="https://user-images.githubusercontent.com/996659/27047665-de6dc706-4f76-11e7-938c-dddd5fc26749.png">
<img width="1108" alt="screen shot 2017-06-12 at 1 53 07 pm" src="https://user-images.githubusercontent.com/996659/27047664-de6d1b30-4f76-11e7-93a4-1e8c2a32ecd4.png">

**Comment by gaponte1985** [comment]
I miss a import? not sure why is not working, this is the same example as you have

**Comment by filipcynarski** [comment]
Good catch @gaponte1985 there was a typo in documentation please replace semicolon on the end of line 13 w/ curly bracket and should work. *It is a method* sorry for confusion I'm updating docs right now
