### ISSUE TITLE
TriggerMode

### ISSUE THREAD

**Issue by gaponte1985** [FluentLenium/FluentLenium#506]
Configuration properties when I do the set methods can i call the Sets the trigger  so i pull it from a property file?

**Comment by filipcynarski** [comment]
Sorry @gaponte1985 could you please be more specific because I'm not sure I get your point.

**Comment by filipcynarski** [comment]
@gaponte1985 any update on that?

**Comment by gaponte1985** [comment]
I resolve this issue, thanks for your time
