### ISSUE TITLE
Fluentlenium & BrowserStack

### ISSUE THREAD

**Issue by yaziz** [FluentLenium/FluentLenium#507]
Hi!

I want to fetch the session id of browserStack with Java.
I know that I can do this from RemoteWebDriver but Fluentlenium provides me a EventFiringWebDriver. This object contains the session id but I can't get it (see screenshot).
<img width="710" alt="capture d ecran 2017-06-15 a 13 04 19" src="https://user-images.githubusercontent.com/5519128/27178647-648e97d8-51cb-11e7-883a-c21fd4efa952.png">

I'm also trying to cast EventFiringWebDriver in RemoteWebDriver but I have a CastException.
`String sessionId = ((RemoteWebDriver) getDriver()).getSessionId().toString();`

How could I fetch the session id from an EventFiringWebDriver?

Thanks.

**Comment by filipcynarski** [comment]
Hello @yaziz 

Thank you for reporting an issue. Could you please shed some light into the problem and provide the way how are you configuring your webdriver? Is it by class, or by properties files, could you please extract some problematic part of you project to make investigation easier to me?

**Comment by yaziz** [comment]
In effect, I used properties files but the overriding in FluentTest class is more flexible.
Thanks for your response. It is now possible to fetch the session id. 👍
