### ISSUE TITLE
org.fluentlenium.adapter.FluentAdapter.goTo

### ISSUE THREAD

**Issue by gaponte1985** [FluentLenium/FluentLenium#510]
I have the following step defenition

```java
public class GoogleSearchAPIFL extends FluentTest {
 @Given(value = "^The user is on the google pages$")
    public void the_user_is_on_the_google_pages() throws Throwable {

        goTo( "http://www.google.com" );
        // goTo(Property.getProperty("remoteUrl"));
        ExtentTestManager.logInfo( "" );
    }
}
```

when I run my feature file I getting 

```
java.lang.NullPointerException
	at org.fluentlenium.adapter.FluentAdapter.goTo(FluentAdapter.java:51)
	at cukes.steps.frameworkshakeout.UI.GoogleCreateNewUser.the_user_is_in_the_signup_page(GoogleCreateNewUser.java:22)
	at ✽.Given The user is in the signup page(CreateNewUser.feature:13)
```

Can you please help me

**Comment by filipcynarski** [comment]
@gaponte1985 are you using FluentLenium cucumber plugin?

**Comment by gaponte1985** [comment]
Any different extends FluentCucumberTest or FluentTest or FluentAdapter...

**Comment by filipcynarski** [comment]
@gaponte1985 there is a difference if you are extending each of those classes, that's why we have introduced those classes :)

Could you prepare exemplary archive w/ your project which isolates the issue which you are facing?

**Comment by filipcynarski** [comment]
@gaponte1985 is the issue resolved on your end? May I close the ticket or do you need more help from our side?

**Comment by gaponte1985** [comment]
Yees It was thanks

**Comment by tanvirqa17** [comment]
@gaponte1985 Can please let me know how you solved that issue? I am facing the same issue, I extented FluentCucumberTest and FluentTest, but still facing the same issue.

**Comment by norbertas-gaulia** [comment]
Same here any news?

**Comment by wriki** [comment]
Hi,
I am also facing the same issue. Can Anyone help me

**Comment by slawekradzyminski** [comment]
@koryl We need you here :)

**Comment by koryl** [comment]
@wriki, which version of FluentLenium are you using? Did you extended your step classes/base test class with FluentCucucmberTest?
It would be the best if you provide some code and we try reproduce the problem.

**Comment by wriki** [comment]
`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>fluent</groupId>
	<artifactId>testproject</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>testproject</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<junit.jupiter.version>5.3.2</junit.jupiter.version>
		<java.version>1.8</java.version>
		
		<selenium.version>3.5.3</selenium.version>
	</properties>
	<dependencies>
		
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-surefire-provider</artifactId>
			<version>1.3.2</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>selenium-jupiter</artifactId>
			<version>3.1.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.jupiter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-runner</artifactId>
			<version>1.4.0-RC2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.fluentlenium</groupId>
			<artifactId>fluentlenium-junit-jupiter</artifactId>
			<version>3.7.1</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.fluentlenium</groupId>
			<artifactId>fluentlenium-junit</artifactId>
			<version>3.7.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>3.141.59</version>
		</dependency>
		<dependency>
			<groupId>org.fluentlenium</groupId>
			<artifactId>fluentlenium-assertj</artifactId>
			<version>3.7.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
`

**Comment by koryl** [comment]
This issue is not related to Cucumber so this is different issue from the one which was mentioned at start of this thread. 
It seems you use FluentLenium 3.7.1. Could you try to upgrade to newest version (4.1.1) and check if issue you mentioned is still exist?

**Comment by koryl** [comment]
Another think is that you don't need to provide dependencies to JUnit Jupiter because it is already provided in FluentLenium JUnit Jupiter module. Moreover please remove this dependency if you don't use it:
```
 <dependency>
		<groupId>org.fluentlenium</groupId>
		<artifactId>fluentlenium-junit</artifactId>
		<version>3.7.1</version>
	</dependency>
```
because it is for integration with JUnit 4, not with JUnit 5 Jupiter.
Let us know if this help ;)

**Comment by wriki** [comment]
Thanks for speedy reply.
Now I am getting "No test found with test runner "junit5" 
`package testproject;

import static org.junit.jupiter.api.Assertions.*;

import org.fluentlenium.adapter.junit.jupiter.FluentTest;
import org.junit.jupiter.api.Test;

class Testfluen extends FluentTest{

	@Test
	void test() {
		fail("Not yet implemented");
	}

}`
`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>fluent</groupId>
	<artifactId>testproject</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>testproject</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.fluentlenium</groupId>
			<artifactId>fluentlenium-junit-jupiter</artifactId>
			<version>4.1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.fluentlenium</groupId>
			<artifactId>fluentlenium-assertj</artifactId>
			<version>3.7.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
`

**Comment by koryl** [comment]
Try something like this (I used WebDriverManger also):

```
import io.github.bonigarcia.wdm.WebDriverManager;
import org.fluentlenium.adapter.junit.jupiter.FluentTest;
import org.fluentlenium.configuration.FluentConfiguration;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Capabilities;
import org.openqa.selenium.chrome.ChromeOptions;

@FluentConfiguration(webDriver = "chrome")
public class SomeTest extends FluentTest {

    @Test
    public void test() {
        goTo("http://www.google.pl");
    }

    @Override
    public Capabilities getCapabilities() {
        WebDriverManager.chromedriver().setup();
        return new ChromeOptions();
    }
}
```

pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>example</groupId>
    <artifactId>example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-junit-jupiter</artifactId>
            <version>3.7.1</version>
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-assertj</artifactId>
            <version>3.7.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.141.59</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>(whatever version is current)</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

If you want use the newest version of FluentLenium you need set java.version property to 11:
`<java.version>11</java.version>`
