### ISSUE TITLE
Refactor static Impl class

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#515]
Refactor static Impl class - it is to much for me :) Should be refactored.

**Comment by slawekradzyminski** [comment]
I made few fixes here and now this class is called SharedWebdriverSingletonImpl. @filipcynarski  you can take a look and decide if it's still worth doing:

package org.fluentlenium.adapter.sharedwebdriver;

**Comment by slawekradzyminski** [comment]
Done
