### ISSUE TITLE
Cleanup tests + refactoring

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#533]
* Organize in packages
* Organize by functionality
* Improve maven POMs and modules for tests
* Replace French words by English

**Comment by slawekradzyminski** [comment]
@filipcynarski do want to repackage implementation classes as well? It would make sense to have implementation + tests in the same packages. My worry is that those changes would be breaking (users would have to update imports).

**Comment by filipcynarski** [comment]
we can introduce the next major version to highlight such change if it helps and make sense I'd like to change it.

**Comment by slawekradzyminski** [comment]
Let's close it and create a new task for repackaging (core + tests)
