### ISSUE TITLE
No javadocs

### ISSUE THREAD

**Issue by bledari** [FluentLenium/FluentLenium#540]

**Comment by filipcynarski** [comment]
Could you please elaborate? Do you want to have Javadocs available on web page or is there java doc annotation missing?

**Comment by bledari** [comment]
Yep, where are the web page javadocs? Also a migrations guide from older version would be great. You guys changed it all

**Comment by Toilal** [comment]
Damn... leave please.

**Comment by filipcynarski** [comment]
@bledari please find migration guide http://fluentlenium.org/migration/from-0.13.2-to-1.0-or-3.0/
we can add java docs for sure it is a task for us, thank you for your comment

**Comment by filipcynarski** [comment]
@bledari please find migration guide http://fluentlenium.org/migration/from-0.13.2-to-1.0-or-3.0/
we can add java docs for sure it is a task for us, thank you for your comment

**Comment by bledari** [comment]
Still no javadocs, why is this closed then?

**Comment by Toilal** [comment]
Not sure we need an HTML export of the JavaDoc if it's what you mean... 

What do you really mean, because there are JavaDoc everywhere in sources ?

**Comment by filipcynarski** [comment]
@bledari could you please elaborate?

**Comment by filipcynarski** [comment]
No response from reporter closing this one

**Comment by bledari** [comment]
I mean online Javadocs for different versions just like the Java API

**Comment by filipcynarski** [comment]
It is documentation issue, we can fix it

**Comment by slawekradzyminski** [comment]
Closing - priority too low
