### ISSUE TITLE
Change axes() to more descriptive name

### ISSUE THREAD

**Issue by gkiszczak** [FluentLenium/FluentLenium#544]
Currently, axes method is not enough descriptive. Would be good to rename it:
nodes, dom or scope.

**Comment by Toilal** [comment]
It is for XPath axes, but i would be in favor of traverse() or something
like that...

Le 5 oct. 2017 12:22, "Grzegorz Kiszczak" <notifications@github.com> a
écrit :

**Comment by filipcynarski** [comment]
@gkiszczak you need to remember to deprecate axes and introduce new name instead, we do not want to rid the axes out at this stage.
