### ISSUE TITLE
Self referencing bound FluentPage changes in release 3.4.0

### ISSUE THREAD

**Issue by petergphillips** [FluentLenium/FluentLenium#546]
3.4.0 introduces a recursive type declaration for FluentPage:
```java
public class FluentPage<P extends FluentPage>
```

This has broken all of my Kotlin code that extend the FluentPage object as the type now has to be specified (unlike in Java).  Also it makes constructing subclasses of FluentPage messy and in violation of DRY principles as we now have to write:
```java
public class AmendPage extends FluentPage<AmendPage>
```
whenever we want to create a page.  It also makes it prone to copy and paste errors e.g. 
```java
public class CreatePage extends FluentPage<AmendPage>
```

From what I can tell it appears it was added to return a type from the `go` method i.e. so that people can write:
```java
final CreatePage go = go();
```

This could alternatively be implemented by parameterising the return type of `go` instead:
```java
public <T extends FluentPage> T go()
```

and would therefore make the code cleaner without unnecessary duplication.

Would you therefore consider accepting a pull request to revert the signature change and alter the `go` method instead?

**Comment by filipcynarski** [comment]
@petergphillips please create the pull request and I can take a look, accept or propose different approach consistent w/ architecture. Thank you for reporting the issue I'm happy to help you

**Comment by Toilal** [comment]
I'm a kotlin user too and this language is gaining a high popularity in the whole Java ecosystem, so it's worth considering such change. I learned it on an Android app, but I know consider it for other Java related development as the experience was great.

From a technical point of view, even in java, i'm not a big fan of having too much generics. User can still override go() method to return a subclass of FluentPage.

**Comment by filipcynarski** [comment]
Issue resolved.
