### ISSUE TITLE
await().untilPage().isLoaded() doesn't wait for page reload after alert().accept()

### ISSUE THREAD

**Issue by albuch** [FluentLenium/FluentLenium#549]
We are facing an issue after upgrading to fluentlenium 3.4.1 (from 0.13.x).

Our application displays a Javascript confirmation dialog before submitting a form. After we accept the dialog Fluentlenium doesn't wait for the form submit to be completed before moving to the next step (e.g assertion). Even adding an `await().untilPage().isLoaded()` after `alert().accept()` fails to wait for the page reload.

The only thing that helps is adding an explicit wait (e.g. `await().explicitlyFor(1, TimeUnit.SECONDS)`)
 which is obviously not a good solution as it needs to be long enough to be fail-proof for network latency and it slows down the test.

```
$("#delete").click();
alert().accept();
await().atMost(10, TimeUnit.SECONDS).untilPage().isLoaded();
// This fails as the await() does not wait for the form submit after accepting the confirmation modal box.
assertTrue($("#deleted_element").isEmpty());
```

With fluentlenium 0.13.x we didn't even have to add any waits for this use case to work.

Is there a possibility to get form submits via Javascript to work without an explicit wait?

**Comment by filipcynarski** [comment]
What is the isLoaded method body for that page?

W dniu czw., 26.10.2017 o 10:57 Alexander v. Buchholtz <
notifications@github.com> napisał(a):

**Comment by albuch** [comment]
@filipcynarski : it is the same page as before the form submit, so waiting for specific elements not being present on the page is not an option.

**Comment by albuch** [comment]
I think I've found a solution that works rather well. As I know that it's a javascript call that triggers a submit I can set an implicit wait on the HTML element to get stale. after that I can add another implicit wait for the dom read event:

```
FluentWait<WebDriver> wait = fluentWait().withTimeout(10, TimeUnit.SECONDS);
wait.until(ExpectedConditions.stalenessOf(driver.findElement(By.tagName("html"))));
await().untilPage().isLoaded();
```
Do you see any side effects that this may have?

**Comment by filipcynarski** [comment]
@albuch I'm not sure what the `driver` variable reference is? Is it for FluentLenium driver or is it a separate instance?

What I afraid of is if you are waiting for `html` tag to be present something must be wrong w/ your await for page load?

Could you please share some part of the test and page object to give me possibility to suggest how you can improve it? You can create exemplary project which reproducing the issue.

**Comment by filipcynarski** [comment]
@albuch any update on that? I'm closing the issue please feel free to comment and put more details if help is still required.
