### ISSUE TITLE
Performance issue with find(), el(). 

### ISSUE THREAD

**Issue by aquddos123** [FluentLenium/FluentLenium#567]
We recently migrated from a very old version of Fluentlenium v0.10.3 to v3.4.1 along with Selenium from v2.53.1 to v3.6.0. We are seeing huge performance issues with our regression builds after the upgrade. The builds are taking almost double time to finish now. Any idea what's going on?

We use to have findFirst() and find() which are now replaced with find() and some places we are using el() and $(). We mostly need to rely on nested searches like few given below as an example. Also we run tests in INTERNET EXPLORER 11 using IEDriverServer 2.53.1 64 bit

`FluentList<FluentWebElement> elementList = find("li", withId().contains("some ID"), withText().contains("some text")).find("ol > li", withId().contains("some ID"));`

`find("li", withId().contains("some ID")).find("ol > li", withId().contains("some ID")).first().text()`

`el("li", withId().contains("some ID")).attribute("class");`

`el("#something").el("#something").find("li#ID").find("span", withText("some text")).click();`

All of the above were much much efficient in the older version with find() and findFirst(). 

Thanks, AQ

**Comment by filipcynarski** [comment]
@aquddos123 the use case which you described looks as explanation why your tests performance is so poor, I can play a little bit w/ the FL engine to tweak performance in that area but I afraid w/o any refactoring on your end and stopping use nested finds based on lists it won't be much better but as I said I'm marking this as a bug and want to work on it.

**Comment by aquddos123** [comment]
@filipcynarski Thanks for looking into this matter. 
I think find() in general is acting very slow compared to older version of find(). We can think about refactoring our nested searches wherever possible but would like to understand the current behavior first. Below are few more facts where find() is found slower even in single searches. 

`find("li"); // returned 66 results in 13 sec`

`find("li", withText().contains("some text")); // returned 3 results in 30 sec`

`el("li", withText().contains"some text")); // 1 sec`

`el("li", withText().contains"some text")).el("ol").find("li", withId().contains("partial ID")).size(); // returned 1 result in 29 sec`

`find("li", withText().contains"some text")).el("ol").find("li", withId().contains("partial ID")).size(); // returned 1 results in 35 sec`

`find("li", withText().contains"some text")).find("ol").find("li", withId().contains("partial ID")).size(); // returned 6 results in 40 sec `

**Comment by Toilal** [comment]
For each element matching the base selector but doesn't matching the programmatic filter, it will be slow because FL waits until timeout before actually considering this element really doesn't match. And it does this sequentially for each selected elements.

Do you use @Wait annotation ? If so, you can customize the timeout values in @Wait annotation parameter, see [@Wait annotation sources](https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/core/hook/wait/Wait.java)

**Comment by filipcynarski** [comment]
@aquddos123 are you good w/ solution suggested bt @Toilal please let us know is it still an issue on your side or you managed to fix the issue which you are facing on test design phase.
