### ISSUE TITLE
Cast issue 

### ISSUE THREAD

**Issue by angryfoxtanuja** [FluentLenium/FluentLenium#568]
Hi, 

I trying a run a simple program to take screenshot, but the cast issue is occurring, below is the code:
package testFirefox;

import java.io.File;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.TakesScreenshot;
import org.testng.annotations.Test;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import java.util.concurrent.TimeUnit;

public class DemoFirefoxOpen {

    @Test
    public void webDriver(){

        System.setProperty("webdriver.gecko.driver", "Geckodriver");
        FirefoxDriver driver;
        driver= new FirefoxDriver();
        driver.navigate().to("http://www.seleniumhq.org/");
        driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS) ;
        driver.findElement(By.xpath("/html/body/div[3]/div[1]/ul/li[5]/a")).click();
        //driver.findElement(By.linkText("Projects")).click();
        driver.findElement(By.xpath("//input[@id='q']")
        ).sendKeys("test", Keys.ENTER);
        driver.close();
      verifyLogin();
    }

    public  void verifyLogin() {

        System.setProperty("webdriver.gecko.driver", "Geckodriver");
        FirefoxDriver driver;
        driver= new FirefoxDriver();
        driver.navigate().to("https://github.com/login");
        driver.findElement(By.xpath("//input[@id='login_field']")
        ).sendKeys("tanuja.b@sigmainfo.net");
        driver.findElement(By.xpath("//input[@id='password']")
        ).sendKeys("Blogpost865@");

        driver.findElement(By.xpath("/html/body/div[3]/div[1]/div/form/div[4]/input[3]")).click();
        driver.findElement(By.xpath("/html/body/div[4]/div[1]/div[1]/div/div/a[1]")).click();
        String url = driver.getCurrentUrl();
        System.out.println(url);
        driver.quit();

    }

    public void getscreenshot() throws Exception
    {
            File scrFile = ((TakesScreenshot)webDriver()).getScreenshotAs(OutputType.FILE);
        //The below method will save the screen shot in d drive with name "screenshot.png"
        FileUtils.copyFile(scrFile, new File("Users/Desktop"));
    }
}

![screen shot 2017-12-14 at 4 53 31 pm](https://user-images.githubusercontent.com/19648350/33989973-6b9b6610-e0ef-11e7-8233-0899f3fbfa5f.png)

**Comment by gkiszczak** [comment]
Hi @angryfoxtanuja, the problem you're reporting is not related to FluentLenium. 
Your code looks incorrect:
in the getscreenshot method, you are calling webDriver() which is a test method and returns void (that is why you're getting casting error).

Please rearrange the code and fix syntax issues.
