### ISSUE TITLE
Add `containingText(...)` to docs

### ISSUE THREAD

**Issue by vrish88** [FluentLenium/FluentLenium#588]
Hello!

We are using FluentLenium on a project and had a difficult time finding an element that had some text. We were looking at the [docs](http://fluentlenium.org/docs/) and tried using `withText` and `withTextContent` to no avail. 

It turns out what we wanted was the `containingText` filter. However nowhere in the documentation of the methods nor the online docs did it say that `withText` and `withTextContent` performed an exact match.

How could the documentation be improved to communicate this distinction to future developers?

Thanks!

**Comment by gszczutkowski** [comment]
Created pull request #606 connected to this issue

**Comment by filipcynarski** [comment]
The issue is resolved as a result of #606 cheers!
