### ISSUE TITLE
Refactoring code to not use deprecated methods

### ISSUE THREAD

**Issue by koryl** [FluentLenium/FluentLenium#599]
I propose to check the source code and rewrite fragments that using deprecated method, like e.g.:
- in FluentWait class
`wait.**withTimeout**(duration, unit);` 
- in tests:
`verify(beforeAllListener).on(**isNull**(String.class), **notNull**(WebDriver.class), eq(NavigateAllListener.Direction.BACK));`

**Comment by slawekradzyminski** [comment]
Done
