### ISSUE TITLE
Reseting FluentList of Components not work correctly

### ISSUE THREAD

**Issue by gszczutkowski** [FluentLenium/FluentLenium#602]
I am not sure if it should work(could not find it in docs) but it looks like there are some problems with refreshing FluentList of Components.
I have added a few tests in ComponentListTest class in https://gitlab.com/g.szczutkowski/fluentlenium-list-test.git to indicate the problem.

If it works as expected then I think that docs should be updated accordingly - it is really not clear how to use FluentList with Components.

**Comment by gszczutkowski** [comment]
Created pull request with tests showing this issue. Added WIP because I am not sure if all tests are correct.

**Comment by kputh** [comment]
Are you refering to _FluentList.reset()_? I believe I have cases in my tests where the method fails outside of Components.

**Comment by slawekradzyminski** [comment]
I believe that the easiest solution for that bug would be:
1. Implement _.reset()_ method for FluentPage which will trigger _newInstance(Given.class)_ underneath
2. State clearly in the documentation that whenever DOM changes new element/page/list instantiation is required (or reset which does the same underneath).

**Comment by slawekradzyminski** [comment]
#637 needs to be fixed before this one as it fails on more basic FluentList case

**Comment by slawekradzyminski** [comment]
One of the issues here is _count()_ method implementation:

```java
    @Override
    public int count() {
        if (loaded()) {
            return super.size();
        } else {
            return LocatorProxies.getLocatorHandler(proxy).getLocator().findElements().size();
        }
    }
```

Basically once we load the list we just return initial size later.

**Comment by slawekradzyminski** [comment]
Done
