### ISSUE TITLE
When using fluentlenium version 3.6.1 doesn't work

### ISSUE THREAD

**Issue by salvada** [FluentLenium/FluentLenium#604]
Using fluentlenium 3.5.2 with selenium 3.9.1 everything works well. I tried to update to fluentlenium 3.6.1 with selenium 3.12.0 i get this message 

Expected only one instance, but found too many: [cucumber.runtime.java.spring.SpringFactory@50b494a6, cucumber.runtime.java.picocontainer.PicoFactory@3cef309d]
More than one Cucumber ObjectFactory was found in the classpath

You probably may have included, for instance, cucumber-spring AND cucumber-guice as part of
your dependencies. When this happens, Cucumber falls back to instantiating the
DefaultJavaObjectFactory implementation which doesn't provide IoC.
In order to enjoy IoC features, please remove the unnecessary dependencies from your classpath.

**Comment by filipcynarski** [comment]
@salvada could you please provide isolated issue in source code example? From your issue I understand you are using cucumber module, but it is not enough information for me to make sure is the issue resolved or not. It would be good if I can test we can fix the issue in next release.

**Comment by salvada** [comment]
@filipcynarski What do you mean for isolated issue?

**Comment by salvada** [comment]
You can close the issue. It was necessary to exclude dependencies that fluentlenium-cucumber brings

		<dependency>
			<groupId>org.fluentlenium</groupId>
			<artifactId>fluentlenium-cucumber</artifactId>
			<version>${fluentlenium.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.cucumber</groupId>
					<artifactId>cucumber-picocontainer</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
