### ISSUE TITLE
Remove lombok

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#626]
The Lombok is not bad but it was used almost everywhere and makes complex code harder to understand. We want to maintain easy to read and follow-up code now it requires a lot of time to dive into it.

Within Lombok removal we need to refactor a lot of classes and we want to do it as a piggy back as well.

**Comment by nikmanG** [comment]
This issue still open for doing?

**Comment by filipcynarski** [comment]
Yes, it is a new one

**Comment by filipcynarski** [comment]
Code merged task is done
