### ISSUE TITLE
Upgrade JUnit 5 to latest stable.

### ISSUE THREAD

**Issue by bobtiernay-okta** [FluentLenium/FluentLenium#630]
Using older versions or JUnit 5 leads to classloading issues on startup. `5.3.1` is the latest stable whereas `fluentlenium-junit-jupiter` is on `5.1.0`:

https://github.com/FluentLenium/FluentLenium/blob/develop/fluentlenium-junit-jupiter/pom.xml#L24

**Comment by filipcynarski** [comment]
@bobtiernay-okta it is done in 3.7.1-SNAPSHOT we will release the newest version soon. If you would like to have such simple upgrades available, please create pull request and we can merge it to code base faster.

**Comment by bobtiernay-okta** [comment]
Will do next time, thanks!
