### ISSUE TITLE
Upgrade from 3.4.1 to 4.0.0 missing methods .text() .value() .textContent() .attribute("")

### ISSUE THREAD

**Issue by jens-meiss** [FluentLenium/FluentLenium#635]
Hi, maybe i'm wrong but the doc's still say's that these methods are available:

* "Information" section
* $(".fluent").text()
* $(".fluent").value()
* $(".fluent").textContent()
* $(".fluent").attribute("myCustomAttribute")

But i can't find them in:

* https://github.com/FluentLenium/FluentLenium/blob/v4.0.0/fluentlenium-core/src/main/java/org/fluentlenium/core/domain/FluentList.java

they are now all in plurals returning a list:

* texts()
* values()
* textContents()
* attributes()

Can you explain the best way how to migrate to the new methods? I think texts().contains("<mystring>") is verry error prone.

**Comment by jens-meiss** [comment]
ok, thx for the quick response :)

since i have an abstract parent class for all the pages i think i will add the missing methods to this class or i have to change hundrets maybe thousand lines of code :)

i think 3.4.1 was the last version containing these methods, i can't find them in 3.5.0 as well ...

but i think you should fix the documentation about this anyway :)

**Comment by slawekradzyminski** [comment]
Yes, I agree it's a documentation bug. Thanks for reporting.
