### ISSUE TITLE
Bug: @org.fluentlenium.adapter.junit.After is not executed on test success  (JUnit)

### ISSUE THREAD

**Issue by nsherif** [FluentLenium/FluentLenium#655]
When using `@org.fluentlenium.adapter.junit.After` and configuring the screenshot on `org.fluentlenium.configuration.ConfigurationProperties.TriggerMode.AUTOMATIC_ON_FAIL`, the after method is not executed in case of a **successful** test.

**Comment by slawekradzyminski** [comment]
Thanks for report @nsherif 

I took a look and it seems like this feature is not complete. Currently `@org.fluentlenium.adapter.junit.After` is triggered instantly after test failure (see `FluentTestRule` class for implementation). `TriggerMode.AUTOMATIC_ON_FAIL` config doesn't seem to change anything here.

It should work like this:
1. `@org.fluentlenium.adapter.junit.After` should be triggered instantly after test failure (already met).
2. `@org.fluentlenium.adapter.junit.After` should be triggered after each annotated test succeeds. (TODO).

Also we don't inform users that `TriggerMode.AUTOMATIC_ON_FAIL` require custom `@org.fluentlenium.adapter.junit.After`. This should be added into docs.

**Comment by slawekradzyminski** [comment]
Fix merged
