### ISSUE TITLE
UrlTemplate#put(Map) doesn't set properties

### ISSUE THREAD

**Issue by picimako** [FluentLenium/FluentLenium#664]
The `put(Map)` method of [UrlTemplate](https://github.com/FluentLenium/FluentLenium/blob/4b0d551b8d32a9bc83e35b30ebf9aa3b565d6f3b/fluentlenium-core/src/main/java/org/fluentlenium/core/url/UrlTemplate.java) looks like the following:

```java
public UrlTemplate put(Map<String, String> values) {
    values.putAll(values);
    return this;
}
```

which doesn't really seem correct. Instead, based on the `put(String, String)` method I think it should put the argument values to the `properties` map.

**Comment by slawekradzyminski** [comment]
Thanks @picimako 

Would you be able to fix it?

I think we should do the following in this task:
1. Make _put(String, String)_ and _putAll(Map<String, String>)_ non public - users should use _add()_ and _addAll()_
2. Fix addAll() and put(Map<String, String>)
3. Add tests for addAll() 

add()

**Comment by picimako** [comment]
@slawekradzyminski 

Sure, I will create a fix. However I have some questions:
1. What do you mean by non-public, protected or package-private?
2. Could you please clarify what the problem is with `addAll()`?

**Comment by slawekradzyminski** [comment]
@picimako sorry, I didn't investigate too deep :)

_addAll()_ looks ok - please add tests to make sure

Let's just fix _put(Map<String, String>)_ and leave everything as is. I'll let you decide ;)

**Comment by slawekradzyminski** [comment]
It's done, thanks @picimako
