### ISSUE TITLE
Correct name of method takeScreenShot() in documentation

### ISSUE THREAD

**Issue by kputh** [FluentLenium/FluentLenium#689]
Hi,

The documentation refers to methods names _takeScreenShot()_ and _takeScreenShot(String)_. But somewhere between FluentLenium 3.4 und 3.7 these methods were renamed to _takeScreen**s**hot()_ and _takeScreen**s**hot(String)_. Please update the documentation. Thank you.

Regards,
Kai

**Comment by slawekradzyminski** [comment]
Thanks @kputh for the report. It will be updated in next release (we build docs from master branch).

It was fixed by @picimako, thanks :)
