### ISSUE TITLE
isAt assertion throw exception even url matches

### ISSUE THREAD

**Issue by pure4Sk** [FluentLenium/FluentLenium#698]
Tested url: https://lab6-us.awp.autotask.net/webhome?X2H2KPV_1a=FX2U-8GJL-RSVA-VRIT-EA1U#/dashboard/ViewDashboard.action

Anotation on pageObject
`@PageUrl("https://lab6-us.awp.autotask.net/webhome{server}/dashboard/ViewDashboard.action")`

In test step
```
String server = "?X2H2KPV_1a=FX2U-8GJL-RSVA-VRIT-EA1U#";
awpTeamMainPage.isAt(server); 
```

Err

> java.lang.AssertionError: Current URL [https://lab6-us.awp.autotask.net/webhome?X2H2KPV_1a=FX2U-8GJL-RSVA-VRIT-EA1U#/dashboard/ViewDashboard.action] doesn't match expected Page URL [https://lab6-us.awp.autotask.net/webhome?X2H2KPV_1a=FX2U-8GJL-RSVA-VRIT-EA1U#/dashboard/ViewDashboard.action]

**Comment by pure4Sk** [comment]
Anotation
`@PageUrl("/webhome{server}/dashboard/ViewDashboard.action")`
doesnt work either.

**Comment by pure4Sk** [comment]
<fluentlenium.version>3.6.1</fluentlenium.version>

**Comment by slawekradzyminski** [comment]
done
