### ISSUE TITLE
takeScreenShot() causes ClassCastException

### ISSUE THREAD

**Issue by philipmjohnson** [FluentLenium/FluentLenium#70]
I wrote a simple Play example system to illustrate Fluentlenium for my students:

https://github.com/philipmjohnson/play-example-fluentlenium

When I included a call to takeSnapShot, I got the following exception:

```
java.lang.ClassCastException: org.openqa.selenium.htmlunit.HtmlUnitDriver cannot be cast to org.openqa.selenium.TakesScreenshot
```

The call to takeScreenShot is here:

https://github.com/philipmjohnson/play-example-fluentlenium/blob/master/test/IntegrationTest.java

Am I doing something wrong?

Thanks,
Philip

**Comment by emilylin56** [comment]
Just like to know if this issue has been solved?
I still run into the same problem.
selenium.common.exceptions.WebDriverException: Message: org.openqa.selenium.htmlunit.HtmlUnitDriver cannot be cast to org.openqa.selenium.TakesScreenshot

**Comment by filipcynarski** [comment]
Which version are you using @emilylin56

**Comment by emilylin56** [comment]
Hi Filip,
I tried selenium-server-standalone-3.3.0 and selenium-server-standalone-3.1.0.
Both got the same issue. 
Screenshot is working fine with ie, edge, firefox but not htmlunit.
From log below, Htmlunit can get correct webdriver.title, test is successful, but screenshot is failed.
http://192.168.3.148:4444/wd/hub htmlunit
【test】什么意思_英语test的翻译_音标_读音_用法_例句_在线翻译_有道词典
Traceback (most recent call last):
  File "remote_ts.py", line 20, in <module>
    driver.get_screenshot_as_file("E:\\run_ok.jpg")
  File "E:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 798, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "E:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 817, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "E:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 827, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "E:\python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "E:\python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: org.openqa.selenium.htmlunit.HtmlUnitDriver cannot be cast to org.openqa.selenium.TakesScreenshot
Stacktrace:
    at org.openqa.selenium.remote.server.handler.CaptureScreenshot.call (CaptureScreenshot.java:36)
    at org.openqa.selenium.remote.server.handler.CaptureScreenshot.call (CaptureScreenshot.java:26)
    at java.util.concurrent.FutureTask.run (None:-1)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
    at java.lang.Thread.run (None:-1)

***Repl Closed***

**Comment by filipcynarski** [comment]
@emilylin56 I can't see fluentlenium here, see Python, Selenium but there is nothing about FluentLenium, which version of FluentLenium are you using, are you using it at all?

**Comment by filipcynarski** [comment]
You can check in the java code your webdriver using following code

```
 if (!(getDriver() instanceof TakesScreenshot)) {
                logger.error("Could not capture screenshot - selected web driver does not support taking screenshots");
                return;
            }
```

**Comment by filipcynarski** [comment]
@emilylin56 I think you hot this error because HTMLUnit doesn't support screenshots, so my code above may help you to handle that case, we can add such check on the FluentLenium level as well, it is not a big deal to introduce such validation. Do you think it may resolve your issue?

**Comment by emilylin56** [comment]
Hi Filip,
You can close this issue, I will check the java code as you suggest.

Thank you.

**Comment by krichter722** [comment]
The issue that

    java.lang.ClassCastException: org.openqa.selenium.htmlunit.HtmlUnitDriver cannot be cast to org.openqa.selenium.TakesScreenshot

isn't a very clear and helpful error message as mentioned by @MathildeLemee still isn't resolved, i.e. the issue shouldn't be closed.

I recommend admins to clean up comments which are unrelated to the issue or support requests.

**Comment by filipcynarski** [comment]
@krichter722 how are you taking screenshots? Which version of FL are you using? It should be handled in FluentLenium code right now.

**Comment by krichter722** [comment]
> @krichter722 how are you taking screenshots? Which version of FL are you using? It should be handled in FluentLenium code right now.

I guess it's not really a FluentLenium issue, my bad. Please close this again.

**Comment by filipcynarski** [comment]
Thank you!
