### ISSUE TITLE
Fluentlenium 4.0.0 jumping to JDK 11 

### ISSUE THREAD

**Issue by Sonali77** [FluentLenium/FluentLenium#701]
We at present use JDK 1.8. Fluentlenium 4.0.0 wants one to use JDK 11 whereas Selenium or cucumber doesn't do such major jumps. That means inorder to use Fluentlenium 4.0.0 one needs to upgrade to JDK 11. Fluentlenium also controls which version of Selenium and Cucumber one can use. Jumping from JDK 1.8 to 11 is a long jump for us. This means if we want to stay in JDK 1.8, the max Fluentlenium version we can go is 3.7.1. This has led us to think that fluentlenium should be taken out from our project. Please let me know why such a significant JDK jump was made in Fluentlenium 4.0.0.

**Comment by filipcynarski** [comment]
Hello Sonali77, Java 11 brings great features mostly performance related. So not moving to Java 11 if you are on 1.8 it is a big mistake, but I'm leaving it to your decision.

We are planning to support 3 version for a while so not worry all bug fixes are going to be merged to 3.7 as well. However, JDK 11 is a great improvement and in JDK 11 you can use JDK 1.8 libraries so it doesn't stop you to go to JDK 11 in your project. We have migrated many of our projects in our company and it wasn't a big deal. Technology is moving rapidly forward and we are not planning to stop on Java 1.8 if JDK is on 11 version already.

Honestly if you try to upgrade from JDK 1.8 to 11 you shouldn't face a lot of issues, most breaking changes were introduced in 1.8 and if you are running on 1.8 it is not a big deal to upgrade to 11 version ;) Thank you for your feedback, but as usual in IT industry if you are not progressing you are moving back

**Comment by slawekradzyminski** [comment]
Hi @Sonali77 

New features has been backported to Java 8.

https://github.com/FluentLenium/FluentLenium/releases

**Comment by fedotxxl** [comment]
strange idea to develop a library for Java 11 - I'm sure a lot of people still use Java 8.  It was a surprise for me...
