### ISSUE TITLE
FluentLenium specific IntelliJ inspections

### ISSUE THREAD

**Issue by picimako** [FluentLenium/FluentLenium#711]
Hi guys,

I created and collected a couple of IntelliJ inspections (Structural Search and Replace templates) for FluentLenium and I would like to get your opinion about them whether at least the concept of them is correct or they may need refinements.

You can find the document here: https://github.com/picimako/intellij-inspections/blob/master/inspections/fluentlenium.md

Though I already uploaded them to my repo of inspections, if you like these and you think it could add value to FluentLenium users I would be more than happy to contribute them to this project as a kind of IDE support.

**Comment by slawekradzyminski** [comment]
@picimako Let's add it somewhere in the docs and let the users decide how useful it is.

**Comment by slawekradzyminski** [comment]
done
