### ISSUE TITLE
Add setFileDetector() support in FluentLenium

### ISSUE THREAD

**Issue by clavecin92** [FluentLenium/FluentLenium#734]
when we upload a file on the browser using a remote web driver, the local file is not available on the remote because no way to call setFileDetector() (not available when we call getDriver()).
I'm using the Java Properties file "fluentlenium.properties" to configure the web driver so, the web driver instantiation is delegated to Fluentlenium.

**Comment by slawekradzyminski** [comment]
Hi @clavecin92, thanks for the report.

Which FluentLenium version do you use?

**Comment by clavecin92** [comment]
Hi,

The version is 3.5.2

Thank you in advance for your help

**Comment by slawekradzyminski** [comment]
Thanks @clavecin92 

Looks like we never actually exposed this method in FluentLenium. So in this task we should add it.

**Comment by slawekradzyminski** [comment]
Meanwhile @clavecin92 you can take a look how we navigate to urls in our project. See _getAbsoluteUrlFromFile(String)_ method

https://github.com/FluentLenium/FluentLenium/blob/develop/fluentlenium-core/src/main/java/org/fluentlenium/utils/UrlUtils.java

Honestly speaking using _setFileDetector()_ is probably code smell because your tests would work only on one operating system. Our solution for handling filepaths is OS-independent.

**Comment by clavecin92** [comment]
Thank you for your feedback,
But getAbsoluteUrlFromFile() just get the local file url and doesn't send file to remote hub selenium:
In my case, from a Jenkins job workspace, I need to upload a file to browser that is installed on a node of a remote selenium grid server

**Comment by slawekradzyminski** [comment]
All right, got it :)

**Comment by clavecin92** [comment]
Hi slawekradzyminski,

I would like to know if this feature will be implemented soon or I have to refactor my project to manage the Web Driver differently.

Thank you

**Comment by slawekradzyminski** [comment]
@clavecin92 that's not high on our priority list.

**Comment by clavecin92** [comment]
Hi slawekradzyminski,

sorry, I just back from vacation.

I took a look to the code, may be nothing to implement but I don't understand why when I use a RemoteWebDriver:
-  (getDriver() instanceof RemoteWebDriver) **return false**
-  getWebDriver().equals("remote") **return true**

**this is how I manage the WebDriver:**
- I use fluentlenium.properties to declare : 
     + webDriver=${defaultWebDriver}
     + capabilities=${webDriverCapabilities}
     + remoteUrl=${remoteWebDriverUrl}
- I call the WebDriver with the method "getDriver()" when needed

**this is my code to upload a file to a remote browser:** 
LocalFileDetector detector = new LocalFileDetector();
if (getDriver() instanceof RemoteWebDriver) {
      getDriver().setFileDetector(detector);
      getDriver().findElement(By.cssSelector("input[type='file']")).sendKeys(fileToUpload.getAbsolutePath());
}

**Comment by clavecin92** [comment]
I found a solution so, nothing to implement in Fluentlenium:

public void uploadFile(WebDriver driver, String file) {
        ResourceLoader resourceLoader = new ResourceLoader(file);
        LocalFileDetector detector = new LocalFileDetector();
        if ("remote".equals(getWebDriver())) {
            ((RemoteWebDriver) ((WrapsDriver) driver).getWrappedDriver()).setFileDetector(detector);
            (((WrapsDriver) driver).getWrappedDriver()).findElement(By.cssSelector("input[type='file']"))
                    .sendKeys(resourceLoader.getResourcePath());
        } else {
            driver.findElement(By.cssSelector("input[type='file']")).sendKeys(resourceLoader.getResourcePath());
        }
    }

**Comment by slawekradzyminski** [comment]
Great, Thanks for providing solution as well :)
