### ISSUE TITLE
No information to choose between Annotations and Event APi 

### ISSUE THREAD

**Issue by Manakel166** [FluentLenium/FluentLenium#737]
Hello,
I could not find a forum or mailing list so i'm asking here.
There is 2 options to register events provided in Fluent: Event Annotation and Event API.
What are the differences / benefit of one versus the other?

Aim is to provide some pré /post logging for Click, Navigate, setValue etc... that would work for all  
Pages implemented without having to modify each existing Page
With Regards
Woody

**Comment by slawekradzyminski** [comment]
Hi @Manakel166 - pré /post logging can be added by custom hooks. See our example:
https://github.com/FluentLenium/FluentLenium/tree/develop/examples/hooks/src/test/java/org/fluentlenium/examples/hooks

I'll answer initial question (Event Annotation vs Event API) in free time

**Comment by slawekradzyminski** [comment]
Hi @Manakel166 documentation has been updated:

https://github.com/FluentLenium/FluentLenium/pull/813/files

Please let us know if that was all you needed :)
