### ISSUE TITLE
Configuration for Cucumber with Multiple Step Definitions

### ISSUE THREAD

**Issue by richman555** [FluentLenium/FluentLenium#738]
Hello Fluentlenium Community,

Currently, we are extending FluentCucumberTest (classic inheritence) and we have created before and after tagged hooks in a single step definition.  We also extend FluentCucumberTest in other step definition files which are sharing common steps. We are currently using Fluentlenium 3.2.0 and Cucumber 1.2.4 .  We also have future plans to upgrade however it hasn't happened yet and we use JDK 1.8.

It appears that the scope of the selenium driver is only available in the step definition file which contains the before and after hooks.   All other step definition files receive null pointer exceptions due to the driver being null and we are issuing fluent commands in the steps.  All of the step definition files extend FluentCucumberTest. 

We have found that by adding before and after tagged hooks in all step definition files appears to work, however by doing this Cucumber appears to _instance all step definition files for every scenario regardless if they are used or not within the test_.  

This approach doesn't scale very well as the number of step definitions grows (we may end up with hundreds of step definition files within our glue).

Since the issue appears to be with regard to the management and sharing of the driver among steps, is there any recommended approach or documentation describing the setup and configuration with Cucumber?

Attached is the code for our single step definition file which we have created.

Thank you for any help, advice, or documentation!

[ExampleCode.zip](https://github.com/FluentLenium/FluentLenium/files/2881495/ExampleCode.zip)

**Comment by richman555** [comment]
After further thought about this issue, it might be more of an issue with Cucumber however we would need to test its behavior.  It might be possible that once you add a scenario hook or a tagged hook, Cucumber instances all Step Definition classes which contain them.  I believe we may do some further investigation unless someone knows more definitively.   Thanks for any help or advice!

**Comment by koryl** [comment]
Hi @richman555!
I perfectly understand the issue you have found because I have exactly the same problem as you in the past. For me it was highly unintuitive and inefficient - this was the reason I have started to make changes in fluentlenium-cucumber by myslef ;)
Sadly, for FluentLenium 3.2.0 it is not really possible to fix this issue and in older documentation it was addressed directly that you MUST add these hooks for all classes with steps definition.
The fluentlenium-cucumber module was already refactored (from version 3.6.0), but I think it would be work better with upcoming version 3.8.0 (for Java 1.8, https://github.com/FluentLenium/FluentLenium/issues/702) or 4.1.2 (for Java 11).

**Comment by richman555** [comment]
Thanks @koryl ,
I think we may try to upgrade to 3.8.0 (for Java 1.8).   Do you have any details as to what is being changed for cucumber tests in this revision?  Will it still require the before and after hooks for all step definitions?

Thanks for your help!

**Comment by koryl** [comment]
Hi, you can see documentation prepared for upcoming releases on our develop branch: https://github.com/FluentLenium/FluentLenium/blob/develop/docs/docs/test-runners.md#cucumber

It will not require before and after hooks for all classes.

**Comment by richman555** [comment]
Hi @koryl I see that 3.8.1 has been released.  We will test this issue as part of upgrading to this release.   Thanks for your help!

**Comment by koryl** [comment]
No problem :) Let us know if you find any problem.
