### ISSUE TITLE
@Page annotation in cucumber step definition is not getting instantiated with Junit5

### ISSUE THREAD

**Issue by richman555** [FluentLenium/FluentLenium#739]
Hi Fluentlenium Community,

We are working on a test application upgrade to using _Fluentlenium-3.7.1_ and we use JDK 1.8.   We also use _Cucumber-3.0.2_ and _Selenium-3.14.0_ and intend to use _JUnit 5.1.0_ .

What we have noticed is that when using JUnit 5.1.0 the @Page annotation is no longer instanced (null) in any Cucumber Step Definition file.   When we downgrade to Junit 4.12 the @Page annotation is instanced and everything works fine.

Below are the JUnit 5.1.0 dependencies we are attempting to use.

```
<!--junit-->
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>5.1.0</version>
</dependency>
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>5.1.0</version>
</dependency>
<dependency>
    <groupId>org.junit.vintage</groupId>
    <artifactId>junit-vintage-engine</artifactId>
    <version>5.1.0</version>
</dependency>
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <version>1.1.0</version>
</dependency>
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-runner</artifactId>
    <version>1.1.0</version>
</dependency>
<!--junit-->
```
Please let us know if there is any issue using JUnit 5 and using the @Page annotations within Cucumber Step Definitions.   Currently all of our Cucumber Step Definition files extend FluentCucumberTest class.

Thank you for any relevant information, ideas or documentation!

**Comment by koryl** [comment]
Hi! Thank you for reporting your issue. Few ideas from my side:
- Cucumber does not fully support JUnit 5 and it can be one of possible reasons ( details here: https://github.com/cucumber/cucumber-jvm/issues/1149);
- there was already reported similar issue related to TestNG and the newest version should not have problems with creating @page instances. If you cannot update your jdk to jdk 11, we are working of creating additional version for jdk 1.8 which will be realeased as FluentLenium 3.8.0. This realase will introduce update of Cucumber to 4.2.2;
- we have tested integration FluentLenium with Cucumber only for JUnit 4.12, not for JUnit Jupiter 5 or TestNG. I will add additional tests for mentioned libraries and  will get back to you with more information.

**Comment by richman555** [comment]
Thank you for this clarification as this make sense.  We likely will be staying on 1.8 JDK for some time going forward as our test framework also includes MQ Series tests and Spring 4 for SOAP/REST Services and dependency injection and batch testing.  We may get around to it once we can confirm our dependencies can support it.
