### ISSUE TITLE
@findby is coming as null using cucumber 3.0.2 and version 3.7.1

### ISSUE THREAD

**Issue by richman555** [FluentLenium/FluentLenium#746]
Hello Fluentlenium Community,

We are currently working on a upgrade to use Fluentlenium version 3.7.1 and cucumber 3.0.2 (using java 1.8).   We are seeing null values coming for @findby annotations which were working in previous versions.

I believe that we may have found the solution to this in issue #631 and it appears the suggested code does work.   We were wondering what version of Fluentlenium would include a permanent fix.   I have seen mentions here of 3.8.0 and 4.0.0 however I would just like to confirm it.   Also what is the timeline for the 3.8.0 release?

Thanks for your help!

**Comment by koryl** [comment]
Hi, thank you for reporting.

I've checked on the current develop and it should be fixed with the new release.

We will try to make new release in this week, stay in tune.

**Comment by slawekradzyminski** [comment]
Hi @richman555 

New features has been backported to Java 8.

https://github.com/FluentLenium/FluentLenium/releases

**Comment by richman555** [comment]
@slawekradzyminski Thank you!  We will do some testing with this version 3.8.1 and if all is good we will close out this ticket.  Thanks for your help!

**Comment by slawekradzyminski** [comment]
No problem :)
