### ISSUE TITLE
More specific documentation for @PageUrl, screenshotPath and htmlDumpPath

### ISSUE THREAD

**Issue by picimako** [FluentLenium/FluentLenium#750]
Hi,
I've come across some difficulties with the annotation and config properties mentioned in the title.

1. The javadoc for `@PageUrl` seems to be a bit outdated and could be more specific:
 - The `value` attribute is mandatory, so the example for local files would need some update.
 - I haven't managed to make local file targeting work. It could be updated with some concrete examples, like what `{resourcesDirectory}` is, whether it can be configured, what kind of values it can work with in terms of the `file` and the `value` attribute.
 - In terms of parameterization, at least a link to the official documentation could be added.

2. The `screenshotPath` and `htmlDumpPath` configuration properties could use some concrete examples what exact values they can handle. I haven't been able to make them work with either relative or absolute paths. (It may be a bug?)

**Comment by slawekradzyminski** [comment]
Point 1 has been done by @picimako 

Point 2 requires investigation.

**Comment by tamasbalog** [comment]
@slawekradzyminski 
Regarding point 1 I am still not sure what `resourcesDirectory` exactly is, etc. I would appreciate some help with that, than I would update the docs accordingly.

**Comment by slawekradzyminski** [comment]
We have example in integration tests:

```java
/**
     * Converts a file String to a valid URL String.<br>
     * Example: <code>index.html</code> converts to <code>file://C:/path/to/file/index.html</code>.
     *
     * @param file the file String
     * @return the URL String
     */
    public static String getAbsoluteUrlFromFile(String file) {
        if (file == null) {
            throw new IllegalArgumentException("file must not be null");
        }

        URL url = ClassLoader.getSystemResource(file);
        if (url == null) {
            throw new NullPointerException("url from file=" + file + " is null");
        }

        return url.toString();
    }
```

```java
    public static final String JAVASCRIPT_URL = getAbsoluteUrlFromFile("javascript.html");
```

javascript.html is in test resources folder

**Comment by picimako** [comment]
I refined the javadoc for number 1 on https://github.com/picimako/FluentLenium/commit/6ffc98d45f5c83f8bf43b7d1b1309287d0b53d78

**Comment by picimako** [comment]
I've investigated  a little and it seems that both `screenshotPath` and`htmlDumpPath` work properly both for `TriggerMode.AUTOMATIC_ON_FAIL` and via explicit call for screenshot and html dump creation from e.g. FluentWebElement.

I'm closing this ticket for now.
