### ISSUE TITLE
Simplify APIs

### ISSUE THREAD

**Issue by picimako** [FluentLenium/FluentLenium#767]
Hi,

I have some suggestions to simplify a few interfaces:

1. NavigationControl
The `switchTo()` method seems to be doing the same as `switchToDefault()`, so my suggestion is to mark `switchTo()` as deprecated and use `switchToDefault()` instead.

2. Fill
`withText(String...)` does the same as `with(String...)`, so I think one of them could be deprecated.

3. PageUrl
Since the `file` and `isLocalFile` attributes of this annotation are used together, I would remove `isLocalFile` and determine whether the file is local based on whether the `file` attribute is present (as in not empty).
Along with this one I would also recommend to come up with a solution to avoid manually overriding the `isAtUsingUrl(String)` method in order to skip URL check in case of local files.

4. FluentPageControl
The current API of this interface is:
```
String getUrl();
String getUrl(Object... parameters);
void isAt();
void isAt(Object... parameters);
<P extends FluentPage> P go();
<P extends FluentPage> P go(Object... params);
ParsedUrlTemplate parseUrl();
ParsedUrlTemplate parseUrl(String url);
```
I would remove `getUrl()`, `isAt()` and `go()`, they seem to be a bit unnecessary considering that the other variants of these methods accept varargs. So the new API would look like this:
```
String getUrl(Object... parameters);
void isAt(Object... parameters);
<P extends FluentPage> P go(Object... params);
ParsedUrlTemplate parseUrl();
ParsedUrlTemplate parseUrl(String url);
```

I would like to work on these items, but I need confirmation that they are valid ideas.

**Comment by slawekradzyminski** [comment]
Hi @picimako thanks for the suggestion.

Regarding 1 & 2 you are probably right that's unnecessary, but I don't see much value in changing it at this point. Please have in mind that our users just want to bump their version number and have all tests working without any deprecation warnings. Let's leave it for now.

3 is a good point- if you like to work on that you can do it.

4 is also a good point, but the value seems to be marginal. Let's leave it as well.

**Comment by picimako** [comment]
@slawekradzyminski 

Yep, good point. I'll keep that in mind. And I will work on number 3.
Thanks.

**Comment by picimako** [comment]
Closing this ticket as it's scope was only number 3 which is merged.
