### ISSUE TITLE
Ways to set options for drivers in Fluentlenium

### ISSUE THREAD

**Issue by Sonali77** [FluentLenium/FluentLenium#774]
Hi,

  This is not a bug but since i don't have any other place to ask this question, so i am asking you. In selenium, one can set up options for any driver like-
 ChromeOptions chromeOptions=new ChromeOptions();
             chromeOptions.setExperimentalOption("useAutomationExtension",false);
             chromeOptions.addArguments("start-maximized");
             WebDriver capabilitiesChromeWebDriver = new ChromeDriver(chromeOptions);

Similarly, one can set up for IE or Firefox. I am keen in knowing, if there is any way to set up options with respect to fluentlenium. 

Regards,
Sonali

**Comment by picimako** [comment]
Hi @Sonali77 
As I understand your question you may be looking for this one: https://fluentlenium.com/docs/configuration/#custom-webdriver

You can create a custom implementation of `WebDriverFactory` annotated with `@FactoryName`, and the value that you give in that annotation can be referenced in the webDriver configuration property, e.g. via the `@FluentConfiguration` annotation.

```java
@FactoryName("custom")
public class CustomWebDriverFactory implements WebDriverFactory {
    @Override
    public WebDriver newWebDriver(Capabilities desiredCapabilities, ConfigurationProperties configuration) {
        //create your webdriver with the capabilities you need
    }
}
```

```java
@FluentConfiguration(webDriver = "custom")
public class TestClass {
}
```

**Comment by slawekradzyminski** [comment]
Hi @Sonali77 

You can take a look into our examples.

1. FluentConfiguration https://github.com/FluentLenium/FluentLenium/blob/develop/examples/quickstart-chrome/src/test/java/org/fluentlenium/examples/test/DuckDuckGoHeadlessTest.java

```java
@FluentConfiguration(capabilities = "{\"chromeOptions\": {\"args\": [\"headless\",\"disable-gpu\"]}}")
```

2. Overriding newWebDriver method
https://github.com/FluentLenium/FluentLenium/blob/develop/examples/quickstart-firefox/src/test/java/org/fluentlenium/examples/test/DuckDuckGoHeadlessFirefoxTest.java

```java
 @Override
    public WebDriver newWebDriver() {
        FirefoxOptions firefoxOptions = new FirefoxOptions();
        firefoxOptions.addArguments("--headless");
        return new FirefoxDriver(firefoxOptions);
    }
```

There are multiple examples of that in my blog:
https://github.com/slawekradzyminski/AwesomeTesting

Please let us know if our responses have solved your issue :)

**Comment by Sonali77** [comment]
Thanks. Even i am using the  @Override
    public WebDriver newWebDriver() {}
way of doing it. Thanks for the feedback :)

**Comment by slawekradzyminski** [comment]
Great :)
