### ISSUE TITLE
NPE during JUnit/Cucumber test execution

### ISSUE THREAD

**Issue by tamasbalog** [FluentLenium/FluentLenium#790]
#### FL modules used:
- fluentlenium-core
- fluentlenium-cucumber
- fluentlenium-assertj
- fluentlenium-junit

Base class for step definitions:
```java
@FluentConfiguration(...)
public class BaseTest extends FluentCucumberTest {
    ...
}
```

All the step def classes extend `BaseTest`:
```java
public class SomeStepDefs extends BaseTest {
    ...
}
```

And the JUnit test class looks like this:
```java
@RunWith(Cucumber.class)
@CucumberOptions(...)
public class SomeTest {
}
```

### Issue
When a method like `goTo(P)` is called, down in `FluentControlImpl#goTo(P)` the `getFluentControl()` call returns null because the `FluentControlContainer` field was not set a `FluentControl` object.

Note: With this setup the execution falls into the `if (nonNull(configClass)` branch within `FluentObjectFactory#start()`.

### Library versions affected (at least what I tried it with)
- FluentLenium 4.1.1 / Cucumber 3.0.2 
- FluentLenium 4.2.2 / Cucumber 4.2.6

**Comment by koryl** [comment]
@tamasbalog, thank you for report. 
I am not aware from the information you provide why you met NPE in your config. Did you add Before and After hooks in the way mentioned in documantation (https://fluentlenium.com/docs/test-runners/#cucumber)? 
I created example project here and it seems everything works as expected: https://github.com/koryl/fluentlenium-cucumber-config-example
Please, let me know if it helps.

**Comment by picimako** [comment]
@koryl I didn't use any hooks, I was not aware of that setting them up may be a crucial part of execution. I will try that later today.

As for your example project, thank you, but I'm a little bit confused. You created the class `HooksSteps` extending `BaseTest` but it doesn't seem to be used anywhere. Am I missing something?

(Don't be confused, I accidentally used my other account to report this issue. :) )

**Comment by picimako** [comment]
@koryl I managed to make it work.

There were two issues. One is that the hook setup were missing, the other one is that a specific package was set on the glue path as step definitions package, and after adding the hooks in a different package, Cucumber didn't read the hooks.

Thanks for your help. The example project you put together were useful.
