### ISSUE TITLE
Support for other DI Frameworks

### ISSUE THREAD

**Issue by buko** [FluentLenium/FluentLenium#800]
We're using a different DI framework (HK2) and we'd like to be able to inject our own services into Page objects using HK2.

Would it be possible to modify the FluentInjector so that our own code could process a page compnent before injection, after injection and when it is destroyed?

**Comment by slawekradzyminski** [comment]
Hi @buko, thanks for the submission.

FluentInjector is definitely a good candidate for refactoring. We were thinking about easier access (fewer constructor arguments) or even full logic extraction to separate module. 

Pull requests are very welcome in this area so if you want to extend FluentLenium please do so. We can offer help and maybe even maintenance.

However, if you want for us to refactor FluentInjector I can't give you any guarantees that it will be done.
