### ISSUE TITLE
How to extract param from URL?

### ISSUE THREAD

**Issue by fedotxxl** [FluentLenium/FluentLenium#803]
Let's suppose I've got page:

```
public class ProjectReadPage extends FluentPage {
    @Override
    public String getUrl() {
        return "/project/{projectId}";
    }
}
```

and test open Project by clicking on URL `/project/123`. Can I use `projectReadPage` to extract project id from current URL?

**Comment by slawekradzyminski** [comment]
Hi @fedotxxl 

Examples:

```java
@PageUrl("?param1={param1}")
class Page extends FluentPage {
}
```

```java
@Page
private Page page;

 @Test
    void pageParameterTest() {
        page.go("ab").isAt();
    }
```

Please let us know if it helps.

**Comment by slawekradzyminski** [comment]
@fedotxxl Ok - will be added to FL :)

**Comment by picimako** [comment]
@fedotxxl The changes have been added to FluentPage. It will be available in the next release.

Closing the issue.
