### ISSUE TITLE
find gets timeout exception while no element found on version 3.7.0

### ISSUE THREAD

**Issue by motalib** [FluentLenium/FluentLenium#811]
find("tbody tr").stream()
        .map(g -> g.as(SampleClass.class))
        .findFirst()
        .orElse(null);

if no selector is found with this selector, then test case fail with timeout exception.
In that case I had to count first like below
if (find("tbody tr").count() == 0) return null;

**Comment by slawekradzyminski** [comment]
Hi @motalib, thanks for submission :)

We are aware of this issue and track it on #787

**Comment by filipcynarski** [comment]
Not yet, I can schedule it for next release

**Comment by filipcynarski** [comment]
Closing this one as a duplication of:

https://github.com/FluentLenium/FluentLenium/issues/787
https://github.com/FluentLenium/FluentLenium/issues/787
