### ISSUE TITLE
Multiple browsers are opened when using JVM, CLASS or THREAD DriverLifecycle

### ISSUE THREAD

**Issue by swethamarinenisagecom** [FluentLenium/FluentLenium#843]
Hi Team, 

When the DriverLifecycle is set to either JVM, CLASS or THREAD,  when a test suite is run, after one test finishes, the next test is not run in the same browser but a different browser is opened. This is confusing to have two browser instances at the same time. 

When DriverLifecycle is set to METHOD, the browser is closed after every single test. Although this ensures having a clean session every time, a concern is raise in my team that this takes more time for all tests to run.

Using Java 11, FluentTestNg, Chrome browser (Version 73.0.3683.103 (Official Build) (64-bit)).

Problem:- Multiple browsers are opened while running a test suite when the DriverLifecycle is set to either JVM, CLASS or THREAD

Expect:- Single browser to be opened and each test runs in the same browser one after the other.

**Comment by filipcynarski** [comment]
Hello @swethamarinenisagecom,

Expected behaviour which you described may lead to tests destabilisation and cause issues because you have to take care of browser cleanup each time. For example, remaining cookies, browser data like cache if you want to not close the browser each time the test runs you should properly configure tests execution. You mentioned you are using TestNG which type of execution policy you choose?

The reason why it runs a new browser for each test may be because of TestNG configuration, not FluentLenium. The DriverLifecycle tells FL how to manage WebDriver instantiation nothing more.

Could you check is the TestNG creating new JVM for each of your tests? You can easily verify it by listing active JVM processes IDs and checking is the IDs changing or not during execution. If so it means TestNG creates new JVM processes and you have to configure TestNG to execute tests in the same Java process instead of creating new JVM.

Please let me know if something requires more elaboration or attach an example of your project (can be the extarcted configuration of FL and TestNG) so we can dig deeper and help you ;)

Have a good day!

**Comment by swethamarinenisagecom** [comment]
Hi, thanks for your response! 

Not sure why expected behavior would cause destabilization. For example, if the DriverLifecycle is set to CLASS, I would expect a browser to be opened at the beginning, run each test in the class and then close the browser at the end (lets assume no parallel execution specified). 
So the web driver life cycle would be for each class right? Do you expect multiple browsers opened one for each test when the tests in the class are executed ?

I'm not doing any specific configuration for TestNG . I checked JVM while tests are running, there is only one PID. 

*The DriverLifecycle tells FL how to manage WebDriver instantiation nothing more.* --- That is what I was referring to in the problem above.  Only when a WebDriver is instantiated browser is opened, right ? 
When I set DLC (DriverLifeCycle) to CLASS, it should open one browser for all tests in that class, right ? But it opens two browsers which is incorrect and needs to be fixed.

If you think it is TestNG or other configuration issue and would like to see my project files, let me know. I'll send it.

**Comment by slawekradzyminski** [comment]
@swethamarinenisagecom please share TestNG config, we will take a look

**Comment by swethamarinenisagecom** [comment]
Hi, there is no specific configuration for TestNG. I've attached the project for your reference. I had to remove the lib jar and drivers exe files due to size limit. Please take a look and let me know if you need anything else. 
[sp_auto_proj.zip](https://github.com/FluentLenium/FluentLenium/files/3246763/sp_auto_proj.zip)

Thank you!
Swetha.

**Comment by slawekradzyminski** [comment]
Thanks @swethamarinenisagecom 

One more question, how do you run tests in CI/command line? What's the exact command?

**Comment by slawekradzyminski** [comment]
Hi @swethamarinenisagecom again, I was checking your issue :)

I'm afraid the issue may not be on our side. If you comment your `newWebDriver()`` and initFluent()` in `FluentRegTest` the browser isn't closed for lifecycle CLASS and JVM. You can also see copy paste this example and see how it should work in our opinion.

```java
package ic.testng;

import org.fluentlenium.adapter.testng.FluentTestNg;
import org.fluentlenium.configuration.ConfigurationProperties;
import org.fluentlenium.configuration.FluentConfiguration;
import org.openqa.selenium.Cookie;
import org.testng.annotations.Test;

@FluentConfiguration(driverLifecycle = ConfigurationProperties.DriverLifecycle.CLASS, webDriver = "chrome")
public class InternalComsTest extends FluentTestNg {

    @Test(priority = 1)
    public void testICTypeYouTubeRenderInTile() {
        goTo("https://fluentlenium.com");
        getDriver().manage().addCookie(new Cookie("CUSTOM", "1"));
        assert getDriver().manage().getCookieNamed("CUSTOM").getValue().equals("1");
    }

    @Test(priority = 2)
    public void testICTypeYouTubeDoNotRenderInTile() {
        assert getDriver().manage().getCookieNamed("CUSTOM").getValue().equals("1");
    }

}
```

This feature is also covered in fluentlenium-testng integration test (path `package org.fluentlenium.adapter.testng.integration.shareddriver`)

Would it be possible for you to migrate for example to annotation based configuration? You can see examples in docs:
https://fluentlenium.com/docs/configuration/#configuration-ways

Please do not override `initFluent()`method.

Thank you very much for sharing your project, that's really helpful to see how FluentLenium is used world-wide :)

**Comment by swethamarinenisagecom** [comment]
Hi @slawekradzyminski 
Thank you very much for looking into the issue and for your detailed response earlier!

As per your first suggestion I've commented overridden methods newWebDriver() and initFluent() in FluentRegTest. When I run the test suite, I see that browser is closed after every test and all tests are failing, I think it is because the wait times are default values and are not sufficient for this project (default firefox driver is opened after executable system env is set).

And as per your second suggestion, when I do "@FluentConfiguration(driverLifecycle = ConfigurationProperties.DriverLifecycle.CLASS, webDriver = "chrome")" in the test suite, there is only one browser open which is used to run all tests in that test suite. But all tests fail (I think its same wait time issue).

I can see from the fluentlenium-testng integration test (in package org.fluentlenium.adapter.testng.integration.shareddriver) sets the driver life cycle using @FluentConfiguration. But all tests extends IntegrationFluentTestNg which overrides newWebDriver() method. 

I assume, I can do the same in FluentRegTest to override newWebDriver() method as I set specific chrome options that are not available by default. Also I will need it when I need to run tests on browserstack (or any remote server). And also I can set driver life cycle using @FluentConfiguration in FluentRegTest which will be applicable to all tests suites (I prefer this way to set once instead of doing it in every test suite as the config value is same for all).

Can you please explain why you asked not to override initFluent() method ? As you can see currently there are some configurations done in that method. What is the suitable way to override all those without overriding initFluent() method ? It is not clear from https://fluentlenium.com/docs/configuration/#configuration-ways about how all the configs overridden in FluentRegTest can be done using annotations. I know annotations are handy and can be done quickly with less code. But if I'm doing a list of configs (like in initFluent() method in FluentRegTest) I think its better the way its currently done. Please let me know if there are any best practices or standards that I need to know in this case.

Thank you very much for making FluentLenium available for us and also supporting us when we have issues. It has been very quick and useful for us to use FluentLenium as all ground work that we have to normally do when using Selenium is taken care. We are still in the initial stages. We will be having Jenkins job soon, so currently we are not running using maven but are running in IntelliJ IDE. While looking at our project if you have come across any places you think FluentLenium can be used even better or any features that can be used that we have not utilized please let us know.

Many Thanks!
Swetha.

**Comment by slawekradzyminski** [comment]
Hi @swethamarinenisagecom again :)

I think you should override our Configuration methods in your FluentRegTest https://github.com/FluentLenium/FluentLenium/blob/develop/fluentlenium-core/src/main/java/org/fluentlenium/configuration/ConfigurationProperties.java (Please read Javadoc).

Example:

```java
@Override
public DriverLifecycle getDriverLifecycle() {
return CLASS;
}

@Override
public String getWebDriver(){
return "chrome";
}

@Override
public Capabilities getCapabilities(){
return yourCapabilities;
}
```

Regarding browser timeout we have it configured by default on 60 seconds. Maybe you should override it (120 seconds for example)?

```java
@Override
public Long getBrowserTimeout() {
return 120000L;
}
```

Hope it helps :)

**Comment by slawekradzyminski** [comment]
Hi @swethamarinenisagecom, can you please tell me which properties would you expect to be taken into account during initial driver startup?

What documentation changes do you suggest? I have trouble understanding what exactly should we improve.
