### ISSUE TITLE
Configuration using environment variables does not work & should not use invalid dot `.` notation

### ISSUE THREAD

**Issue by alexanderhawley** [FluentLenium/FluentLenium#890]
In the docs, it describes using environment variables to configure FluentLenium. It does not work using a real terminal. Environment variables cannot have dots `.` in them. As an aside, it does happen to work using a pseudo-environment like Intellij. It is also of note that `EXPORT` does't work and needs to be lowercase `export`.

https://fluentlenium.com/docs/configuration/#configuration-ways

Version: 4.3.0

```
$ export fluentlenium.webDriver=chrome && mvn clean test
-bash: export: `fluentlenium.webDriver=chrome': not a valid identifier
```

As a workaround, one must create environment variables without dots, then pass them as Java command line system properties.

```
export fluentlenium_webDriver=chrome && mvn clean test -Dfluentlenium.webDriver=$fluentlenium_webDriver
... tests run
```

**Comment by slawekradzyminski** [comment]
Thanks @alexanderhawley
