### ISSUE TITLE
Add method clearing cookies for every domain

### ISSUE THREAD

**Issue by slawekradzyminski** [FluentLenium/FluentLenium#922]
As stated in title. Selenium doesn't have it.

**Comment by picimako** [comment]
On my previous project we had this problem and we had a couple of brainstorming sessions about this, so the followings are my thoughts from that time.

As far as I know deleting cookies either from Selenium or via JavaScript is only possible on the current domain. That would make it necessary to delete cookies on every domain of the application that has been visited by the tests, and those domains would need to be saved somewhere either automatically or in part manually by the framework users.
That also includes saving not just those domains hat were visited explicitly but that were visited by intermediate redirects, either by the application or by interaction (e.g. click) on a page.
(We had custom logic for redirecting users from the domain they entered in the browser, based on their location, browser language and many more to another domain of the site that would give them more relevant information.)

The framework would also need to be able to store a dedicated URL/path of the application that it could visit after each test (depending on the driver lifecycle) to delete the cookies there.

But I suspect there is/should be a much simpler solution out there.

**Comment by slawekradzyminski** [comment]
Looks like those command are used a lot for example in WebdriverIO
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/protocol/chromium.json

Perhaps we should do some stuff on API level now

**Comment by slawekradzyminski** [comment]
Done
