### ISSUE TITLE
Add .hasTextContaining assertion to assertj module

### ISSUE THREAD

**Issue by slawekradzyminski** [FluentLenium/FluentLenium#934]
I have to write
```java
assertThat(errorMessageInfo.text()).contains(partOfErrorMessage);
```

I'd like to write
```java
assertThat(errorMessageInfo).hasTextContaining(partOfErrorMessage);
```

**Comment by picimako** [comment]
@slawekradzyminski 

The interesting things is that `hasText()` already works as validating whether the element text contains another text, and not equal to that:

```java
@Override
public FluentWebElementAssert hasText(String textToFind) {
    String actualText = actual.text();
    if (!actualText.contains(textToFind)) {
        failWithMessage("The element does not contain the text: " + textToFind
                + ". Actual text found : " + actualText);
    }
    return this;
}
```

I think this may be done in two steps:
- introducing `hasTextContaining()` and letting users adopt it in on release
- in another release change the logic of `hasText()` to validate equality

What do you think?

**Comment by slawekradzyminski** [comment]
@picimako fully agree :)

**Comment by slawekradzyminski** [comment]
It’s Done by @picimako :)
