### ISSUE TITLE
clickAndCloseCurrent() doesn't close window

### ISSUE THREAD

**Issue by Wodress** [FluentLenium/FluentLenium#974]
Hello,

I have a case where I'm trying to open chosen web application from list.
There are buttons representing available applications for current user.
If you click on the app button then new window with this app is invoked.
I'm trying to use clickAndCloseCurrent() method for it but after this new window is opened, the old one is not closed, so I'm ending with :

> org.openqa.selenium.TimeoutException: Expected condition failed: Window CDwindow-62ACF65D611A8BEAEF5CB7B24F8BDCFA should not be displayed. (tried for 5 second(s) with 500 milliseconds interval)

```
public void openApplication(String appName) {
        WebElement appButton = getDriver().findElement(
                By.xpath("//div[@id='main-content']//ul[contains(@class,'app-buttons-list')]//p[contains(text(),'"+appName+"')]/../a")
        );

        window().clickAndCloseCurrent(el(appButton));
        await().untilPage().isLoaded();
    }
```

Is there anything I forgot to think about ?

Thank you

**Comment by slawekradzyminski** [comment]
Hmm, if the window doesn't close I believe you should use `clickAndOpenNew()` method:
https://fluentlenium.com/javadoc/org/fluentlenium/core/action/WindowAction.html#clickAndOpenNew(org.fluentlenium.core.domain.FluentWebElement)

**Comment by Wodress** [comment]
I modified the code a bit and I got what I needed.
I was expecting different behaviour of this method according to documentation but then I realized how it should work when I saw how it is implemented.

This case is not relevant, thank you for your help.
