### ISSUE TITLE
Taking screenshot Cucumber/Fluentlenium

### ISSUE THREAD

**Issue by puresk** [FluentLenium/FluentLenium#979]
Hi, i would like to take screenshot. 

I cant really take it with @ after anotation, cause getDriver() will be null in there..Method takeScreenshot(); works just fine when its directly in my test steps, but not in @ after. 

So i found out it could be done by fluentlenium itself by "AUTOMATIC_ON_FAIL"

not working code with after anotation:

```
    @After(order = 1)
    public void afterScenario(Scenario scenario) throws InterruptedException {
        takeScreenshot();

        //export collected output values to XLS file
        context.writeResults(scenario);
        logger.info("End of scenario {} (id: {})", scenario.getName(), scenario.getId());
    }
```
Err output:

```
java.lang.NullPointerException
	at org.fluentlenium.adapter.FluentAdapter.takeScreenshot(FluentAdapter.java:52)
```

This is my TestBase class:

```
@FluentConfiguration(webDriver = "custom", deleteCookies = FluentConfiguration.BooleanValue.TRUE,
        driverLifecycle = ConfigurationProperties.DriverLifecycle.JVM, screenshotMode = AUTOMATIC_ON_FAIL,
        screenshotPath = "C:\\Example\\path\\Desktop\\scr")
public abstract class TestBase extends FluentCucumberTest {
```

My POM:

```
<java.version>1.8</java.version>
<junit.version>4.13-beta-2</junit.version>
<cucumber.version>3.0.2</cucumber.version>
<selenium.version>3.13.0</selenium.version>
<fluentlenium.version>3.6.1</fluentlenium.version>
<surefire.version>2.22.0</surefire.version>
```

**Comment by picimako** [comment]
Hi @puresk!

I'm not sure if you are using JUnit's own `@After` annotation or the one in FL, `org.fluentlenium.adapter.junit.After`. This latter one is designed to be able to actually take screenshots when AUTOMATIC_ON_FAIL is configured.

Could you try FluentLenium's After annotation and see if it works that way?

**Comment by puresk** [comment]
That help. Thanks!
